GeoPubby: DataURLServlet Class Reference
DataURLServlet Class Reference
Servlet for serving RDF documents containing a description of a given resource.
Public Member Functions
void init () throws ServletException
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
Protected Member Functions
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title)
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes)
void send404 (HttpServletResponse response, String resourceURI) throws IOException
void sendInitialization500 (HttpServletResponse response, String message) throws IOException
String addQueryString (String dataURL, HttpServletRequest request)
Private Member Functions
void addHighDegreePropertyLinks (Model model, HypermediaControls controller)
Static Private Attributes
static final long serialVersionUID = 6825866213915066364L
Detailed Description
Servlet for serving RDF documents containing a description of a given resource.
Member Function Documentation
addDocumentMetadata()
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title) protected inherited
References MetadataConfiguration.addCustomMetadata(), MetadataConfiguration.addMetadataFromTemplate(), ModelUtil.addNSIfUndefined(), HypermediaControls.getAbsoluteIRI(), and Configuration.getDatasets().
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
{
                 ModelUtil.addNSIfUndefined(model, "foaf", FOAF.getURI());
                 ModelUtil.addNSIfUndefined(model, "rdfs", RDFS.getURI());
                 // Add document metadata
                 Resource topic = model.getResource(controller.getAbsoluteIRI());
                 Resource document = model.getResource(documentURL);
                 document.addProperty(FOAF.primaryTopic, topic);
                 document.addProperty(RDFS.label, title);
                 // Add custom metadata
                 for (Dataset dataset: config.getDatasets()) {
                         MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                         metadata.addCustomMetadata(model, document);
                         metadata.addMetadataFromTemplate(model, controller);
                 }
         }
addHighDegreePropertyLinks()
void addHighDegreePropertyLinks (Model model, HypermediaControls controller) private
References HypermediaControls.getAbsoluteIRI(), HypermediaControls.getInverseValuesDataURL(), and HypermediaControls.getValuesDataURL().
Referenced by DataURLServlet.doGet().
{
                 // TODO: This should re-use the logic from ResourceDescription and ResourceProperty to decide where to create these links
                 // Add links to RDF documents with descriptions of the blank nodes
                 Resource r = model.getResource(controller.getAbsoluteIRI());
                 StmtIterator it = r.listProperties();
                 while (it.hasNext()) {
                         Statement stmt = it.nextStatement();
                         if (!stmt.getObject().isAnon()) continue;
                         String pathDataURL = controller.getValuesDataURL(stmt.getPredicate());
                         if (pathDataURL == null) continue;
                         ((Resource) stmt.getResource()).addProperty(RDFS.seeAlso,
                                         model.createResource(pathDataURL));
                 }
                 it = model.listStatements(null, null, r);
                 while (it.hasNext()) {
                         Statement stmt = it.nextStatement();
                         if (!stmt.getSubject().isAnon()) continue;
                         String pathDataURL = controller.getInverseValuesDataURL(stmt.getPredicate());
                         if (pathDataURL == null) continue;
                         ((Resource) stmt.getSubject().as(Resource.class)).addProperty(RDFS.seeAlso,
                                         model.createResource(pathDataURL));
                 }
         }
addPageMetadata()
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes) protected inherited
References MetadataConfiguration.addMetadataFromTemplate(), BaseServlet.doGet(), and Configuration.getDatasets().
Referenced by PageURLServlet.doGet(), and ValuesURLServlet.doGet().
{
                 try {
                         Model metadataModel = ModelFactory.createDefaultModel();
                         for (Dataset dataset: config.getDatasets()) {
                                 MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                                 Resource document = metadata.addMetadataFromTemplate(metadataModel, controller);
                                 // Replaced the commented line by the following one because the
                                 // RDF graph we want to talk about is a specific representation
                                 // of the data identified by the getDataURL() URI.
                                 //                                       Olaf, May 28, 2010
                                 // context.put("metadata", metadata.getResource(resource.getDataURL()));
                                 context.put("metadata", document);
                         }
                         Map<String,String> nsSet = metadataModel.getNsPrefixMap();
                         nsSet.putAll(prefixes.getNsPrefixMap());
                         context.put("prefixes", nsSet.entrySet());
                         context.put("blankNodesMap", new HashMap<Resource,String>());
                 }
                 catch (Exception e) {
                         context.put("metadata", Boolean.FALSE);
                 }
         }
addQueryString()
String addQueryString (String dataURL, HttpServletRequest request) protected inherited
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
{
                 if (request.getParameter("output") == null) {
                         return dataURL;
                 }
                 return dataURL + "?output=" + request.getParameter("output");
         }
doGet() [1/2]
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException protected
References BaseServlet.addDocumentMetadata(), DataURLServlet.addHighDegreePropertyLinks(), BaseServlet.addQueryString(), BaseServlet.config, HypermediaControls.getAbsoluteIRI(), Configuration.getControls(), HypermediaControls.getDataURL(), ResourceDescription.getModel(), HypermediaControls.getResourceDescription(), and ResourceDescription.getTitle().
{
                 HypermediaControls controller = config.getControls(relativeURI, false);
                 ResourceDescription description = controller == null ?
                                 null : controller.getResourceDescription();
                 // Check if resource exists in dataset
                 if (description == null) {
                         response.setStatus(404);
                         response.setContentType("text/plain");
                         response.getOutputStream().println("Nothing known about <" + controller.getAbsoluteIRI() + ">");
                         return true;
                 }
                 Model model = description.getModel();
                 addHighDegreePropertyLinks(model, controller);
                 addDocumentMetadata(model, controller,
                                 addQueryString(controller.getDataURL(), request),
                                 "RDF description of " + description.getTitle());
                 ModelResponse server = new ModelResponse(model, request, response);
                 server.serve();
                 return true;
         }
doGet() [2/2]
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException inherited
References BaseServlet.doGet(), BaseServlet.send404(), and BaseServlet.sendInitialization500().
{
                 if (initError != null) {
                         sendInitialization500(response, initError);
                         return;
                 }
                 String relativeURI = request.getRequestURI().substring(
                                 request.getContextPath().length() + request.getServletPath().length());
                 // Some servlet containers keep the leading slash, some don't
                 if (!"".equals(relativeURI) && "/".equals(relativeURI.substring(0, 1))) {
                         relativeURI = relativeURI.substring(1);
                 }
                 if (!doGet(relativeURI, request, response, config)) {
                         send404(response, null);
                 }
         }
init()
void init () throws ServletException inherited
References ServletContextInitializer.ERROR_MESSAGE, ServletContextInitializer.initConfiguration(), and ServletContextInitializer.SERVER_CONFIGURATION.
{
                 config = (Configuration) getServletContext().getAttribute(
                                 ServletContextInitializer.SERVER_CONFIGURATION);
                 if (config == null) {
                     ServletContextInitializer.initConfiguration(getServletContext());
                     config = (Configuration) getServletContext().getAttribute(
                                 ServletContextInitializer.SERVER_CONFIGURATION);
                         if(config==null){
                             initError = (String) getServletContext().getAttribute(
                                         ServletContextInitializer.ERROR_MESSAGE);
                         }
                 }
         }
send404()
void send404 (HttpServletResponse response, String resourceURI) throws IOException protected inherited
References Configuration.getProjectLink(), Configuration.getProjectName(), and Configuration.getWebApplicationBaseURI().
Referenced by BaseServlet.doGet().
{
                 response.setStatus(404);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("project_name", config.getProjectName());
                 context.put("project_link", config.getProjectLink());
                 context.put("server_base", config.getWebApplicationBaseURI());
                 context.put("title", "404 Not Found");
                 if (resourceURI != null) {
                         context.put("uri", resourceURI);
                 }
                 template.renderXHTML("404.vm");
         }
sendInitialization500()
void sendInitialization500 (HttpServletResponse response, String message) throws IOException protected inherited
Referenced by BaseServlet.doGet().
{
                 response.setStatus(500);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("message", message);
                 context.put("title", "Configuration error");
                 template.renderXHTML("500init.vm");
         }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 6825866213915066364L static private