GeoPubby: GPXWriter Class Reference
GPXWriter Class Reference
Writes a GeoPubby instance as GPX.
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Detailed Description
Writes a GeoPubby instance as GPX.
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
References GEO.ASWKT, GEO.GEORSSPOINT, GEO.P625, GEO.P_GEOMETRY, GEO.P_LAT, GEO.P_LONG, ModelWriter.reader, and ModelWriter.usedProperty.
{
                 ExtendedIterator<Resource> it = super.write(model, response);
                 if (!it.hasNext()) {
                         response.getWriter().write("");
                         response.getWriter().close();
                 } else {
                         XMLOutputFactory factory = XMLOutputFactory.newInstance();
                         StringWriter strwriter = new StringWriter();
                         try {
                                 XMLStreamWriter writer = new IndentingXMLStreamWriter(factory.createXMLStreamWriter(strwriter));
                                 writer.writeStartDocument();
                                 // writer.setPrefix("gml","http://www.opengis.net/gml");
                                 writer.writeStartElement("http://www.topografix.com/GPX/1/1", "gpx");
                                 writer.writeDefaultNamespace("http://www.topografix.com/GPX/1/1");
                                 writer.writeNamespace("gml", "http://www.opengis.net/gml");
                                 Map<String, String> ns = new TreeMap<String, String>();
                                 while (it.hasNext()) {
                                         Resource ind = it.next();
                                         StmtIterator it2 = ind.listProperties();
                                         int nscounter = 1;
                                         while (it2.hasNext()) {
                                                 Statement curst = it2.next();
                                                 String nss = curst.getPredicate().getURI().toString().substring(0,
                                                                 curst.getPredicate().getURI().toString().lastIndexOf('/'));
                                                 if (!ns.containsKey(nss)) {
                                                         writer.setPrefix("ns" + nscounter, nss);
                                                         writer.writeNamespace("ns" + nscounter, nss);
                                                         ns.put(nss, "ns" + nscounter++);
                                                 }
                                         }
                                 }
                                 it.close();
                                 it = model.listResourcesWithProperty(usedProperty);
                                 while (it.hasNext()) {
                                         Resource ind = it.next();
                                         StmtIterator it2 = ind.listProperties();
                                         Double lat = null, lon = null;
                                         while (it2.hasNext()) {
                                                 Statement curst = it2.next();
                                                 if (GEO.ASWKT.getURI().equals(curst.getPredicate().getURI().toString())
                                                                 || GEO.P_GEOMETRY.getURI().equals(curst.getPredicate().getURI())
                                                                 || GEO.P625.getURI().equals(curst.getPredicate().getURI())) {
                                                         try {
                                                                 Geometry geom = reader.read(curst.getObject().asLiteral().getString());
                                                                 writer.writeStartElement("http://www.opengis.net/gml", geom.getGeometryType());
                                                                 writer.writeStartElement("http://www.opengis.net/gml", "posList");
                                                                 writer.writeCharacters(lat + " " + lon);
                                                                 writer.writeEndElement();
                                                                 writer.writeEndElement();
                                                         } catch (ParseException e) {
                                                                 // TODO Auto-generated catch block
                                                                 e.printStackTrace();
                                                         }
                                                 } else if (GEO.P_LAT.getURI().equals(curst.getPredicate().getURI().toString())) {
                                                         lat = curst.getObject().asLiteral().getDouble();
                                                 } else if (GEO.P_LONG.getURI().equals(curst.getPredicate().getURI().toString())) {
                                                         lon = curst.getObject().asLiteral().getDouble();
                                                 } else if (GEO.GEORSSPOINT.getURI().equals(curst.getPredicate().getURI().toString())) {
                                                         lat = Double.valueOf(curst.getObject().asLiteral().getString().split(" ")[0]);
                                                         lon = Double.valueOf(curst.getObject().asLiteral().getString().split(" ")[1]);
                                                 } else {
                                                         String namespace = curst.getPredicate().toString().substring(0,
                                                                         curst.getPredicate().toString().lastIndexOf('/'));
                                                         String last = curst.getPredicate().toString()
                                                                         .substring(curst.getPredicate().toString().lastIndexOf('/') + 1);
                                                         if (ns.containsKey(namespace)) {
                                                                 writer.writeStartElement(namespace, last);
                                                                 if (curst.getObject().toString().contains("^^")) {
                                                                         writer.writeCharacters(curst.getObject().toString().substring(0,
                                                                                         curst.getObject().toString().lastIndexOf("^^")));
                                                                 } else {
                                                                         writer.writeCharacters(curst.getObject().toString());
                                                                 }
                                                                 writer.writeEndElement();
                                                         } else {
                                                                 writer.writeStartElement(curst.getPredicate().toString());
                                                                 if (curst.getObject().toString().contains("^^")) {
                                                                         writer.writeCharacters(curst.getObject().toString().substring(0,
                                                                                         curst.getObject().toString().lastIndexOf("^^")));
                                                                 } else {
                                                                         writer.writeCharacters(curst.getObject().toString());
                                                                 }
                                                                 writer.writeEndElement();
                                                         }
                                                 }
                                                 if (lon != null && lat != null) {
                                                         writer.writeStartElement("wpt");
                                                         writer.writeAttribute("lat", lat + "");
                                                         writer.writeAttribute("lon", lon + "");
                                                         // collectColumns(writer,
                                                         // geojson.getJSONArray("features").getJSONObject(i).getJSONObject("properties"),"");
                                                         writer.writeEndElement();
                                                         lat = null;
                                                         lon = null;
                                                 }
                                         }
                                 }
                                 writer.writeEndElement();
                                 writer.writeEndDocument();
                                 writer.flush();
                         } catch (XMLStreamException e1) {
                                 // TODO Auto-generated catch block
                                 e1.printStackTrace();
                         }
                         response.getWriter().write(strwriter.toString());
                         response.getWriter().close();
                 }
                 return null;
         }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GeoURIWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), GeoJSONWriterr.write(), CSVWriter.write(), KMLWriter.write(), GMLWriter.write(), OSMWriter.write(), SVGWriter.write(), and GPXWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), OSMWriter.write(), GMLWriter.write(), and GPXWriter.write().