GeoPubby: ContentTypeNegotiator.VariantSpec Class Reference
ContentTypeNegotiator.VariantSpec Class Reference
Public Member Functions
VariantSpec (String mediaType)
VariantSpec addAliasMediaType (String mediaType)
void makeDefault ()
MediaRangeSpec getMediaType ()
boolean isDefault ()
List< MediaRangeSpec > getAliases ()
Private Attributes
MediaRangeSpec type
List< MediaRangeSpec > aliases = new ArrayList<MediaRangeSpec>()
boolean isDefault = false
Constructor & Destructor Documentation
VariantSpec()
VariantSpec (String mediaType)
References MediaRangeSpec.parseType().
{
                         type = MediaRangeSpec.parseType(mediaType);
                 }
Member Function Documentation
addAliasMediaType()
VariantSpec addAliasMediaType (String mediaType)
References MediaRangeSpec.parseType().
Referenced by ContentTypeNegotiatorTest.testAcceptAlias(), and ContentTypeNegotiatorTest.testUseAliasQuality().
{
                         aliases.add(MediaRangeSpec.parseType(mediaType));
                         return this;
                 }
getAliases()
List<MediaRangeSpec> getAliases ()
References ContentTypeNegotiator.VariantSpec.aliases.
Referenced by ContentTypeNegotiator.Negotiation.negotiate().
{
                         return aliases;
                 }
getMediaType()
MediaRangeSpec getMediaType ()
References ContentTypeNegotiator.VariantSpec.type.
Referenced by ContentTypeNegotiator.Negotiation.negotiate().
{
                         return type;
                 }
isDefault()
boolean isDefault ()
{
                         return isDefault;
                 }
makeDefault()
void makeDefault ()
Referenced by ContentTypeNegotiatorTest.testUseDefaultIfNoMatch(), and ContentTypeNegotiatorTest.testUseDefaultIfTwoEqualOptions().
{
                         isDefault = true;
                 }
Member Data Documentation
aliases
List<MediaRangeSpec> aliases = new ArrayList<MediaRangeSpec>() private
Referenced by ContentTypeNegotiator.VariantSpec.getAliases().
isDefault
boolean isDefault = false private
Referenced by ContentTypeNegotiator.Negotiation.negotiate().
type
MediaRangeSpec type private
Referenced by ContentTypeNegotiator.VariantSpec.getMediaType().