GeoPubby: GoogleMapsLinkWriter Class Reference
GoogleMapsLinkWriter Class Reference
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
References GEO.ASWKT, GEO.GEORSSPOINT, GEO.P625, GEO.P_GEOMETRY, GEO.P_LAT, GEO.P_LONG, and ModelWriter.reader.
{
                 ExtendedIterator<Resource> it=super.write(model, response);
                 Double lat = null, lon = null;
         Geometry geom=null;
                 while (it.hasNext()) {
                         Resource ind = it.next();
                         StmtIterator it2 = ind.listProperties();
                         while (it2.hasNext()) {
                                 Statement curst = it2.next();
                                 if (GEO.ASWKT.getURI().equals(curst.getPredicate().getURI().toString())
                                                 || GEO.P_GEOMETRY.getURI().equals(curst.getPredicate().getURI())
                                                 || GEO.P625.getURI().equals(curst.getPredicate().getURI())) {
                                         try {
                                                 geom = reader.read(curst.getObject().asLiteral().getString());
                                         } catch (ParseException e) {
                                                 // TODO Auto-generated catch block
                                                 e.printStackTrace();
                                         }
                                 } else if (GEO.P_LAT.getURI().equals(curst.getPredicate().getURI().toString())) {
                                         lat = curst.getObject().asLiteral().getDouble();
                                 } else if (GEO.P_LONG.getURI().equals(curst.getPredicate().getURI().toString())) {
                                         lon = curst.getObject().asLiteral().getDouble();
                                 } else if (GEO.GEORSSPOINT.getURI().equals(curst.getPredicate().getURI().toString())) {
                                         lat = Double.valueOf(curst.getObject().asLiteral().getString().split(" ")[0]);
                                         lon = Double.valueOf(curst.getObject().asLiteral().getString().split(" ")[1]);
                                 }
                         }
                 }
                 try {
                         if(geom!=null) {
                                 Point p=geom.getCentroid();
                                 response.getWriter().write("http://www.google.com/maps/place/"+p.getX()+","+p.getY());
                                 response.getWriter().close();
                         }else if (lat != null || lon != null) {
                                 response.getWriter().write("http://www.google.com/maps/place/"+lat+","+lon);
                                 response.getWriter().close();
                         }else{
                                 response.getWriter().write("");
                                 response.getWriter().close();
                         }
                 } catch (JSONException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return null;
         }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GoogleMapsLinkWriter.write(), GeoURIWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), GeoJSONWriterr.write(), CSVWriter.write(), KMLWriter.write(), GMLWriter.write(), OSMWriter.write(), GPXWriter.write(), and SVGWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), GPXWriter.write(), GMLWriter.write(), and OSMWriter.write().