GeoPubby: ModelResponse.RDFXMLWriter Class Reference
ModelResponse.RDFXMLWriter Class Reference
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
{
                         RDFWriter writer = model.getWriter("RDF/XML-ABBREV");
                         writer.setProperty("showXmlDeclaration", "true");
                         // From Joseki -- workaround for the j.cook.up bug.
                         writer.setProperty("blockRules", "propertyAttr");
                         writer.write(model,
                                         new OutputStreamWriter(response.getOutputStream(), "utf-8"), null);
                         return null;
                 }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GeoURIWriter.write(), WKTWriter.write(), GeoJSONWriterr.write(), CSVWriter.write(), KMLWriter.write(), GMLWriter.write(), GPXWriter.write(), SVGWriter.write(), and OSMWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), OSMWriter.write(), GMLWriter.write(), and GPXWriter.write().