GeoPubby: ModelResponse.TrigWriter Class Reference
ModelResponse.TrigWriter Class Reference
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
{
                         model.getWriter("TriG").write(model, response.getOutputStream(), null);
                         return null;
                 }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GeoURIWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), GeoJSONWriterr.write(), CSVWriter.write(), KMLWriter.write(), GPXWriter.write(), GMLWriter.write(), SVGWriter.write(), and OSMWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), GPXWriter.write(), GMLWriter.write(), and OSMWriter.write().