GeoPubby: Dataset Class Reference
Dataset Class Reference
A dataset block in the server's configuration.
Public Member Functions
Dataset (Resource dataset, Configuration configuration)
DataSource getDataSource ()
MetadataConfiguration getMetadataConfiguration ()
boolean supportsIRIs ()
boolean addSameAsStatements ()
boolean supportsSPARQL11 ()
Set< String > getBrowsableNamespaces ()
Gets all values of conf:browsableNamespace declared on the dataset resource.
Resource getSelf ()
Model getModel ()
boolean hasType (Resource class_)
boolean hasProperty (Property p)
Resource getResource (Property p)
Set< Resource > getResources (Property p)
Set< Property > getProperties (Property p)
String getIRI (Property p)
String getIRI (Property p, String defaultValue)
String getRequiredIRI (Property p)
Set< String > getIRIs (Property p)
String getString (Property p)
String getString (Property p, String defaultValue)
Set< String > getStrings (Property p)
boolean getBoolean (Property p, boolean defaultValue)
void requireExactlyOneOf (Property... properties)
Public Attributes
String datasetBase
Private Member Functions
DataSource buildDataSource (Configuration configuration)
Private Attributes
final DataSource dataSource
final MetadataConfiguration metadata
RemoteSPARQLDataSource sparqlDataSource = null
Detailed Description
A dataset block in the server's configuration.
Constructor & Destructor Documentation
Dataset()
Dataset (Resource dataset, Configuration configuration)
References Dataset.buildDataSource().
{
                 super(dataset);
                 dataSource = buildDataSource(configuration);
                 metadata = new MetadataConfiguration(dataset, sparqlDataSource);
         }
Member Function Documentation
addSameAsStatements()
boolean addSameAsStatements ()
References CONF.addSameAsStatements, and ResourceReader.getBoolean().
Referenced by Dataset.buildDataSource().
{
                 return getBoolean(CONF.addSameAsStatements, false);
         }
buildDataSource()
DataSource buildDataSource (Configuration configuration) private
References RemoteSPARQLDataSource.addGraphQueryParam(), Dataset.addSameAsStatements(), RemoteSPARQLDataSource.addSelectQueryParam(), CONF.AnnotationProvider, CONF.anonymousInversePropertyDescriptionQuery, CONF.anonymousPropertyDescriptionQuery, IRIRewriter.chain(), CONF.contentType, IRIRewriter.createNamespaceBased(), CONF.datasetBase, CONF.datasetURIPattern, Dataset.getBrowsableNamespaces(), Configuration.getBrowsableNamespaces(), VocabularyStore.getHighIndegreeProperties(), VocabularyStore.getHighOutdegreeProperties(), ResourceReader.getIRI(), ResourceReader.getIRIs(), ResourceReader.getString(), ResourceReader.getStrings(), Configuration.getVocabularyStore(), Configuration.getWebApplicationBaseURI(), Configuration.getWebResourcePrefix(), ResourceReader.hasProperty(), ResourceReader.hasType(), IRIRewriter.identity, CONF.inversePropertyListQuery, CONF.loadRDF, CONF.propertyListQuery, CONF.queryParamGraph, CONF.queryParamSelect, ResourceReader.requireExactlyOneOf(), CONF.resourceDescriptionQuery, RemoteSPARQLDataSource.setGraphContentType(), Dataset.sparqlDataSource, CONF.sparqlDefaultGraph, CONF.sparqlEndpoint, Dataset.supportsIRIs(), and Dataset.supportsSPARQL11().
Referenced by Dataset.Dataset().
{
                 requireExactlyOneOf(CONF.sparqlEndpoint, CONF.loadRDF);
                 DataSource result;
                 if (hasProperty(CONF.sparqlEndpoint)) {
                         // SPARQL data source
                         String endpointURL = getIRI(CONF.sparqlEndpoint);
                         String defaultGraphURI = getIRI(CONF.sparqlDefaultGraph);
                         sparqlDataSource = new RemoteSPARQLDataSource(
                                         endpointURL,
                                         defaultGraphURI,
                                         supportsSPARQL11(),
                                         getStrings(CONF.resourceDescriptionQuery),
                                         getStrings(CONF.propertyListQuery),
                                         getStrings(CONF.inversePropertyListQuery),
                                         getStrings(CONF.anonymousPropertyDescriptionQuery),
                                         getStrings(CONF.anonymousInversePropertyDescriptionQuery),
                                         configuration.getVocabularyStore().getHighIndegreeProperties(),
                                         configuration.getVocabularyStore().getHighOutdegreeProperties());
                         if (hasProperty(CONF.contentType)) {
                                 sparqlDataSource.setGraphContentType(getString(CONF.contentType));
                         }
                         for (String param: getStrings(CONF.queryParamSelect)) {
                                 sparqlDataSource.addSelectQueryParam(param);
                         }
                         for (String param: getStrings(CONF.queryParamGraph)) {
                                 sparqlDataSource.addGraphQueryParam(param);
                         }
                         result = sparqlDataSource;
                 } else {
                         // File data source
                         Model data = ModelFactory.createDefaultModel();
                         for (String fileName: getIRIs(CONF.loadRDF)) {
                                 // If the location is a local file, then use webBase as base URI
                                 // to resolve relative URIs in the file. Having file:/// URIs in
                                 // there would likely not be useful to anyone.
                                 fileName = IRIResolver.resolveFileURL(fileName);
                                 String base = (fileName.startsWith("file:/") ?
                                                 configuration.getWebApplicationBaseURI() : fileName);
                                 try {
                                         Model m = FileManager.get().loadModel(fileName, base, null);
                                         data.add(m);
                                         // We'd like to do simply data.setNsPrefix(m), but that leaves relative
                                         // namespace URIs like <#> unresolved, so we do a big dance to make them
                                         // absolute.
                                         for (String prefix: m.getNsPrefixMap().keySet()) {
                                                 IRI uri = IRIResolver.resolve(m.getNsPrefixMap().get(prefix), base);
                                                 data.setNsPrefix(prefix, uri.toString());
                                         }
                                 } catch (JenaException ex) {
                                         throw new ConfigurationException("Error reading <" + fileName + ">: " + ex.getMessage());
                                 }
                         }
                         result = new ModelDataSource(data);
                 }
                 // If conf:datasetURIPattern is set, then filter the dataset accordingly.
                 if (hasProperty(CONF.datasetURIPattern)) {
                         final Pattern pattern = Pattern.compile(getString(CONF.datasetURIPattern));
                         final DataSource fresult=result;
                         result = new FilteredDataSource(fresult) {
                                 @Override
                                 public boolean canDescribe(String absoluteIRI) {
                                         return pattern.matcher(absoluteIRI).find();
                                 }
                                 @Override
                                 public Model describeResource(String absoluteIRI, String language) {
                                         // TODO Auto-generated method stub
                                         return null;
                                 }
                         };
                 }
                 IRIRewriter rewriter = IRIRewriter.identity;
                 // If conf:datasetBase is set (and different from conf:webBase),
                 // rewrite the IRIs accordingly
                 // Base IRI for IRIs considered to be "in" the data source
                 String fullWebBase = configuration.getWebApplicationBaseURI() +
                                 configuration.getWebResourcePrefix();
                 datasetBase = getIRI(CONF.datasetBase,
                                 fullWebBase);
                 if (!datasetBase.equals(fullWebBase)) {
                         rewriter = IRIRewriter.createNamespaceBased(datasetBase, fullWebBase);
                 }
                 // Escape special characters in IRIs
                 rewriter = IRIRewriter.chain(rewriter, new PubbyIRIEscaper(
                                 fullWebBase, !supportsIRIs()));
                 result = new RewrittenDataSource(
                                 result, rewriter, addSameAsStatements());
                 // Determine all browsable namespaces for this dataset
                 final Set<String> browsableNamespaces = new HashSet<String>();
                 browsableNamespaces.add(fullWebBase);
                 for (String iri: getBrowsableNamespaces()) {
                         browsableNamespaces.add(iri);
                 }
                 browsableNamespaces.addAll(configuration.getBrowsableNamespaces());
                 // Filter the dataset to keep only those resources in the datasetBase
                 // and in browsable namespaces, unless it's an annotation provider
                 if (!hasType(CONF.AnnotationProvider)) {
                         final DataSource fresult=result;
                         result = new FilteredDataSource(fresult) {
                                 @Override
                                 public boolean canDescribe(String absoluteIRI) {
                                         for (String namespace: browsableNamespaces) {
                                                 if (absoluteIRI.startsWith(namespace)) return true;
                                         }
                                         return false;
                                 }
                                 @Override
                                 public Model describeResource(String absoluteIRI, String language) {
                                         // TODO Auto-generated method stub
                                         return null;
                                 }
                         };
                 }
                 return result;
         }
getBoolean()
boolean getBoolean (Property p, boolean defaultValue) inherited
References ResourceReader.assertHasOneValue(), ResourceReader.assertLiteralValue(), and ResourceReader.raiseUnexpectedDatatype().
Referenced by Dataset.addSameAsStatements(), Configuration.showLabels(), Dataset.supportsIRIs(), and Dataset.supportsSPARQL11().
{
                 if (!resource.hasProperty(p)) {
                         return defaultValue;
                 }
                 assertHasOneValue(p);
                 assertLiteralValue(p);
                 Literal value = resource.getProperty(p).getLiteral();
                 if (XSD.xboolean.getURI().equals(value.getDatatypeURI())) {
                         return value.getBoolean();
                 }
                 if (value.getDatatypeURI() == null || XSD.xstring.getURI().equals(value.getDatatypeURI())) {
                         if ("true".equals(value.getString().toLowerCase())
                                         || "false".equals(value.getString().toLowerCase())) {
                                 return "true".equals(value.getString().toLowerCase());
                         }
                 }
                 raiseUnexpectedDatatype("xsd:boolean", resource.getProperty(p));
                 return false;
         }
getBrowsableNamespaces()
Set<String> getBrowsableNamespaces ()
Gets all values of conf:browsableNamespace declared on the dataset resource.
Does not include values inherited from the configuration resource.
Returns
Namespace IRIs of browsable namespaces
References CONF.browsableNamespace, and ResourceReader.getIRIs().
Referenced by Dataset.buildDataSource(), and Configuration.Configuration().
{
                 return getIRIs(CONF.browsableNamespace);
         }
getDataSource()
DataSource getDataSource ()
References Dataset.dataSource.
{
                 return dataSource;
         }
getIRI() [1/2]
String getIRI (Property p) inherited
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), Configuration.getProjectLink(), ResourceReader.getRequiredIRI(), and MetadataConfiguration.MetadataConfiguration().
{
                 return getIRI(p, null);
         }
getIRI() [2/2]
String getIRI (Property p, String defaultValue) inherited
References ResourceReader.assertHasOneValue(), and ResourceReader.assertIRIValue().
{
                 if (!resource.hasProperty(p)) return defaultValue;
                 assertHasOneValue(p);
                 assertIRIValue(p);
                 return resource.getProperty(p).getResource().getURI();
         }
getIRIs()
Set<String> getIRIs (Property p) inherited
References ResourceReader.assertIRIValue().
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), Dataset.getBrowsableNamespaces(), and Configuration.getBrowsableNamespaces().
{
                 Set<String> result = new HashSet<String>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertIRIValue(stmt);
                         result.add(stmt.getResource().getURI());
                 }
                 return result;
         }
getMetadataConfiguration()
MetadataConfiguration getMetadataConfiguration ()
References Dataset.metadata.
{
                 return metadata;
         }
getModel()
Model getModel () inherited
Referenced by MetadataConfiguration.addMetadataFromTemplate(), Configuration.Configuration(), MetadataConfiguration.parsePlaceholder(), and ResourceReader.pretty().
{
                 return resource.getModel();
         }
getProperties()
Set<Property> getProperties (Property p) inherited
References ResourceReader.getResources().
Referenced by Configuration.Configuration().
{
                 Set<Property> result = new HashSet<Property>();
                 for (Resource r: getResources(p)) {
                         result.add(r.as(Property.class));
                 }
                 return result;
         }
getRequiredIRI()
String getRequiredIRI (Property p) inherited
References ResourceReader.getIRI(), and ResourceReader.raiseMissingProperty().
Referenced by Configuration.Configuration().
{
                 if (!resource.hasProperty(p)) {
                         raiseMissingProperty(p);
                 }
                 return getIRI(p);
         }
getResource()
Resource getResource (Property p) inherited
References ResourceReader.assertHasOneValue(), and ResourceReader.assertResourceValue().
Referenced by MetadataConfiguration.MetadataConfiguration().
{
                 if (!resource.hasProperty(p)) return null;
                 assertHasOneValue(p);
                 assertResourceValue(p);
                 return resource.getProperty(p).getResource();
         }
getResources()
Set<Resource> getResources (Property p) inherited
References ResourceReader.assertResourceValue().
Referenced by Configuration.Configuration(), and ResourceReader.getProperties().
{
                 Set<Resource> result = new HashSet<Resource>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertResourceValue(stmt);
                         result.add(stmt.getResource());
                 }
                 return result;
         }
getSelf()
Resource getSelf () inherited
References ResourceReader.resource.
Referenced by MetadataConfiguration.parsePlaceholder().
{
                 return resource;
         }
getString() [1/2]
String getString (Property p) inherited
Referenced by Dataset.buildDataSource(), Configuration.getDefaultLanguage(), Configuration.getProjectName(), and Configuration.getWebResourcePrefix().
{
                 return getString(p, null);
         }
getString() [2/2]
String getString (Property p, String defaultValue) inherited
References ResourceReader.assertHasOneValue(), and ResourceReader.assertString().
{
                 if (!resource.hasProperty(p)) {
                         return defaultValue;
                 }
                 assertHasOneValue(p);
                 assertString(resource.getProperty(p));
                 return resource.getProperty(p).getString();
         }
getStrings()
Set<String> getStrings (Property p) inherited
References ResourceReader.assertString().
Referenced by Dataset.buildDataSource().
{
                 Set<String> result = new HashSet<String>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertString(stmt);
                         result.add(stmt.getString());
                 }
                 return result;
         }
hasProperty()
boolean hasProperty (Property p) inherited
Referenced by Dataset.buildDataSource(), Configuration.buildDataSource(), and Configuration.Configuration().
{
                 return resource.hasProperty(p);
         }
hasType()
boolean hasType (Resource class_) inherited
Referenced by Dataset.buildDataSource().
{
                 return resource.hasProperty(RDF.type, class_);
         }
requireExactlyOneOf()
void requireExactlyOneOf (Property... properties) inherited
References ResourceReader.pretty().
Referenced by Dataset.buildDataSource().
{
                 Property found = null;
                 boolean first = true;
                 StringBuilder s = new StringBuilder();
                 for (Property p: properties) {
                         if (resource.hasProperty(p)) {
                                 if (found == null) {
                                         found = p;
                                 } else {
                                         throw new ConfigurationException("Can't have both " +
                                                         pretty(found) + " and " + pretty(p) +
                                                         " on resource " + pretty(resource));
                                 }
                         }
                         if (!first) {
                                 s.append(", ");
                         }
                         s.append(pretty(p));
                         first = false;
                 }
                 if (found == null) {
                         throw new ConfigurationException("One of " + s.toString() +
                                         " required on resource " + pretty(resource));
                 }
         }
supportsIRIs()
boolean supportsIRIs ()
References ResourceReader.getBoolean(), and CONF.supportsIRIs.
Referenced by Dataset.buildDataSource().
{
                 return getBoolean(CONF.supportsIRIs, true);
         }
supportsSPARQL11()
boolean supportsSPARQL11 ()
References ResourceReader.getBoolean(), and CONF.supportsSPARQL11.
Referenced by Dataset.buildDataSource().
{
                 return getBoolean(CONF.supportsSPARQL11, false);
         }
Member Data Documentation
datasetBase
String datasetBase
dataSource
final DataSource dataSource private
Referenced by Dataset.getDataSource().
metadata
final MetadataConfiguration metadata private
Referenced by Dataset.getMetadataConfiguration().
sparqlDataSource
RemoteSPARQLDataSource sparqlDataSource = null private
Referenced by Dataset.buildDataSource().