GeoPubby: LatLonTextWriter Class Reference
LatLonTextWriter Class Reference
Public Member Functions
String convertDecimalToLatLonText (Double D, Boolean lng)
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Member Function Documentation
convertDecimalToLatLonText()
String convertDecimalToLatLonText (Double D, Boolean lng)
Referenced by LatLonTextWriter.write().
{
             String dir;
                 if(D<0) {
                         if(lng) {
                                 dir="W";
                         }else {
                                 dir="S";
                         }
                 }else {
                         if(lng) {
                                 dir="E";
                         }else {
                                 dir="N";
                         }
                 }
                 Double deg=D<0?-D:D;
                 Double min=D%1*60;
                 Double sec=(D*60%1*6000)/100;
                 return deg+"°"+min+"'"+sec+"\""+dir;
         }
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
References GEO.ASWKT, LatLonTextWriter.convertDecimalToLatLonText(), GEO.GEORSSPOINT, GEO.P625, GEO.P_GEOMETRY, GEO.P_LAT, GEO.P_LONG, and ModelWriter.reader.
{
                 ExtendedIterator<Resource> it=super.write(model, response);
                 Double lat = null, lon = null;
                 while (it.hasNext()) {
                         Resource ind = it.next();
                         StmtIterator it2 = ind.listProperties();
                         while (it2.hasNext()) {
                                 Statement curst = it2.next();
                                 if (GEO.ASWKT.getURI().equals(curst.getPredicate().getURI().toString())
                                                 || GEO.P_GEOMETRY.getURI().equals(curst.getPredicate().getURI())
                                                 || GEO.P625.getURI().equals(curst.getPredicate().getURI())) {
                                         try {
                                                 Geometry geom = reader.read(curst.getObject().asLiteral().getString());
                                                 lat = geom.getCentroid().getCoordinate().getY();
                                                 lon = geom.getCentroid().getCoordinate().getX();
                                         } catch (ParseException e) {
                                                 // TODO Auto-generated catch block
                                                 e.printStackTrace();
                                         }
                                 } else if (GEO.P_LAT.getURI().equals(curst.getPredicate().getURI().toString())) {
                                         lat = curst.getObject().asLiteral().getDouble();
                                 } else if (GEO.P_LONG.getURI().equals(curst.getPredicate().getURI().toString())) {
                                         lon = curst.getObject().asLiteral().getDouble();
                                 } else if (GEO.GEORSSPOINT.getURI().equals(curst.getPredicate().getURI().toString())) {
                                         lat = Double.valueOf(curst.getObject().asLiteral().getString().split(" ")[0]);
                                         lon = Double.valueOf(curst.getObject().asLiteral().getString().split(" ")[1]);
                                 }
                         }
                 }
                 try {
                         if (lat == null || lon == null) {
                                 response.getWriter().write("");
                                 response.getWriter().close();
                         } else {
                                 response.getWriter().write(convertDecimalToLatLonText(lat,false)+" "+convertDecimalToLatLonText(lon,true));
                                 response.getWriter().close();
                         }
                 } catch (JSONException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 } catch (IOException e) {
                         // TODO Auto-generated catch block
                         e.printStackTrace();
                 }
                 return null;
         }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GoogleMapsLinkWriter.write(), GeoURIWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), TopoJSONWriter.write(), CSVWriter.write(), GeoJSONWriterr.write(), KMLWriter.write(), GPXWriter.write(), GMLWriter.write(), SVGWriter.write(), OSMWriter.write(), and LatLonTextWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), OSMWriter.write(), GMLWriter.write(), and GPXWriter.write().