GeoPubby: ModelWriter Class Reference
ModelWriter Class Reference
A model class for exporting RDF in several downlift formats.
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Detailed Description
A model class for exporting RDF in several downlift formats.
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
References GEO.GEORSSPOINT, GEO.HASGEOMETRY, GEO.P625, and GEO.P_LAT.
{
                 ExtendedIterator<Resource> it=model.
                                 listResourcesWithProperty(GEO.HASGEOMETRY);
                 usedProperty=GEO.HASGEOMETRY;
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P_LAT);
                         usedProperty=GEO.P_LAT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.HASGEOMETRY);
                         usedProperty=GEO.HASGEOMETRY;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.GEORSSPOINT);
                         usedProperty=GEO.GEORSSPOINT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P625);
                         usedProperty=GEO.P625;
                 }
                 return it;
         }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected
Referenced by GeoModelWriter.handleGeometry(), GoogleMapsLinkWriter.write(), CSVWriter.write(), XYZASCIIWriter.write(), WKBWriterr.write(), TWKBWriterr.write(), GeoURIWriter.write(), EWKTWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), X3DWriter.write(), LDWriter.write(), XLSWriter.write(), XLSXWriter.write(), and GPXWriter.write().
usedProperty
Property usedProperty =null protected
Referenced by KMLWriter.write(), OSMWriter.write(), GMLWriter.write(), MapMLWriter.write(), and GPXWriter.write().