GeoPubby: FilteredDataSource Class Reference
FilteredDataSource Class Reference abstract
A DataSource that wraps another data source in such a way that the resulting data source is only capable of describing a subset of the IRI space.
Public Member Functions
FilteredDataSource (DataSource wrapped)
abstract boolean canDescribe (String absoluteIRI)
Determines whether a given IRI is considered to be described in the wrapped data source or not.
Model describeResource (String iri)
Returns a subgraph of the data source describing one resource.
Map< Property, Integer > getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
Map< Property, Integer > getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Returns a subgraph of the data source.
List< Resource > getIndex ()
A list of IRI resources described in this data source.
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine< SearchRecord > getLabelIndex ()
Static Public Attributes
static final int MAX_INDEX_SIZE = 1000000
Private Attributes
final DataSource wrapped
Detailed Description
A DataSource that wraps another data source in such a way that the resulting data source is only capable of describing a subset of the IRI space.
This is usually done for performance, to prevent the underlying data source from attempting to describe resources that we know it doesn't have anything of value about.
Constructor & Destructor Documentation
FilteredDataSource()
FilteredDataSource (DataSource wrapped)
References FilteredDataSource.canDescribe(), and FilteredDataSource.wrapped.
{
                 this.wrapped = wrapped;
         }
Member Function Documentation
canDescribe()
abstract boolean canDescribe (String absoluteIRI) abstract
Determines whether a given IRI is considered to be described in the wrapped data source or not.
Parameters
absoluteIRI Any syntactically valid IRI
Returns
true if that IRI is described in the data source
Implements DataSource.
Referenced by FilteredDataSource.describeResource(), FilteredDataSource.FilteredDataSource(), FilteredDataSource.getHighIndegreeProperties(), FilteredDataSource.getHighOutdegreeProperties(), FilteredDataSource.getIndex(), and FilteredDataSource.listPropertyValues().
describeResource()
Model describeResource (String absoluteIRI)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
References FilteredDataSource.canDescribe(), DataSource.describeResource(), and ModelUtil.EMPTY_MODEL.
{
                 if (!canDescribe(iri)) return ModelUtil.EMPTY_MODEL;
                 return wrapped.describeResource(iri);
         }
getHighIndegreeProperties()
Map<Property, Integer> getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
If high-indegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-indegree properties with number of arcs for the resource
Implements DataSource.
References FilteredDataSource.canDescribe(), and DataSource.getHighIndegreeProperties().
{
                 if (!canDescribe(resourceIRI)) return null;
                 return wrapped.getHighIndegreeProperties(resourceIRI);
         }
getHighOutdegreeProperties()
Map<Property, Integer> getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
If high-outdegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-outdegree properties with number of arcs for the resource
Implements DataSource.
References FilteredDataSource.canDescribe(), and DataSource.getHighOutdegreeProperties().
{
                 if (!canDescribe(resourceIRI)) return null;
                 return wrapped.getHighOutdegreeProperties(resourceIRI);
         }
getIndex()
List<Resource> getIndex ()
A list of IRI resources described in this data source.
Ordering is implementation-defined. Usually a reasonable limit should be applied to the number of resources returned.
Implements DataSource.
References FilteredDataSource.canDescribe(), and DataSource.getIndex().
{
                 List<Resource> result = new ArrayList<Resource>();
                 for (Resource r: wrapped.getIndex()) {
                         if (canDescribe(r.getURI())) {
                                 result.add(r);
                         }
                 }
                 return result;
         }
getLabelIndex()
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine<SearchRecord> getLabelIndex () inherited
Implemented in RemoteSPARQLDataSource, RewrittenDataSource, MergeDataSource, IndexDataSource, and ModelDataSource.
Referenced by SearchServlet.doGet(), IndexDataSource.getLabelIndex(), and RewrittenDataSource.getLabelIndex().
listPropertyValues()
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Returns a subgraph of the data source.
It lists the values of a particular property of a particular resource. Where values are blank nodes, a complete description of these anonymous resources must be included.
Parameters
resourceIRI The resource to be examined
property The property we're interested in
isInverse Are we interested in outgoing arcs (false) or incoming (true)?
Returns
A subgraph of the data source.
Implements DataSource.
References FilteredDataSource.canDescribe(), ModelUtil.EMPTY_MODEL, and DataSource.listPropertyValues().
{
                 if (!canDescribe(resourceIRI)) return ModelUtil.EMPTY_MODEL;
                 return wrapped.listPropertyValues(resourceIRI, property, isInverse);
         }
Member Data Documentation
MAX_INDEX_SIZE
final int MAX_INDEX_SIZE = 1000000 static inherited
Referenced by ModelDataSource.getIndex(), RemoteSPARQLDataSource.getIndex(), and RemoteSPARQLDataSource.getLabelIndex().
wrapped
final DataSource wrapped private
Referenced by FilteredDataSource.FilteredDataSource().