GeoPubby: ValuesURLServlet Class Reference
ValuesURLServlet Class Reference
A servlet for rendering an HTML page listing resources related to a given resource via a given property.
Public Member Functions
boolean doGet (HypermediaControls controller, Property predicate, boolean isInverse, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException, ServletException
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
void init () throws ServletException
Protected Member Functions
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title)
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes)
void send404 (HttpServletResponse response, String resourceURI) throws IOException
void sendInitialization500 (HttpServletResponse response, String message) throws IOException
String addQueryString (String dataURL, HttpServletRequest request)
Static Private Attributes
static final long serialVersionUID = -2597664961896022667L
Detailed Description
A servlet for rendering an HTML page listing resources related to a given resource via a given property.
URIs and literals are displayed as simple values. Blank nodes are displayed as complete resource descriptions.
Member Function Documentation
addDocumentMetadata()
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title) protected inherited
References MetadataConfiguration.addCustomMetadata(), MetadataConfiguration.addMetadataFromTemplate(), ModelUtil.addNSIfUndefined(), HypermediaControls.getAbsoluteIRI(), and Configuration.getDatasets().
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
{
                 ModelUtil.addNSIfUndefined(model, "foaf", FOAF.getURI());
                 ModelUtil.addNSIfUndefined(model, "rdfs", RDFS.getURI());
                 // Add document metadata
                 Resource topic = model.getResource(controller.getAbsoluteIRI());
                 Resource document = model.getResource(documentURL);
                 document.addProperty(FOAF.primaryTopic, topic);
                 document.addProperty(RDFS.label, title);
                 // Add custom metadata
                 for (Dataset dataset: config.getDatasets()) {
                         MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                         metadata.addCustomMetadata(model, document);
                         metadata.addMetadataFromTemplate(model, controller);
                 }
         }
addPageMetadata()
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes) protected inherited
References MetadataConfiguration.addMetadataFromTemplate(), BaseServlet.doGet(), and Configuration.getDatasets().
Referenced by PageURLServlet.doGet(), and ValuesURLServlet.doGet().
{
                 try {
                         Model metadataModel = ModelFactory.createDefaultModel();
                         for (Dataset dataset: config.getDatasets()) {
                                 MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                                 Resource document = metadata.addMetadataFromTemplate(metadataModel, controller);
                                 // Replaced the commented line by the following one because the
                                 // RDF graph we want to talk about is a specific representation
                                 // of the data identified by the getDataURL() URI.
                                 //                                       Olaf, May 28, 2010
                                 // context.put("metadata", metadata.getResource(resource.getDataURL()));
                                 context.put("metadata", document);
                         }
                         Map<String,String> nsSet = metadataModel.getNsPrefixMap();
                         nsSet.putAll(prefixes.getNsPrefixMap());
                         context.put("prefixes", nsSet.entrySet());
                         context.put("blankNodesMap", new HashMap<Resource,String>());
                 }
                 catch (Exception e) {
                         context.put("metadata", Boolean.FALSE);
                 }
         }
addQueryString()
String addQueryString (String dataURL, HttpServletRequest request) protected inherited
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
{
                 if (request.getParameter("output") == null) {
                         return dataURL;
                 }
                 return dataURL + "?output=" + request.getParameter("output");
         }
doGet() [1/3]
boolean doGet (HypermediaControls controller, Property predicate, boolean isInverse, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException
References BaseServlet.addPageMetadata(), BaseServlet.config, Configuration.getDataSource(), ResourceDescription.getModel(), Configuration.getProjectLink(), Configuration.getProjectName(), ResourceDescription.getProperty(), ResourceDescription.getTitle(), ResourceDescription.getURI(), Configuration.getWebApplicationBaseURI(), DataSource.listPropertyValues(), and Configuration.showLabels().
{
                 ResourceDescription resource = controller.getResourceDescription();
                 if (resource == null) return false;
                 Model descriptions = config.getDataSource().listPropertyValues(
                                 controller.getAbsoluteIRI(), predicate, isInverse);
                 if (descriptions.isEmpty()) return false;
                 ResourceProperty property = new ResourceDescription(
                                 controller, descriptions, config).getProperty(predicate, isInverse);
                 if (property == null) return false;     // Can happen if prefix is declared in URI space of a data source rather than in web space
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("project_name", config.getProjectName());
                 context.put("project_link", config.getProjectLink());
                 context.put("uri", resource.getURI());
                 context.put("server_base", config.getWebApplicationBaseURI());
                 context.put("title", resource.getTitle());
                 context.put("head_title", resource.getTitle() + " \u00BB " + property.getCompleteLabel());
                 context.put("property", property);
                 context.put("back_uri", controller.getBrowsableURL());
                 context.put("back_label", resource.getTitle());
                 context.put("rdf_link", isInverse ? controller.getInverseValuesDataURL(predicate) : controller.getValuesDataURL(predicate));
                 context.put("showLabels", config.showLabels());
                 addPageMetadata(context, controller, resource.getModel());
                 template.renderXHTML("valuespage.vm");
                 return true;
         }
doGet() [2/3]
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException, ServletException inherited
References BaseServlet.config, ValuesBaseServlet.doGet(), Configuration.getControls(), Configuration.getPrefixes(), IRIEncoder.toIRI(), and PubbyIRIEscaper.unescapeSpecialCharacters().
{
                 boolean isInverse;
                 Property property;
                 Matcher matcher = prefixedNamePattern.matcher(relativeURI);
                 if (matcher.matches()) {
                         String prefix = matcher.group(2);
                         if (config.getPrefixes().getNsPrefixURI(prefix) == null) {
                                 return false;
                         }
                         String localName = matcher.group(3);
                         relativeURI = matcher.group(4); // Keep just last part
                         property = ResourceFactory.createProperty(
                                         config.getPrefixes().getNsPrefixURI(prefix), localName);
                 } else {
                         matcher = fullIRIPattern.matcher(relativeURI);
                         if (!matcher.matches()) {
                                 return false;
                         }
                         String propertyIRI = IRIEncoder.toIRI(
                                         PubbyIRIEscaper.unescapeSpecialCharacters(matcher.group(2)));
                         relativeURI = matcher.group(3); // Keep just last part
                         property = ResourceFactory.createProperty(propertyIRI);
                 }
                 isInverse = "-".equals(matcher.group(1));
                 HypermediaControls controller = config.getControls(relativeURI, false);
                 if (controller == null) {
                         return false;
                 }
                 return doGet(controller, property, isInverse, request, response, config);
         }
doGet() [3/3]
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException inherited
References BaseServlet.doGet(), ServletContextInitializer.ERROR_MESSAGE, ServletContextInitializer.initConfiguration(), BaseServlet.send404(), BaseServlet.sendInitialization500(), and ServletContextInitializer.SERVER_CONFIGURATION.
{
                 if (initError != null) {
                         if(config==null) {
                                 System.out.println("Calling initConfiguration from BaseServlet!");
                                 Boolean res=ServletContextInitializer.initConfiguration(getServletContext());
                                 if(res)
                                         initError=null;
                                 else {
                                         initError=getServletContext().getAttribute(ServletContextInitializer.ERROR_MESSAGE).toString();
                                 }
                                 System.out.println("Successful result? "+res.toString());
                         }
                         config = (Configuration) getServletContext().getAttribute(
                                         ServletContextInitializer.SERVER_CONFIGURATION);
                 }
                 if(initError!=null) {
                         sendInitialization500(response, initError);
                         return;
                 }
                 String relativeURI = request.getRequestURI().substring(
                                 request.getContextPath().length() + request.getServletPath().length());
                 // Some servlet containers keep the leading slash, some don't
                 if (!"".equals(relativeURI) && "/".equals(relativeURI.substring(0, 1))) {
                         relativeURI = relativeURI.substring(1);
                 }
                 if (!doGet(relativeURI, request, response, config)) {
                         send404(response, null);
                 }
         }
init()
void init () throws ServletException inherited
References ServletContextInitializer.ERROR_MESSAGE, and ServletContextInitializer.SERVER_CONFIGURATION.
{
                 config = (Configuration) getServletContext().getAttribute(
                                 ServletContextInitializer.SERVER_CONFIGURATION);
                         if(config==null){
                                         initError = (String) getServletContext().getAttribute(
                                         ServletContextInitializer.ERROR_MESSAGE);
                         }
         }
send404()
void send404 (HttpServletResponse response, String resourceURI) throws IOException protected inherited
References Configuration.getProjectLink(), Configuration.getProjectName(), and Configuration.getWebApplicationBaseURI().
Referenced by BaseServlet.doGet().
{
                 response.setStatus(404);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("project_name", config.getProjectName());
                 context.put("project_link", config.getProjectLink());
                 context.put("server_base", config.getWebApplicationBaseURI());
                 context.put("title", "404 Not Found");
                 if (resourceURI != null) {
                         context.put("uri", resourceURI);
                 }
                 template.renderXHTML("404.vm");
         }
sendInitialization500()
void sendInitialization500 (HttpServletResponse response, String message) throws IOException protected inherited
Referenced by BaseServlet.doGet().
{
                 response.setStatus(500);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("message", message);
                 context.put("title", "Configuration error");
                 template.renderXHTML("500init.vm");
         }
Member Data Documentation
serialVersionUID
final long serialVersionUID = -2597664961896022667L static private