GeoPubby: PageURLServlet Class Reference
PageURLServlet Class Reference
A servlet for serving the HTML page describing a resource.
Public Member Functions
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, final Configuration config) throws ServletException, IOException
void init () throws ServletException
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
Protected Member Functions
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title)
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes)
void send404 (HttpServletResponse response, String resourceURI) throws IOException
void sendInitialization500 (HttpServletResponse response, String message) throws IOException
String addQueryString (String dataURL, HttpServletRequest request)
Static Private Attributes
static final long serialVersionUID = 3363621132360159793L
Detailed Description
A servlet for serving the HTML page describing a resource.
Invokes a Velocity template.
Member Function Documentation
addDocumentMetadata()
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title) protected inherited
References MetadataConfiguration.addCustomMetadata(), MetadataConfiguration.addMetadataFromTemplate(), ModelUtil.addNSIfUndefined(), HypermediaControls.getAbsoluteIRI(), and Configuration.getDatasets().
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
{
                 ModelUtil.addNSIfUndefined(model, "foaf", FOAF.getURI());
                 ModelUtil.addNSIfUndefined(model, "rdfs", RDFS.getURI());
                 // Add document metadata
                 Resource topic = model.getResource(controller.getAbsoluteIRI());
                 Resource document = model.getResource(documentURL);
                 document.addProperty(FOAF.primaryTopic, topic);
                 document.addProperty(RDFS.label, title);
                 // Add custom metadata
                 for (Dataset dataset: config.getDatasets()) {
                         MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                         metadata.addCustomMetadata(model, document);
                         metadata.addMetadataFromTemplate(model, controller);
                 }
         }
addPageMetadata()
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes) protected inherited
References MetadataConfiguration.addMetadataFromTemplate(), and Configuration.getDatasets().
Referenced by PageURLServlet.doGet(), and ValuesURLServlet.doGet().
{
                 try {
                         Model metadataModel = ModelFactory.createDefaultModel();
                         for (Dataset dataset: config.getDatasets()) {
                                 MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                                 Resource document = metadata.addMetadataFromTemplate(metadataModel, controller);
                                 // Replaced the commented line by the following one because the
                                 // RDF graph we want to talk about is a specific representation
                                 // of the data identified by the getDataURL() URI.
                                 //                                       Olaf, May 28, 2010
                                 // context.put("metadata", metadata.getResource(resource.getDataURL()));
                                 context.put("metadata", document);
                         }
                         Map<String,String> nsSet = metadataModel.getNsPrefixMap();
                         nsSet.putAll(prefixes.getNsPrefixMap());
                         context.put("prefixes", nsSet.entrySet());
                         context.put("blankNodesMap", new HashMap<Resource,String>());
                 }
                 catch (Exception e) {
                         context.put("metadata", Boolean.FALSE);
                 }
         }
addQueryString()
String addQueryString (String dataURL, HttpServletRequest request) protected inherited
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
{
                 if (request.getParameter("output") == null) {
                         return dataURL;
                 }
                 return dataURL + "?output=" + request.getParameter("output");
         }
doGet() [1/2]
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, final Configuration config) throws ServletException, IOException
References BaseServlet.addPageMetadata(), BaseServlet.config, ResourceDescription.getComment(), Configuration.getControls(), HypermediaControls.getDataURL(), ResourceDescription.getGeoms(), ResourceDescription.getImageURL(), ResourceDescription.getModel(), Configuration.getProjectLink(), Configuration.getProjectName(), ResourceDescription.getProperties(), HypermediaControls.getResourceDescription(), ResourceDescription.getTitle(), ResourceDescription.getURI(), Configuration.getWebApplicationBaseURI(), and Configuration.showLabels().
{
                 super.doGet(relativeURI, request, response, config);
                 final HypermediaControls controller = config.getControls(relativeURI, false);
                 if (controller == null) return false;
                 ResourceDescription description = controller.getResourceDescription();
                 if (description == null) return false;
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("project_name", config.getProjectName());
                 context.put("project_link", config.getProjectLink());
                 context.put("uri", description.getURI());
                 context.put("server_base", config.getWebApplicationBaseURI());
                 context.put("rdf_link", controller.getDataURL());
                 context.put("title", description.getTitle());
                 context.put("comment", description.getComment());
                 context.put("image", description.getImageURL());
                 context.put("properties", description.getProperties());
                 context.put("showLabels", config.showLabels());
                 context.put("geoms",description.getGeoms());
                 addPageMetadata(context, controller, description.getModel());
                 template.renderXHTML("page.vm");
                 return true;
         }
doGet() [2/2]
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException inherited
References BaseServlet.doGet(), ServletContextInitializer.initConfiguration(), BaseServlet.send404(), BaseServlet.sendInitialization500(), and ServletContextInitializer.SERVER_CONFIGURATION.
{
                 if (initError != null) {
                         sendInitialization500(response, initError);
                         if(config==null) {
                                 ServletContextInitializer.initConfiguration(getServletContext());
                         }
                         config = (Configuration) getServletContext().getAttribute(
                                         ServletContextInitializer.SERVER_CONFIGURATION);
                         return;
                 }
                 String relativeURI = request.getRequestURI().substring(
                                 request.getContextPath().length() + request.getServletPath().length());
                 // Some servlet containers keep the leading slash, some don't
                 if (!"".equals(relativeURI) && "/".equals(relativeURI.substring(0, 1))) {
                         relativeURI = relativeURI.substring(1);
                 }
                 if (!doGet(relativeURI, request, response, config)) {
                         send404(response, null);
                 }
         }
init()
void init () throws ServletException inherited
References ServletContextInitializer.ERROR_MESSAGE, and ServletContextInitializer.SERVER_CONFIGURATION.
{
                 config = (Configuration) getServletContext().getAttribute(
                                 ServletContextInitializer.SERVER_CONFIGURATION);
                         if(config==null){
                             initError = (String) getServletContext().getAttribute(
                                         ServletContextInitializer.ERROR_MESSAGE);
                         }
         }
send404()
void send404 (HttpServletResponse response, String resourceURI) throws IOException protected inherited
References Configuration.getProjectLink(), Configuration.getProjectName(), and Configuration.getWebApplicationBaseURI().
Referenced by BaseServlet.doGet().
{
                 response.setStatus(404);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("project_name", config.getProjectName());
                 context.put("project_link", config.getProjectLink());
                 context.put("server_base", config.getWebApplicationBaseURI());
                 context.put("title", "404 Not Found");
                 if (resourceURI != null) {
                         context.put("uri", resourceURI);
                 }
                 template.renderXHTML("404.vm");
         }
sendInitialization500()
void sendInitialization500 (HttpServletResponse response, String message) throws IOException protected inherited
Referenced by BaseServlet.doGet().
{
                 response.setStatus(500);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("message", message);
                 context.put("title", "Configuration error");
                 template.renderXHTML("500init.vm");
         }
Member Data Documentation
serialVersionUID
final long serialVersionUID = 3363621132360159793L static private