GeoPubby: RequestParamHandler Class Reference
RequestParamHandler Class Reference
Analyzes an HttpServletRequest to check for the presence of an ?output=n3 or =ttl or =rdfxml request parameter in the URI.
Classes
class WrappedRequest
Public Member Functions
RequestParamHandler (HttpServletRequest request)
boolean isMatchingRequest ()
HttpServletRequest getModifiedRequest ()
Static Public Member Functions
static String removeOutputRequestParam (String uri)
Removes the "output=foobar" part of a URI if present.
Static Package Functions
[static initializer]
Private Member Functions
String identifyRequestedType (String parameterValue)
Private Attributes
final HttpServletRequest request
final String requestedType
Static Private Attributes
static final String ATTRIBUTE_NAME_IS_HANDLED
static final Map< String, String > mimeTypes = new HashMap<String,String>()
Detailed Description
Analyzes an HttpServletRequest to check for the presence of an ?output=n3 or =ttl or =rdfxml request parameter in the URI.
If present, returns a modified HttpServletRequest that has the appropriate MIME type in the Accept: header. This request can then be fed into the rest of our content negotiation based tooling.
Constructor & Destructor Documentation
RequestParamHandler()
RequestParamHandler (HttpServletRequest request)
References RequestParamHandler.identifyRequestedType(), and RequestParamHandler.request.
{
                 this.request = request;
                 requestedType = identifyRequestedType(request.getParameter("output"));
         }
Member Function Documentation
[static initializer]()
[static initializer] () static package
getModifiedRequest()
HttpServletRequest getModifiedRequest ()
Referenced by ModelResponse.ModelResponse().
{
                 return new WrappedRequest();
         }
identifyRequestedType()
String identifyRequestedType (String parameterValue) private
Referenced by RequestParamHandler.RequestParamHandler().
{
                 if (mimeTypes.containsKey(parameterValue)) {
                         return parameterValue;
                 }
                 return null;
         }
isMatchingRequest()
boolean isMatchingRequest ()
Referenced by ModelResponse.ModelResponse().
{
                 if ("true".equals(request.getAttribute(ATTRIBUTE_NAME_IS_HANDLED))) {
                         return false;
                 }
                 return requestedType != null;
         }
removeOutputRequestParam()
static String removeOutputRequestParam (String uri) static
Removes the "output=foobar" part of a URI if present.
{
                 // Remove the param: output=[a-z0-9]*
                 // There are two cases. The param can occur at the end of the URI,
                 // this is matched by the first part: [?&]param$
                 // Or it can occur elsewhere, then it's matched by param& with a
                 // lookbehind that requires [?&] to occur before the pattern.
                 return uri.replaceFirst("([?&]output=[a-z0-9]*$)|((?<=[?&])output=[a-z0-9]*&)", "");
         }
Member Data Documentation
ATTRIBUTE_NAME_IS_HANDLED
final String ATTRIBUTE_NAME_IS_HANDLED static private
Initial value:
=
                "OutputRequestParamHandler.isHandled"
mimeTypes
final Map<String,String> mimeTypes = new HashMap<String,String>() static private
request
final HttpServletRequest request private
Referenced by RequestParamHandler.RequestParamHandler().
requestedType
final String requestedType private