GeoPubby: ServletContextInitializer Class Reference
ServletContextInitializer Class Reference
Public Member Functions
void contextInitialized (ServletContextEvent sce)
void contextDestroyed (ServletContextEvent sce)
Static Public Member Functions
static void initConfiguration (ServletContext context)
Static Public Attributes
static final String SERVER_CONFIGURATION
static final String ERROR_MESSAGE
Static Private Member Functions
static void log (Exception ex, ServletContext context)
Member Function Documentation
contextDestroyed()
void contextDestroyed (ServletContextEvent sce)
{
                 // Do nothing special.
         }
contextInitialized()
void contextInitialized (ServletContextEvent sce)
References ServletContextInitializer.initConfiguration().
{
                 ServletContext context = sce.getServletContext();
                 ServletContextInitializer.initConfiguration(context);
                 /*
                 try {
                         String configFileName = context.getInitParameter("config-file");
                         if (configFileName == null) {
                                 throw new ConfigurationException("Missing context parameter \"config-file\" in /WEB-INF/web.xml");
                         }
                         File configFile = new File(configFileName);
                         if (!configFile.isAbsolute()) {
                                 configFile = new File(context.getRealPath("/") + "/WEB-INF/" + configFileName);
                         }
                         String url = configFile.getAbsoluteFile().toURI().toString();
                         try {
                                 Model m = FileManager.get().loadModel(url);
                                 Configuration conf = Configuration.create(m);
                                 context.setAttribute(SERVER_CONFIGURATION, conf);
                         } catch (JenaException ex) {
                             if(ex.getCause()!=null){
                                                                 throw new ConfigurationException(
                                                 "Error parsing configuration file <" + url + ">: " +
                                                 ex.getMessage()+"\nCause: "+ex.getCause().getMessage());
                             }else{
                                 throw new ConfigurationException(
                                                 "Error parsing configuration file <" + url + ">: " +
                                                 ex.getMessage());
                             }
                         }
                 } catch (ConfigurationException ex) {
                         log(ex, context);
                 }*/
         }
initConfiguration()
static void initConfiguration (ServletContext context) static
References Configuration.create(), and ServletContextInitializer.log().
Referenced by ServletContextInitializer.contextInitialized().
{
             try {
                         String configFileName = context.getInitParameter("config-file");
                         if (configFileName == null) {
                                 throw new ConfigurationException("Missing context parameter \"config-file\" in /WEB-INF/web.xml");
                         }
                         File configFile = new File(configFileName);
                         if (!configFile.isAbsolute()) {
                                 configFile = new File(context.getRealPath("/") + "/WEB-INF/" + configFileName);
                         }
                         String url = configFile.getAbsoluteFile().toURI().toString();
                         try {
                                 Model m = FileManager.get().loadModel(url);
                                 Configuration conf = Configuration.create(m);
                                 context.setAttribute(SERVER_CONFIGURATION, conf);
                         } catch (JenaException ex) {
                             if(ex.getCause()!=null){
                                                                 throw new ConfigurationException(
                                                 "Error parsing configuration file <" + url + ">: " +
                                                 ex.getMessage()+"\nCause: "+ex.getCause().getMessage());
                             }else{
                                 throw new ConfigurationException(
                                                 "Error parsing configuration file <" + url + ">: " +
                                                 ex.getMessage());
                             }
                         }
                 } catch (ConfigurationException ex) {
                         log(ex, context);
                 }
         }
log()
static void log (Exception ex, ServletContext context) static private
Referenced by ServletContextInitializer.initConfiguration().
{
                 context.log("######## PUBBY CONFIGURATION ERROR ######## ");
                 context.log(ex.getMessage());
                 context.log("########################################### ");
                 context.setAttribute(ERROR_MESSAGE, ex.getMessage());
         }
Member Data Documentation
ERROR_MESSAGE
final String ERROR_MESSAGE static
Initial value:
=
                        ServletContextInitializer.class.getName() + ".errorMessage"
Referenced by BaseServlet.init().
SERVER_CONFIGURATION
final String SERVER_CONFIGURATION static
Initial value:
=
                        ServletContextInitializer.class.getName() + ".serverConfiguration"
Referenced by BaseServlet.init().