GeoPubby: ModelUtil Class Reference
ModelUtil Class Reference
Static Public Member Functions
static void mergeModels (Model target, Model source)
Adds the source model to the target model, modifying the target in place.
static void mergePrefixes (Model target, PrefixMapping source)
Adds prefixes from a PrefixMapping to the target model, modifying the target in place.
static void addNSIfUndefined (PrefixMapping m, String prefix, String uri)
Static Public Attributes
static final Model EMPTY_MODEL = ModelFactory.createDefaultModel()
Private Member Functions
ModelUtil ()
Singleton; only public static methods.
Constructor & Destructor Documentation
ModelUtil()
ModelUtil () private
Singleton; only public static methods.
 {}
Member Function Documentation
addNSIfUndefined()
static void addNSIfUndefined (PrefixMapping m, String prefix, String uri) static
Referenced by BaseServlet.addDocumentMetadata(), RewrittenDataSource.addSameAsStatement(), and Configuration.Configuration().
{
                 if (m.getNsURIPrefix(uri) != null) return;
                 if (m.getNsPrefixURI(prefix) != null) return;
                 m.setNsPrefix(prefix, uri);
         }
mergeModels()
static void mergeModels (Model target, Model source) static
Adds the source model to the target model, modifying the target in place.
Overrides any prefixes in the target with those from the source.
References ModelUtil.mergePrefixes().
Referenced by MergeDataSource.describeResource(), and MergeDataSource.listPropertyValues().
{
                 target.add(source);
                 mergePrefixes(target, source);
         }
mergePrefixes()
static void mergePrefixes (Model target, PrefixMapping source) static
Adds prefixes from a PrefixMapping to the target model, modifying the target in place.
Overrides any prefixes in the target with those from the prefix mapping.
Referenced by MergeDataSource.describeResource(), MergeDataSource.listPropertyValues(), and ModelUtil.mergeModels().
{
                 for (String prefix: source.getNsPrefixMap().keySet()) {
                         target.setNsPrefix(prefix, source.getNsPrefixURI(prefix));
                 }
         }
Member Data Documentation
EMPTY_MODEL
final Model EMPTY_MODEL = ModelFactory.createDefaultModel() static
Referenced by FilteredDataSource.describeResource(), ModelDataSource.describeResource(), RewrittenDataSource.describeResource(), FilteredDataSource.listPropertyValues(), and RewrittenDataSource.listPropertyValues().