GeoPubby: CoverageModelWriter Class Reference
CoverageModelWriter Class Reference
Public Member Functions
Tuple< Boolean, String > handleCoverage (Statement curst, Resource ind, Model model)
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Package Attributes
GridCoverage cov
Member Function Documentation
handleCoverage()
Tuple<Boolean,String> handleCoverage (Statement curst, Resource ind, Model model)
References COV.ASCOVERAGEJSON, COV.ASGMLCOV, COV.ASHEXRASTWKB, and COV.ASRASTWKB.
{
                 boolean handled=false;
                 String type="coverage";
                 if(COV.ASCOVERAGEJSON.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }else if(COV.ASGMLCOV.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }else if(COV.ASRASTWKB.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }else if(COV.ASHEXRASTWKB.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }
                 return new Tuple<Boolean,String>(handled,type);
         }
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException inherited
References GEO.GEORSSPOINT, GEO.HASGEOMETRY, GEO.P625, and GEO.P_LAT.
{
                 ExtendedIterator<Resource> it=model.
                                 listResourcesWithProperty(GEO.HASGEOMETRY);
                 usedProperty=GEO.HASGEOMETRY;
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P_LAT);
                         usedProperty=GEO.P_LAT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.HASGEOMETRY);
                         usedProperty=GEO.HASGEOMETRY;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.GEORSSPOINT);
                         usedProperty=GEO.GEORSSPOINT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P625);
                         usedProperty=GEO.P625;
                 }
                 return it;
         }
Member Data Documentation
cov
GridCoverage cov package
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GeoModelWriter.handleGeometry(), GoogleMapsLinkWriter.write(), CSVWriter.write(), XYZASCIIWriter.write(), WKBWriterr.write(), TWKBWriterr.write(), GeoURIWriter.write(), EWKTWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), X3DWriter.write(), LDWriter.write(), XLSXWriter.write(), XLSWriter.write(), and GPXWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), OSMWriter.write(), GMLWriter.write(), MapMLWriter.write(), and GPXWriter.write().