GeoPubby: ResourceDescription.ResourceProperty Class Reference
ResourceDescription.ResourceProperty Class Reference
Public Member Functions
ResourceProperty (Property predicate, boolean isInverse, List< Value > simpleValues, List< ResourceDescription > complexVaues, int omittedValues, VocabularyStore vocabularyStore)
boolean isInverse ()
String getURI ()
String getBrowsableURL ()
boolean hasPrefix ()
String getPrefix ()
String getLocalName ()
String getLabel ()
String getLabel (boolean preferPlural)
String getInverseLabel ()
String getInverseLabel (boolean preferPlural)
String getCompleteLabel ()
Note: This bypasses conf:showLabels, always assuming true
String getDescription ()
List< Value > getSimpleValues ()
List< ResourceDescription > getComplexValues ()
boolean hasOnlySimpleValues ()
int getValueCount ()
boolean isMultiValued ()
String getValuesPageURL ()
int compareTo (ResourceProperty other)
Private Attributes
final Property predicate
final URIPrefixer predicatePrefixer
final boolean isInverse
final List< Value > simpleValues
final List< ResourceDescription > complexValues
final int omittedValues
final VocabularyStore vocabularyStore
Constructor & Destructor Documentation
ResourceProperty()
ResourceProperty (Property predicate, boolean isInverse, List< Value > simpleValues, List< ResourceDescription > complexVaues, int omittedValues, VocabularyStore vocabularyStore)
References ResourceDescription.getPrefixes(), ResourceDescription.ResourceProperty.isInverse(), ResourceDescription.ResourceProperty.omittedValues, ResourceDescription.ResourceProperty.predicate, ResourceDescription.ResourceProperty.simpleValues, and ResourceDescription.ResourceProperty.vocabularyStore.
Referenced by ResourceDescription.ResourceProperty.compareTo(), and ResourceDescription.PropertyBuilder.toProperty().
{
                         this.predicate = predicate;
                         this.predicatePrefixer = new URIPrefixer(predicate, getPrefixes());
                         this.isInverse = isInverse;
                         this.simpleValues = simpleValues;
                         this.complexValues = complexVaues;
                         this.omittedValues = omittedValues;
                         this.vocabularyStore = vocabularyStore;
                 }
Member Function Documentation
compareTo()
int compareTo (ResourceProperty other)
References ResourceDescription.ResourceProperty.getLocalName(), Configuration.getVocabularyStore(), VocabularyStore.getWeight(), ResourceDescription.ResourceProperty.isInverse, ResourceDescription.ResourceProperty.predicate, and ResourceDescription.ResourceProperty.ResourceProperty().
{
                         if (!(other instanceof ResourceProperty)) {
                                 return 0;
                         }
                         ResourceProperty otherProperty = (ResourceProperty) other;
                         int myWeight = config.getVocabularyStore().getWeight(
                                         predicate, isInverse);
                         int otherWeight = config.getVocabularyStore().getWeight(
                                         otherProperty.predicate, other.isInverse);
                         if (myWeight < otherWeight) return -1;
                         if (myWeight > otherWeight) return 1;
                         String propertyLocalName = getLocalName();
                         String otherLocalName = otherProperty.getLocalName();
                         if (propertyLocalName.compareTo(otherLocalName) != 0) {
                                 return propertyLocalName.compareTo(otherLocalName);
                         }
                         if (this.isInverse() != otherProperty.isInverse()) {
                                 return (this.isInverse()) ? 1 : -1;
                         }
                         return 0;
                 }
getBrowsableURL()
String getBrowsableURL ()
References ResourceDescription.config, HypermediaControls.createFromIRI(), and HypermediaControls.getBrowsableURL().
{
                         HypermediaControls controls = HypermediaControls.createFromIRI(
                                         predicate.getURI(), config);
                         if (controls == null) return predicate.getURI();
                         return controls.getBrowsableURL();
                 }
getCompleteLabel()
String getCompleteLabel ()
Note: This bypasses conf:showLabels, always assuming true
Returns
"Is Widget Of", "Widgets", "ex:widget", whatever is most appropriate
References ResourceDescription.ResourceProperty.getInverseLabel(), ResourceDescription.ResourceProperty.getLabel(), ResourceDescription.ResourceProperty.getLocalName(), ResourceDescription.ResourceProperty.getPrefix(), and ResourceDescription.ResourceProperty.hasPrefix().
{
                         if (isInverse && getInverseLabel() != null) {
                                 return getInverseLabel();
                         }
                         String result;
                         if (getLabel() != null) {
                                 result = getLabel();
                         } else if (hasPrefix()) {
                                 result = getPrefix() + ":" + getLocalName();
                         } else {
                                 result = "?:" + getLocalName();
                         }
                         return isInverse ? "Is " + result + " of" : result;
                 }
getComplexValues()
List<ResourceDescription> getComplexValues ()
References ResourceDescription.ResourceProperty.complexValues.
{
                         return complexValues;
                 }
getDescription()
String getDescription ()
References VocabularyStore.getDescription().
{
                         return vocabularyStore.getDescription(predicate.getURI()).getLexicalForm();
                 }
getInverseLabel() [1/2]
String getInverseLabel ()
References ResourceDescription.ResourceProperty.isMultiValued().
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
{
                         return getInverseLabel(isMultiValued());
                 }
getInverseLabel() [2/2]
String getInverseLabel (boolean preferPlural)
References VocabularyStore.getInverseLabel(), and ResourceDescription.toTitleCase().
{
                         Literal label = vocabularyStore.getInverseLabel(predicate.getURI(), preferPlural);
                         if (label == null) return null;
                         return toTitleCase(label.getLexicalForm(), label.getLanguage());
                 }
getLabel() [1/2]
String getLabel ()
References ResourceDescription.ResourceProperty.isMultiValued().
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel(), and ResourceDescription.Value.getLabel().
{
                         return getLabel(isMultiValued());
                 }
getLabel() [2/2]
String getLabel (boolean preferPlural)
References VocabularyStore.getLabel(), and ResourceDescription.toTitleCase().
{
                         System.out.println("Getting label (plural)? "+predicate.getURI());
                         Literal label = vocabularyStore.getLabel(predicate.getURI(), preferPlural);
                         System.out.println("Found label: "+label);
                         if (label == null) {
                                 StmtIterator iter=predicate.listProperties(RDFS.label);
                                 if(iter.hasNext()) {
                                         String labelprop=iter.next().getObject().asLiteral().getString();
                                         System.out.println("Got Label for Prop: "+labelprop);
                                         return labelprop;
                                 }else {
                                         return null;
                                 }
                         }
                         return toTitleCase(label.getLexicalForm(), label.getLanguage());
                 }
getLocalName()
String getLocalName ()
References URIPrefixer.getLocalName().
Referenced by ResourceDescription.ResourceProperty.compareTo(), and ResourceDescription.ResourceProperty.getCompleteLabel().
{
                         return predicatePrefixer.getLocalName();
                 }
getPrefix()
String getPrefix ()
References URIPrefixer.getPrefix().
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
{
                         return predicatePrefixer.getPrefix();
                 }
getSimpleValues()
List<Value> getSimpleValues ()
References ResourceDescription.ResourceProperty.simpleValues.
{
                         return simpleValues;
                 }
getURI()
String getURI ()
{
                         return predicate.getURI();
                 }
getValueCount()
int getValueCount ()
{
                         return omittedValues + complexValues.size() + simpleValues.size();
                 }
getValuesPageURL()
String getValuesPageURL ()
References HypermediaControls.getInverseValuesPageURL(), and HypermediaControls.getValuesPageURL().
{
                         if (hypermediaResource == null) {
                                 return null;
                         }
                         return isInverse
                                         ? hypermediaResource.getInverseValuesPageURL(predicate)
                                         : hypermediaResource.getValuesPageURL(predicate);
                 }
hasOnlySimpleValues()
boolean hasOnlySimpleValues ()
{
                         return omittedValues == 0 && complexValues.isEmpty();
                 }
hasPrefix()
boolean hasPrefix ()
References URIPrefixer.hasPrefix().
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
{
                         return predicatePrefixer.hasPrefix();
                 }
isInverse()
boolean isInverse ()
Referenced by ResourceDescription.ResourceProperty.compareTo(), ResourceDescription.PropertyBuilder.PropertyBuilder(), and ResourceDescription.ResourceProperty.ResourceProperty().
{
                         return isInverse;
                 }
isMultiValued()
boolean isMultiValued ()
Referenced by ResourceDescription.ResourceProperty.getInverseLabel(), and ResourceDescription.ResourceProperty.getLabel().
{
                         return simpleValues.size() + omittedValues + complexValues.size() > 1;
                 }
Member Data Documentation
complexValues
final List<ResourceDescription> complexValues private
Referenced by ResourceDescription.ResourceProperty.getComplexValues().
isInverse
final boolean isInverse private
Referenced by ResourceDescription.ResourceProperty.compareTo().
omittedValues
final int omittedValues private
Referenced by ResourceDescription.ResourceProperty.ResourceProperty().
predicate
final Property predicate private
Referenced by ResourceDescription.ResourceProperty.compareTo(), ResourceDescription.PropertyBuilder.PropertyBuilder(), ResourceDescription.ResourceProperty.ResourceProperty(), and ResourceDescription.Value.Value().
predicatePrefixer
final URIPrefixer predicatePrefixer private
simpleValues
final List<Value> simpleValues private
Referenced by ResourceDescription.ResourceProperty.getSimpleValues(), and ResourceDescription.ResourceProperty.ResourceProperty().
vocabularyStore
final VocabularyStore vocabularyStore private
Referenced by ResourceDescription.PropertyBuilder.PropertyBuilder(), ResourceDescription.ResourceProperty.ResourceProperty(), and ResourceDescription.Value.Value().