GeoPubby: MediaRangeSpec Class Reference
MediaRangeSpec Class Reference
Public Member Functions
String getType ()
String getSubtype ()
String getMediaType ()
List< String > getParameterNames ()
String getParameter (String parameterName)
boolean isWildcardType ()
boolean isWildcardSubtype ()
double getQuality ()
int getPrecedence (MediaRangeSpec range)
MediaRangeSpec getBestMatch (List< MediaRangeSpec > mediaRanges)
String toString ()
Static Public Member Functions
static MediaRangeSpec parseType (String mediaType)
Parses a media type from a string such as text/html;charset=utf-8;q=0.9.
static MediaRangeSpec parseRange (String mediaRange)
Parses a media range from a string such as text/*;charset=utf-8;q=0.9.
static List< MediaRangeSpec > parseAccept (String s)
Parses an HTTP Accept header into a List of MediaRangeSpecs.
Static Package Functions
[static initializer]
Private Member Functions
MediaRangeSpec (String type, String subtype, List< String > parameterNames, List< String > parameterValues, double quality)
String buildMediaType ()
Static Private Member Functions
static String unescape (String s)
static String escape (String s)
Private Attributes
final String type
final String subtype
final List< String > parameterNames
final List< String > parameterValues
final String mediaType
final double quality
Static Private Attributes
static final Pattern tokenPattern
static final Pattern parameterPattern
static final Pattern mediaRangePattern
static final Pattern qValuePattern
Constructor & Destructor Documentation
MediaRangeSpec()
MediaRangeSpec (String type, String subtype, List< String > parameterNames, List< String > parameterValues, double quality) private
References MediaRangeSpec.buildMediaType(), MediaRangeSpec.parameterValues, MediaRangeSpec.quality, MediaRangeSpec.subtype, and MediaRangeSpec.type.
Referenced by MediaRangeSpec.getBestMatch(), and MediaRangeSpec.parseRange().
{
                 this.type = type;
                 this.subtype = subtype;
                 this.parameterNames = Collections.unmodifiableList(parameterNames);
                 this.parameterValues = parameterValues;
                 this.mediaType = buildMediaType();
                 this.quality = quality;
         }
Member Function Documentation
[static initializer]()
[static initializer] () static package
buildMediaType()
String buildMediaType () private
References MediaRangeSpec.escape().
Referenced by MediaRangeSpec.MediaRangeSpec().
{
                 StringBuffer result = new StringBuffer();
                 result.append(type);
                 result.append("/");
                 result.append(subtype);
                 for (int i = 0; i < parameterNames.size(); i++) {
                         result.append(";");
                         result.append(parameterNames.get(i));
                         result.append("=");
                         String value = (String) parameterValues.get(i);
                         if (tokenPattern.matcher(value).matches()) {
                                 result.append(value);
                         } else {
                                 result.append("\"");
                                 result.append(escape(value));
                                 result.append("\"");
                         }
                 }
                 return result.toString();
         }
escape()
static String escape (String s) static private
Referenced by MediaRangeSpec.buildMediaType().
{
                 return s.replaceAll("[\\\\\"]", "\\\\$0");
         }
getBestMatch()
MediaRangeSpec getBestMatch (List< MediaRangeSpec > mediaRanges)
References MediaRangeSpec.getPrecedence(), and MediaRangeSpec.MediaRangeSpec().
Referenced by ContentTypeNegotiator.Negotiation.evaluateVariantAlias(), and MediaRangeSpecTest.testGetBestMatchSameQuality().
{
                 MediaRangeSpec result = null;
                 int bestPrecedence = 0;
                 Iterator<MediaRangeSpec> it = mediaRanges.iterator();
                 while (it.hasNext()) {
                         MediaRangeSpec range = (MediaRangeSpec) it.next();
                         if (getPrecedence(range) > bestPrecedence) {
                                 bestPrecedence = getPrecedence(range);
                                 result = range;
                         }
                 }
                 return result;
         }
getMediaType()
String getMediaType ()
References MediaRangeSpec.mediaType.
Referenced by MediaRangeSpecTest.assertMediaRangeInList(), WebURIServlet.doGet(), ModelResponse.doResponseModel(), ContentTypeNegotiatorTest.testAcceptAlias(), PubbyNegotiatorTest.testAcceptEverythingGetsHTML(), PubbyNegotiatorTest.testAcceptHTML(), PubbyNegotiatorTest.testAcceptJSON(), PubbyNegotiatorTest.testAcceptRDFXML(), PubbyNegotiatorTest.testAcceptXHTMLGetsHTML(), PubbyNegotiatorTest.testAcceptXMLGetsRDFXML(), PubbyNegotiatorTest.testBrowsersGetHTML(), MediaRangeSpecTest.testCaseInsensitive(), PubbyNegotiatorTest.testDataURIDefaultsToN3ForFirefox(), PubbyNegotiatorTest.testDataURIDefaultsToN3ForSafari(), ContentTypeNegotiatorTest.testDefaultToHigherQuality(), ContentTypeNegotiatorTest.testEmptyHeader(), ContentTypeNegotiatorTest.testEmptyHeaderPickBestQuality(), PubbyNegotiatorTest.testFirefox3GetsHTML(), MediaRangeSpecTest.testGetBestMatchSameQuality(), MediaRangeSpecTest.testGetMediaType(), PubbyNegotiatorTest.testGetN3(), PubbyNegotiatorTest.testGetNTriples(), PubbyNegotiatorTest.testGetTurtle(), ContentTypeNegotiatorTest.testMatchSimple(), PubbyNegotiatorTest.testNoAcceptGetsHTML(), MediaRangeSpecTest.testParameterValueEscapingRoundTrip(), ContentTypeNegotiatorTest.testPickCorrectMatchSimple(), ContentTypeNegotiatorTest.testPickCorrectMatchWithClientQuality(), ContentTypeNegotiatorTest.testPickCorrectMatchWithServerQuality1(), ContentTypeNegotiatorTest.testPickCorrectMatchWithServerQuality2(), ContentTypeNegotiatorTest.testPickFirstIfTwoEqualOptions(), ContentTypeNegotiatorTest.testQualityMultiplication(), MediaRangeSpecTest.testQuotedParameter(), PubbyNegotiatorTest.testSafariGetsHTML(), MediaRangeSpecTest.testSimpleParameters(), MediaRangeSpecTest.testSimpleSyntax(), ContentTypeNegotiatorTest.testSpecifyDefaultAccept(), PubbyNegotiatorTest.testTabulatorGetsRDF(), ContentTypeNegotiatorTest.testUseAliasQuality(), ContentTypeNegotiatorTest.testUseDefaultIfNoMatch(), ContentTypeNegotiatorTest.testUseDefaultIfTwoEqualOptions(), ContentTypeNegotiatorTest.testUserAgentOverrideSimple(), and MediaRangeSpecTest.testWithParameters().
{
                 return mediaType;
         }
getParameter()
String getParameter (String parameterName)
Referenced by MediaRangeSpec.getPrecedence(), MediaRangeSpecTest.testParametersAfterQualityAreIgnored(), MediaRangeSpecTest.testParameterValueEscaping(), MediaRangeSpecTest.testQualityAfterParameter(), MediaRangeSpecTest.testSimpleParameters(), MediaRangeSpecTest.testSimpleQuality(), and MediaRangeSpecTest.testSimpleSyntax().
{
                 for (int i = 0; i < parameterNames.size(); i++) {
                         if (parameterNames.get(i).equals(parameterName.toLowerCase())) {
                                 return (String) parameterValues.get(i);
                         }
                 }
                 return null;
         }
getParameterNames()
List<String> getParameterNames ()
References MediaRangeSpec.parameterNames.
Referenced by MediaRangeSpec.getPrecedence(), MediaRangeSpecTest.testSimpleParameters(), and MediaRangeSpecTest.testSimpleSyntax().
{
                 return parameterNames;
         }
getPrecedence()
int getPrecedence (MediaRangeSpec range)
References MediaRangeSpec.getParameter(), MediaRangeSpec.getParameterNames(), MediaRangeSpec.isWildcardSubtype(), MediaRangeSpec.isWildcardType(), MediaRangeSpec.subtype, and MediaRangeSpec.type.
Referenced by MediaRangeSpec.getBestMatch(), MediaRangeSpecTest.testCaseInsensitiveMatch(), and MediaRangeSpecTest.testGetPrecedence().
{
                 if (range.isWildcardType()) return 1;
                 if (!range.type.equals(type)) return 0;
                 if (range.isWildcardSubtype()) return 2;
                 if (!range.subtype.equals(subtype)) return 0;
                 if (range.getParameterNames().isEmpty()) return 3;
                 int result = 3;
                 for (int i = 0; i < range.getParameterNames().size(); i++) {
                         String name = (String) range.getParameterNames().get(i);
                         String value = range.getParameter(name);
                         if (!value.equals(getParameter(name))) return 0;
                         result++;
                 }
                 return result;
         }
getQuality()
double getQuality ()
References MediaRangeSpec.quality.
Referenced by ContentTypeNegotiator.Negotiation.evaluateDefaultVariant(), ContentTypeNegotiator.Negotiation.evaluateVariantAlias(), MediaRangeSpecTest.testIllegalQualityValue(), MediaRangeSpecTest.testParametersAfterQualityAreIgnored(), MediaRangeSpecTest.testQualityAfterParameter(), MediaRangeSpecTest.testQualityValue(), and MediaRangeSpecTest.testSimpleQuality().
{
                 return quality;
         }
getSubtype()
String getSubtype ()
References MediaRangeSpec.subtype.
Referenced by MediaRangeSpecTest.testGetSubtype(), MediaRangeSpecTest.testSimpleParameters(), and MediaRangeSpecTest.testSimpleSyntax().
{
                 return subtype;
         }
getType()
String getType ()
References MediaRangeSpec.type.
Referenced by MediaRangeSpecTest.testGetType(), MediaRangeSpecTest.testSimpleParameters(), and MediaRangeSpecTest.testSimpleSyntax().
{
                 return type;
         }
isWildcardSubtype()
boolean isWildcardSubtype ()
References MediaRangeSpec.isWildcardType().
Referenced by MediaRangeSpec.getPrecedence(), MediaRangeSpec.parseType(), MediaRangeSpecTest.testNoWildcard(), and MediaRangeSpecTest.testWildcard().
{
                 return !isWildcardType() && "*".equals(subtype);
         }
isWildcardType()
boolean isWildcardType ()
Referenced by MediaRangeSpec.getPrecedence(), MediaRangeSpec.isWildcardSubtype(), MediaRangeSpec.parseType(), MediaRangeSpecTest.testNoWildcard(), and MediaRangeSpecTest.testWildcard().
{
                 return "*".equals(type);
         }
parseAccept()
static List<MediaRangeSpec> parseAccept (String s) static
Parses an HTTP Accept header into a List of MediaRangeSpecs.
Returns
A List of MediaRangeSpecs
References MediaRangeSpec.parseRange().
Referenced by ContentTypeNegotiator.setDefaultAccept(), MediaRangeSpecTest.testAcceptIgnoreWSAndJunk(), MediaRangeSpecTest.testAcceptOneRange(), MediaRangeSpecTest.testAcceptTwoRanges(), MediaRangeSpecTest.testAcceptWithQuality(), MediaRangeSpecTest.testGetBestMatchSameQuality(), and ContentTypeNegotiator.toAcceptRanges().
{
                 List<MediaRangeSpec> result = new ArrayList<MediaRangeSpec>();
                 Matcher m = mediaRangePattern.matcher(s);
                 while (m.find()) {
                         result.add(parseRange(m.group()));
                 }
                 return result;
         }
parseRange()
static MediaRangeSpec parseRange (String mediaRange) static
Parses a media range from a string such as text/*;charset=utf-8;q=0.9.
Unlike simple media types, media ranges may include wildcards.
References MediaRangeSpec.MediaRangeSpec(), MediaRangeSpec.parameterNames, MediaRangeSpec.parameterValues, MediaRangeSpec.quality, MediaRangeSpec.subtype, MediaRangeSpec.type, and MediaRangeSpec.unescape().
Referenced by MediaRangeSpecTest.assertIllegalMediaTypeSyntax(), MediaRangeSpec.parseAccept(), MediaRangeSpec.parseType(), MediaRangeSpecTest.testCaseInsensitive(), MediaRangeSpecTest.testGetMediaType(), MediaRangeSpecTest.testGetPrecedence(), MediaRangeSpecTest.testGetSubtype(), MediaRangeSpecTest.testGetType(), MediaRangeSpecTest.testIllegalQualityValue(), MediaRangeSpecTest.testIllegalWildcard(), MediaRangeSpecTest.testNoWildcard(), MediaRangeSpecTest.testParametersAfterQualityAreIgnored(), MediaRangeSpecTest.testParameterValueEscaping(), MediaRangeSpecTest.testParameterValueEscapingRoundTrip(), MediaRangeSpecTest.testQualityAfterParameter(), MediaRangeSpecTest.testQualityValue(), MediaRangeSpecTest.testQuotedParameter(), MediaRangeSpecTest.testSimpleParameters(), MediaRangeSpecTest.testSimpleQuality(), MediaRangeSpecTest.testSimpleSyntax(), MediaRangeSpecTest.testWildcard(), and MediaRangeSpecTest.testWithParameters().
{
                 Matcher m = mediaRangePattern.matcher(mediaRange);
                 if (!m.matches()) {
                         return null;
                 }
                 String type = m.group(1).toLowerCase();
                 String subtype = m.group(2).toLowerCase();
                 String unparsedParameters = m.group(3);
                 String qValue = m.group(7);
                 m = parameterPattern.matcher(unparsedParameters);
                 if ("*".equals(type) && !"*".equals(subtype)) {
                         return null;
                 }
                 List<String> parameterNames = new ArrayList<String>();
                 List<String> parameterValues = new ArrayList<String>();
                 while (m.find()) {
                         String name = m.group(1).toLowerCase();
                         String value = (m.group(3) == null) ? m.group(2) : unescape(m.group(3));
                         parameterNames.add(name);
                         parameterValues.add(value);
                 }
                 double quality = 1.0;
                 if (qValue != null && qValuePattern.matcher(qValue).matches()) {
                         try {
                                 quality = Double.parseDouble(qValue);
                         } catch (NumberFormatException ex) {
                                 // quality stays at default value
                         }
                 }
                 return new MediaRangeSpec(type, subtype, parameterNames, parameterValues, quality);
         }
parseType()
static MediaRangeSpec parseType (String mediaType) static
Parses a media type from a string such as text/html;charset=utf-8;q=0.9.
References MediaRangeSpec.isWildcardSubtype(), MediaRangeSpec.isWildcardType(), and MediaRangeSpec.parseRange().
Referenced by ContentTypeNegotiator.VariantSpec.addAliasMediaType(), MediaRangeSpecTest.testCaseInsensitiveMatch(), MediaRangeSpecTest.testGetBestMatchSameQuality(), MediaRangeSpecTest.testGetPrecedence(), MediaRangeSpecTest.testNoWildcardsInMediaType(), and ContentTypeNegotiator.VariantSpec.VariantSpec().
{
                 MediaRangeSpec m = parseRange(mediaType);
                 if (m == null || m.isWildcardType() || m.isWildcardSubtype()) {
                         return null;
                 }
                 return m;
         }
toString()
String toString ()
References MediaRangeSpec.quality.
{
                 return mediaType + ";q=" + quality;
         }
unescape()
static String unescape (String s) static private
Referenced by MediaRangeSpec.parseRange().
{
                 return s.replaceAll("\\\\(.)", "$1");
         }
Member Data Documentation
mediaRangePattern
final Pattern mediaRangePattern static private
mediaType
final String mediaType private
Referenced by MediaRangeSpec.getMediaType().
parameterNames
final List<String> parameterNames private
Referenced by MediaRangeSpec.getParameterNames(), and MediaRangeSpec.parseRange().
parameterPattern
final Pattern parameterPattern static private
parameterValues
final List<String> parameterValues private
Referenced by MediaRangeSpec.MediaRangeSpec(), and MediaRangeSpec.parseRange().
quality
final double quality private
Referenced by MediaRangeSpec.getQuality(), MediaRangeSpec.MediaRangeSpec(), MediaRangeSpec.parseRange(), and MediaRangeSpec.toString().
qValuePattern
final Pattern qValuePattern static private
subtype
final String subtype private
Referenced by MediaRangeSpec.getPrecedence(), MediaRangeSpec.getSubtype(), MediaRangeSpec.MediaRangeSpec(), and MediaRangeSpec.parseRange().
tokenPattern
final Pattern tokenPattern static private
type
final String type private
Referenced by MediaRangeSpec.getPrecedence(), MediaRangeSpec.getType(), MediaRangeSpec.MediaRangeSpec(), and MediaRangeSpec.parseRange().