GeoPubby: ResourceDescription.Value Class Reference
ResourceDescription.Value Class Reference
Public Member Functions
Value (RDFNode valueNode, Property predicate, VocabularyStore vocabularyStore)
Node getNode ()
String getBrowsableURL ()
boolean hasPrefix ()
String getPrefix ()
String getLocalName ()
String getLabel ()
String getDescription ()
String getDatatypeLabel ()
String getDatatypeURI ()
boolean isType ()
int compareTo (Value other)
Private Attributes
final RDFNode node
URIPrefixer prefixer
Property predicate
VocabularyStore vocabularyStore
Constructor & Destructor Documentation
Value()
Value (RDFNode valueNode, Property predicate, VocabularyStore vocabularyStore)
References ResourceDescription.getPrefixes(), ResourceDescription.ResourceProperty.predicate, and ResourceDescription.ResourceProperty.vocabularyStore.
{
                         this.node = valueNode;
                         this.predicate = predicate;
                         this.vocabularyStore = vocabularyStore;
                         if (valueNode.isURIResource()) {
                                 prefixer = new URIPrefixer((Resource) valueNode.as(Resource.class), getPrefixes());
                         }
                 }
Member Function Documentation
compareTo()
int compareTo (Value other)
References ResourceDescription.Value.compareTo(), and ResourceDescription.Value.getNode().
Referenced by ResourceDescription.Value.compareTo().
{
                         if (!(other instanceof Value)) {
                                 return 0;
                         }
                         Value otherValue = (Value) other;
                         if (getNode().isURI() && otherValue.getNode().isURI()) {
                                 return getNode().getURI().compareTo(otherValue.getNode().getURI());
                         }
                         if (getNode().isURI()) {
                                 return 1;
                         }
                         if (otherValue.getNode().isURI()) {
                                 return -1;
                         }
                         if (getNode().isBlank() && otherValue.getNode().isBlank()) {
                                 return getNode().getBlankNodeLabel().compareTo(otherValue.getNode().getBlankNodeLabel());
                         }
                         if (getNode().isBlank()) {
                                 return 1;
                         }
                         if (otherValue.getNode().isBlank()) {
                                 return -1;
                         }
                         // TODO Typed literals, language literals
                         return getNode().getLiteralLexicalForm().compareTo(otherValue.getNode().getLiteralLexicalForm());
                 }
getBrowsableURL()
String getBrowsableURL ()
References ResourceDescription.config, HypermediaControls.createFromIRI(), and HypermediaControls.getPageURL().
{
                         if (!node.isURIResource()) return null;
                         HypermediaControls controls = HypermediaControls.createFromIRI(
                                         node.asResource().getURI(), config);
                         if (controls == null) return node.asResource().getURI();
                         return controls.getPageURL();
                 }
getDatatypeLabel()
String getDatatypeLabel ()
References URIPrefixer.getLocalName(), ResourceDescription.getPrefixes(), URIPrefixer.hasPrefix(), and URIPrefixer.toTurtle().
{
                         if (!node.isLiteral()) return null;
                         String uri = ((Literal) node.as(Literal.class)).getDatatypeURI();
                         if (uri == null) return null;
                         URIPrefixer datatypePrefixer = new URIPrefixer(uri, getPrefixes());
                         if (datatypePrefixer.hasPrefix()) {
                                 return datatypePrefixer.toTurtle();
                         } else {
                                 return "?:" + datatypePrefixer.getLocalName();
                         }
                 }
getDatatypeURI()
String getDatatypeURI ()
{
                         if (!node.isLiteral()) return null;
                         String uri = ((Literal) node.as(Literal.class)).getDatatypeURI();
                         if (uri == null) return null;
                         return uri;
                 }
getDescription()
String getDescription ()
References VocabularyStore.getDescription().
{
                         return vocabularyStore.getDescription(node.asNode().getURI()).getLexicalForm();
                 }
getLabel()
String getLabel ()
References ResourceDescription.config, VocabularyStore.getCachedLabel(), VocabularyStore.getLabel(), ResourceDescription.ResourceProperty.getLabel(), ResourceDescription.model, ResourceDescription.ResourceDescription(), and ResourceDescription.toTitleCase().
{
                         System.out.println("Getting label for "+node.toString());
                         if (!node.isResource()) return null;
                         System.out.println(node.toString()+" is a resource!");
                         Literal result = null;
                         if (node.isURIResource()) {
                                 if (predicate.equals(RDF.type)) {
                                         // Look up class labels in vocabulary store
                                         result = vocabularyStore.getLabel(node.asNode().getURI(), false);
                                 } else if (node.isURIResource()) {
                                         // If it's not a class, see if we happen to have a label cached
                                         result = vocabularyStore.getCachedLabel(node.asResource().getURI(), false);
                                         //System.out.println("HasCachedLabel? "+result.toString());
                                 }
                         }
                         if (result == null) {
                                 // Use any label that may be included in the description model
                                 result = new ResourceDescription(node.asResource(), model, config).getLabel();
                                 //System.out.println("Resource has label? "+result.toString());
                         }
                         if (result == null) return null;
                         return toTitleCase(result.getLexicalForm(), result.getLanguage());
                 }
getLocalName()
String getLocalName ()
References URIPrefixer.getLocalName().
{
                         if (prefixer == null) {
                                 return null;
                         }
                         return prefixer.getLocalName();
                 }
getNode()
Node getNode ()
Referenced by ResourceDescription.Value.compareTo().
{
                         return node.asNode();
                 }
getPrefix()
String getPrefix ()
References URIPrefixer.getPrefix().
{
                         if (prefixer == null) {
                                 return null;
                         }
                         return prefixer.getPrefix();
                 }
hasPrefix()
boolean hasPrefix ()
References URIPrefixer.hasPrefix().
{
                         return prefixer != null && prefixer.hasPrefix();
                 }
isType()
boolean isType ()
{
                         return predicate.equals(RDF.type);
                 }
Member Data Documentation
node
final RDFNode node private
predicate
Property predicate private
prefixer
URIPrefixer prefixer private
vocabularyStore
VocabularyStore vocabularyStore private