GeoPubby: Configuration Class Reference
Configuration Class Reference
The server's configuration.
Public Member Functions
Configuration (Resource configuration)
DataSource getDataSource ()
A composite DataSource representing the merge of all datasets.
List< Dataset > getDatasets ()
The conf:dataset blocks.
HypermediaControls getControls (String relativeRequestURI, boolean isRelativeToPubbyRoot)
PrefixMapping getPrefixes ()
Collection< Property > getLabelProperties ()
Collection< Property > getCommentProperties ()
Collection< Property > getImageProperties ()
String getDefaultLanguage ()
String getIndexIRI ()
The "home" resource.
String getProjectLink ()
String getProjectName ()
String getWebApplicationBaseURI ()
String getWebResourcePrefix ()
boolean showLabels ()
VocabularyStore getVocabularyStore ()
Set< String > getBrowsableNamespaces ()
Gets all values of conf:browsableNamespace declared on the configuration resource.
boolean isBrowsable (String iri)
Resource getSelf ()
Model getModel ()
boolean hasType (Resource class_)
boolean hasProperty (Property p)
Resource getResource (Property p)
Set< Resource > getResources (Property p)
Set< Property > getProperties (Property p)
String getIRI (Property p)
String getIRI (Property p, String defaultValue)
String getRequiredIRI (Property p)
Set< String > getIRIs (Property p)
String getString (Property p)
String getString (Property p, String defaultValue)
Set< String > getStrings (Property p)
boolean getBoolean (Property p, boolean defaultValue)
void requireExactlyOneOf (Property... properties)
Static Public Member Functions
static Configuration create (Model model)
Private Member Functions
DataSource buildDataSource ()
Private Attributes
final PrefixMapping prefixes
final String webBase
final Collection< Property > labelProperties
final Collection< Property > commentProperties
final Collection< Property > imageProperties
final ArrayList< Dataset > datasets = new ArrayList<Dataset>()
final VocabularyStore vocabularyStore = new VocabularyStore()
final DataSource dataSource
final String indexIRI
final Set< String > allBrowsableNamespaces = new HashSet<String>()
Detailed Description
The server's configuration.
Constructor & Destructor Documentation
Configuration()
Configuration (Resource configuration)
References ModelUtil.addNSIfUndefined(), CONF.AnnotationProvider, Configuration.buildDataSource(), CONF.commentProperty, CONF.dataset, DataSource.describeResource(), Dataset.getBrowsableNamespaces(), Configuration.getBrowsableNamespaces(), Configuration.getDataSource(), Configuration.getDefaultLanguage(), DataSource.getIndex(), ResourceReader.getIRI(), ResourceReader.getIRIs(), DataSource.getLabelIndex(), ResourceReader.getModel(), ResourceReader.getProperties(), ResourceReader.getRequiredIRI(), ResourceReader.getResources(), Configuration.getWebApplicationBaseURI(), Configuration.getWebResourcePrefix(), ResourceReader.hasProperty(), CONF.imageProperty, CONF.indexResource, CONF.labelProperty, CONF.loadRDF, CONF.loadVocabulary, CONF.NS, VocabularyStore.setDataSource(), VocabularyStore.setDefaultLanguage(), CONF.usePrefixesFrom, CONF.wdImage, and CONF.webBase.
Referenced by Configuration.create().
{
                 super(configuration);
                 webBase = getRequiredIRI(CONF.webBase);
                 // Create datasets from conf:dataset
                 for (Resource r: getResources(CONF.dataset)) {
                         Dataset ds = new Dataset(r, this);
                         datasets.add(ds);
                         allBrowsableNamespaces.addAll(ds.getBrowsableNamespaces());
                 }
                 allBrowsableNamespaces.add(getWebApplicationBaseURI() + getWebResourcePrefix());
                 allBrowsableNamespaces.addAll(getBrowsableNamespaces());
                 // Create datasets from conf:loadVocabularyFromURL
                 for (String sourceURL: getIRIs(CONF.loadVocabulary)) {
                         Model m = ModelFactory.createDefaultModel();
                         Resource dummyDataset = m.createResource();
                         dummyDataset.addProperty(CONF.loadRDF, m.createResource(sourceURL));
                         dummyDataset.addProperty(RDF.type, CONF.AnnotationProvider);
                         datasets.add(new Dataset(dummyDataset, this));
                 }
                 labelProperties = getProperties(CONF.labelProperty);
                 if (labelProperties.isEmpty()) {
                         labelProperties.add(RDFS.label);
                         labelProperties.add(DC.title);
                         labelProperties.add(DCTerms.title);
                         labelProperties.add(FOAF.name);
                 }
                 commentProperties = getProperties(CONF.commentProperty);
                 if (commentProperties.isEmpty()) {
                         commentProperties.add(RDFS.comment);
                         commentProperties.add(DC.description);
                         commentProperties.add(DCTerms.description);
                 }
                 imageProperties = getProperties(CONF.imageProperty);
                 if (imageProperties.isEmpty()) {
                         imageProperties.add(FOAF.depiction);
                         imageProperties.add(CONF.wdImage);
                 }
                 prefixes = new PrefixMappingImpl();
                 if (hasProperty(CONF.usePrefixesFrom)) {
                         for (String iri: getIRIs(CONF.usePrefixesFrom)) {
                                 prefixes.setNsPrefixes(FileManager.get().loadModel(iri));
                         }
                 } else {
                         prefixes.setNsPrefixes(getModel());
                 }
                 if (prefixes.getNsURIPrefix(CONF.NS) != null) {
                         prefixes.removeNsPrefix(prefixes.getNsURIPrefix(CONF.NS));
                 }
                 // If no prefix is defined for the RDF and XSD namespaces, set them,
                 // unless that would overwrite something. This is the namespaces that
                 // have syntactic sugar in Turtle.
                 ModelUtil.addNSIfUndefined(prefixes, "rdf", RDF.getURI());
                 ModelUtil.addNSIfUndefined(prefixes, "xsd", XSD.getURI());
                 ModelUtil.addNSIfUndefined(prefixes, "rdfs", RDFS.getURI());
                 ModelUtil.addNSIfUndefined(prefixes, "owl", "http://www.w3.org/2002/07/owl#");
                 ModelUtil.addNSIfUndefined(prefixes, "pubby", webBase);
                 System.out.println("Building datasource");
                 dataSource = buildDataSource();
                 // Vocabulary data source contains our normal data sources plus
                 // the configuration model, so that we can read labels etc from
                 // the configuration file
                 DataSource vocabularyDataSource = new MergeDataSource(
                                 new ModelDataSource(getModel()), getDataSource());
                 vocabularyStore.setDataSource(vocabularyDataSource);
                 vocabularyStore.setDefaultLanguage(getDefaultLanguage());
                 // Sanity check to spot typical configuration problem
                 if (dataSource.getIndex().isEmpty()) {
                         throw new ConfigurationException("The index is empty. " +
                                         "Try adding conf:datasetBase to your datasets, " +
                                         "check any conf:datasetURIPatterns, " +
                                         "and check that all data sources actually contain data.");
                 }
                 System.out.println("Datasource index: "+dataSource.getLabelIndex());
                 String resourceBase = getWebApplicationBaseURI() + getWebResourcePrefix();
                 if (hasProperty(CONF.indexResource)) {
                         indexIRI = getIRI(CONF.indexResource);
                         // Sanity check to spot typical configuration problem
                         if (dataSource.describeResource(indexIRI).isEmpty()) {
                                 throw new ConfigurationException(
                                                 "conf:indexResource <" + indexIRI +
                                                 "> not found in data sets. " +
                                                 "Try disabling the conf:indexResource to get " +
                                                 "a list of found resources.");
                         }
                 } else {
                         indexIRI = resourceBase;
                 }
         }
Member Function Documentation
buildDataSource()
DataSource buildDataSource () private
References DataSource.describeResource(), Configuration.getWebResourcePrefix(), ResourceReader.hasProperty(), and CONF.indexResource.
Referenced by Configuration.Configuration().
{
                 List<DataSource> sources = new ArrayList<DataSource>(datasets.size());
                 for (Dataset dataset: datasets) {
                         sources.add(dataset.getDataSource());
                 }
                 DataSource result = new MergeDataSource(sources, prefixes);
                 // If we don't have an indexResource, and there is no resource
                 // at the home URL in any of the datasets, then add an
                 // index builder. It will be responsible for handling the
                 // homepage/index resource.
                 // TODO: Shouldn't we make the index data source available even if there
                 //       is an indexResource?
                 String indexIRI = webBase + getWebResourcePrefix();
                 if (!hasProperty(CONF.indexResource) &&
                                 result.describeResource(indexIRI).isEmpty()) {
                         result = new IndexDataSource(indexIRI, result);
                 }
                 return result;
         }
create()
static Configuration create (Model model) static
References CONF.Configuration, and Configuration.Configuration().
Referenced by ServletContextInitializer.initConfiguration(), and Reloader.run().
{
                 StmtIterator it = model.listStatements(null, RDF.type, CONF.Configuration);
                 if (!it.hasNext()) {
                         throw new IllegalArgumentException(
                                         "No resource with type conf:Configuration found in configuration file");
                 }
                 return new Configuration(it.nextStatement().getSubject());
         }
getBoolean()
boolean getBoolean (Property p, boolean defaultValue) inherited
References ResourceReader.assertHasOneValue(), ResourceReader.assertLiteralValue(), and ResourceReader.raiseUnexpectedDatatype().
Referenced by Dataset.addSameAsStatements(), Configuration.showLabels(), Dataset.supportsIRIs(), and Dataset.supportsSPARQL11().
{
                 if (!resource.hasProperty(p)) {
                         return defaultValue;
                 }
                 assertHasOneValue(p);
                 assertLiteralValue(p);
                 Literal value = resource.getProperty(p).getLiteral();
                 if (XSD.xboolean.getURI().equals(value.getDatatypeURI())) {
                         return value.getBoolean();
                 }
                 if (value.getDatatypeURI() == null || XSD.xstring.getURI().equals(value.getDatatypeURI())) {
                         if ("true".equals(value.getString().toLowerCase())
                                         || "false".equals(value.getString().toLowerCase())) {
                                 return "true".equals(value.getString().toLowerCase());
                         }
                 }
                 raiseUnexpectedDatatype("xsd:boolean", resource.getProperty(p));
                 return false;
         }
getBrowsableNamespaces()
Set<String> getBrowsableNamespaces ()
Gets all values of conf:browsableNamespace declared on the configuration resource.
Does not include values declared on specific datasets.
Returns
Namespace IRIs of browsable namespaces
References CONF.browsableNamespace, and ResourceReader.getIRIs().
Referenced by Dataset.buildDataSource(), and Configuration.Configuration().
{
                 return getIRIs(CONF.browsableNamespace);
         }
getCommentProperties()
Collection<Property> getCommentProperties ()
References Configuration.commentProperties.
Referenced by ResourceDescription.getComment().
{
                 return commentProperties;
         }
getControls()
HypermediaControls getControls (String relativeRequestURI, boolean isRelativeToPubbyRoot)
Parameters
relativeRequestURI URI relative to the Pubby root (conf:webBase)
isRelativeToPubbyRoot If true, the IRI is relative to the Pubby root (conf:webBase); otherwise, the IRI is relative to some non-resource namespace such as /page/. The distinction matters if conf:webResourcePrefix is set.
References HypermediaControls.createFromPubbyPath(), Configuration.getWebResourcePrefix(), and IRIEncoder.toIRI().
Referenced by PageURLServlet.doGet(), WebURIServlet.doGet(), DataURLServlet.doGet(), ValuesBaseServlet.doGet(), and MappedResource.MappedResource().
{
                 String relativeIRI = IRIEncoder.toIRI(relativeRequestURI);
                 if (isRelativeToPubbyRoot) {
                         if (!relativeIRI.startsWith(getWebResourcePrefix())) return null;
                 } else {
                         relativeIRI = relativeIRI.substring(getWebResourcePrefix().length());
                 }
                 return HypermediaControls.createFromPubbyPath(relativeIRI, this);
         }
getDatasets()
List<Dataset> getDatasets ()
The conf:dataset blocks.
References Configuration.datasets.
Referenced by BaseServlet.addDocumentMetadata(), BaseServlet.addPageMetadata(), PageURLServlet.doGet(), and SearchServlet.doGet().
{
                 return datasets;
         }
getDataSource()
DataSource getDataSource ()
A composite DataSource representing the merge of all datasets.
References Configuration.dataSource.
Referenced by Configuration.Configuration(), ValuesDataURLServlet.doGet(), ValuesURLServlet.doGet(), SearchServlet.doGet(), and HypermediaControls.getResourceDescription().
{
                 return dataSource;
         }
getDefaultLanguage()
String getDefaultLanguage ()
References CONF.defaultLanguage, and ResourceReader.getString().
Referenced by Configuration.Configuration(), ResourceDescription.getComment(), ResourceDescription.getLabel(), and ResourceDescription.toTitleCase().
{
                 return getString(CONF.defaultLanguage, "en");
         }
getImageProperties()
Collection<Property> getImageProperties ()
References Configuration.imageProperties.
Referenced by ResourceDescription.getImageURL().
{
                 return imageProperties;
         }
getIndexIRI()
String getIndexIRI ()
The "home" resource.
If its IRI is not the web server base, then the web server will redirect there.
References Configuration.indexIRI.
Referenced by RootServlet.doGet().
{
                 return indexIRI;
         }
getIRI() [1/2]
String getIRI (Property p) inherited
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), Configuration.getProjectLink(), ResourceReader.getRequiredIRI(), and MetadataConfiguration.MetadataConfiguration().
{
                 return getIRI(p, null);
         }
getIRI() [2/2]
String getIRI (Property p, String defaultValue) inherited
References ResourceReader.assertHasOneValue(), and ResourceReader.assertIRIValue().
{
                 if (!resource.hasProperty(p)) return defaultValue;
                 assertHasOneValue(p);
                 assertIRIValue(p);
                 return resource.getProperty(p).getResource().getURI();
         }
getIRIs()
Set<String> getIRIs (Property p) inherited
References ResourceReader.assertIRIValue().
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), Dataset.getBrowsableNamespaces(), and Configuration.getBrowsableNamespaces().
{
                 Set<String> result = new HashSet<String>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertIRIValue(stmt);
                         result.add(stmt.getResource().getURI());
                 }
                 return result;
         }
getLabelProperties()
Collection<Property> getLabelProperties ()
References Configuration.labelProperties.
Referenced by ResourceDescription.getLabel().
{
                 return labelProperties;
         }
getModel()
Model getModel () inherited
Referenced by MetadataConfiguration.addMetadataFromTemplate(), Configuration.Configuration(), MetadataConfiguration.parsePlaceholder(), and ResourceReader.pretty().
{
                 return resource.getModel();
         }
getPrefixes()
PrefixMapping getPrefixes ()
References Configuration.prefixes.
Referenced by ValuesBaseServlet.doGet(), HypermediaResource.getPathURL(), HypermediaControls.getPathURL(), and ResourceDescription.getPrefixes().
{
                 return prefixes;
         }
getProjectLink()
String getProjectLink ()
References ResourceReader.getIRI(), and CONF.projectHomepage.
Referenced by PageURLServlet.doGet(), ValuesURLServlet.doGet(), and BaseServlet.send404().
{
                 return getIRI(CONF.projectHomepage);
         }
getProjectName()
String getProjectName ()
References ResourceReader.getString(), and CONF.projectName.
Referenced by PageURLServlet.doGet(), ValuesURLServlet.doGet(), and BaseServlet.send404().
{
                 return getString(CONF.projectName);
         }
getProperties()
Set<Property> getProperties (Property p) inherited
References ResourceReader.getResources().
Referenced by Configuration.Configuration().
{
                 Set<Property> result = new HashSet<Property>();
                 for (Resource r: getResources(p)) {
                         result.add(r.as(Property.class));
                 }
                 return result;
         }
getRequiredIRI()
String getRequiredIRI (Property p) inherited
References ResourceReader.getIRI(), and ResourceReader.raiseMissingProperty().
Referenced by Configuration.Configuration().
{
                 if (!resource.hasProperty(p)) {
                         raiseMissingProperty(p);
                 }
                 return getIRI(p);
         }
getResource()
Resource getResource (Property p) inherited
References ResourceReader.assertHasOneValue(), and ResourceReader.assertResourceValue().
Referenced by MetadataConfiguration.MetadataConfiguration().
{
                 if (!resource.hasProperty(p)) return null;
                 assertHasOneValue(p);
                 assertResourceValue(p);
                 return resource.getProperty(p).getResource();
         }
getResources()
Set<Resource> getResources (Property p) inherited
References ResourceReader.assertResourceValue().
Referenced by Configuration.Configuration(), and ResourceReader.getProperties().
{
                 Set<Resource> result = new HashSet<Resource>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertResourceValue(stmt);
                         result.add(stmt.getResource());
                 }
                 return result;
         }
getSelf()
Resource getSelf () inherited
References ResourceReader.resource.
Referenced by MetadataConfiguration.parsePlaceholder().
{
                 return resource;
         }
getString() [1/2]
String getString (Property p) inherited
Referenced by Dataset.buildDataSource(), Configuration.getDefaultLanguage(), Configuration.getProjectName(), and Configuration.getWebResourcePrefix().
{
                 return getString(p, null);
         }
getString() [2/2]
String getString (Property p, String defaultValue) inherited
References ResourceReader.assertHasOneValue(), and ResourceReader.assertString().
{
                 if (!resource.hasProperty(p)) {
                         return defaultValue;
                 }
                 assertHasOneValue(p);
                 assertString(resource.getProperty(p));
                 return resource.getProperty(p).getString();
         }
getStrings()
Set<String> getStrings (Property p) inherited
References ResourceReader.assertString().
Referenced by Dataset.buildDataSource().
{
                 Set<String> result = new HashSet<String>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertString(stmt);
                         result.add(stmt.getString());
                 }
                 return result;
         }
getVocabularyStore()
VocabularyStore getVocabularyStore ()
References Configuration.vocabularyStore.
Referenced by Dataset.buildDataSource(), ResourceDescription.buildProperties(), ResourceDescription.ResourceProperty.compareTo(), and ResourceDescription.learnHighDegreeProperties().
{
                 return vocabularyStore;
         }
getWebApplicationBaseURI()
String getWebApplicationBaseURI ()
References Configuration.webBase.
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), HypermediaControls.createFromPubbyPath(), RootServlet.doGet(), PageURLServlet.doGet(), ValuesURLServlet.doGet(), SearchServlet.doGet(), HypermediaResource.getAbsoluteIRI(), HypermediaResource.getDataURL(), HypermediaControls.getDataURL(), HypermediaResource.getPageURL(), HypermediaControls.getPageURL(), HypermediaResource.getPathURL(), HypermediaControls.getPathURL(), HypermediaControls.getPubbyPath(), HypermediaControls.HypermediaControls(), and BaseServlet.send404().
{
                 return webBase;
         }
getWebResourcePrefix()
String getWebResourcePrefix ()
References ResourceReader.getString(), and CONF.webResourcePrefix.
Referenced by Dataset.buildDataSource(), Configuration.buildDataSource(), Configuration.Configuration(), HypermediaControls.createFromPubbyPath(), HypermediaResource.getAbsoluteIRI(), Configuration.getControls(), and HypermediaControls.getPubbyPath().
{
                 return getString(CONF.webResourcePrefix, "");
         }
hasProperty()
boolean hasProperty (Property p) inherited
Referenced by Dataset.buildDataSource(), Configuration.buildDataSource(), and Configuration.Configuration().
{
                 return resource.hasProperty(p);
         }
hasType()
boolean hasType (Resource class_) inherited
Referenced by Dataset.buildDataSource().
{
                 return resource.hasProperty(RDF.type, class_);
         }
isBrowsable()
boolean isBrowsable (String iri)
Referenced by HypermediaControls.createFromIRI().
{
                 for (String namespace: allBrowsableNamespaces) {
                         if (iri.startsWith(namespace)) return true;
                 }
                 return false;
         }
requireExactlyOneOf()
void requireExactlyOneOf (Property... properties) inherited
References ResourceReader.pretty().
Referenced by Dataset.buildDataSource().
{
                 Property found = null;
                 boolean first = true;
                 StringBuilder s = new StringBuilder();
                 for (Property p: properties) {
                         if (resource.hasProperty(p)) {
                                 if (found == null) {
                                         found = p;
                                 } else {
                                         throw new ConfigurationException("Can't have both " +
                                                         pretty(found) + " and " + pretty(p) +
                                                         " on resource " + pretty(resource));
                                 }
                         }
                         if (!first) {
                                 s.append(", ");
                         }
                         s.append(pretty(p));
                         first = false;
                 }
                 if (found == null) {
                         throw new ConfigurationException("One of " + s.toString() +
                                         " required on resource " + pretty(resource));
                 }
         }
showLabels()
boolean showLabels ()
References ResourceReader.getBoolean(), and CONF.showLabels.
Referenced by PageURLServlet.doGet(), and ValuesURLServlet.doGet().
{
                 return getBoolean(CONF.showLabels, true);
         }
Member Data Documentation
allBrowsableNamespaces
final Set<String> allBrowsableNamespaces = new HashSet<String>() private
commentProperties
final Collection<Property> commentProperties private
Referenced by Configuration.getCommentProperties().
datasets
final ArrayList<Dataset> datasets = new ArrayList<Dataset>() private
Referenced by Configuration.getDatasets().
dataSource
final DataSource dataSource private
Referenced by Configuration.getDataSource().
imageProperties
final Collection<Property> imageProperties private
Referenced by Configuration.getImageProperties().
indexIRI
final String indexIRI private
Referenced by Configuration.getIndexIRI().
labelProperties
final Collection<Property> labelProperties private
Referenced by Configuration.getLabelProperties().
prefixes
final PrefixMapping prefixes private
Referenced by Configuration.getPrefixes().
vocabularyStore
final VocabularyStore vocabularyStore = new VocabularyStore() private
Referenced by Configuration.getVocabularyStore().
webBase
final String webBase private
Referenced by Configuration.getWebApplicationBaseURI().