GeoPubby: ModelResponse Class Reference
ModelResponse Class Reference
Calls into Joseki to send a Jena model over HTTP.
Classes
class JSONWriter
class NQuadsWriter
class NTriplesWriter
class RDFJSONWriter
class RDFThriftWriter
class RDFXMLWriter
class TrigWriter
class TrixWriter
class TurtleWriter
Public Member Functions
ModelResponse (Model model, HttpServletRequest request, HttpServletResponse response)
void serve ()
Private Member Functions
void doResponseModel () throws IOException
ModelWriter getWriter (String mediaType)
Private Attributes
final Model model
final HttpServletRequest request
final HttpServletResponse response
Detailed Description
Calls into Joseki to send a Jena model over HTTP.
This gives us content negotiation and all the other tricks supported by Joseki for free. This has to be in the Joseki package because some required methods are not visible.
Constructor & Destructor Documentation
ModelResponse()
ModelResponse (Model model, HttpServletRequest request, HttpServletResponse response)
References RequestParamHandler.getModifiedRequest(), RequestParamHandler.isMatchingRequest(), ModelResponse.model, ModelResponse.request, and ModelResponse.response.
{
                 // Handle ?output=format request parameter
                 RequestParamHandler handler = new RequestParamHandler(request);
                 if (handler.isMatchingRequest()) {
                         request = handler.getModifiedRequest();
                 }
                 this.model = model;
                 this.request = request;
                 this.response = response;
         }
Member Function Documentation
doResponseModel()
void doResponseModel () throws IOException private
References ContentTypeNegotiator.getBestMatch(), PubbyNegotiator.getDataNegotiator(), MediaRangeSpec.getMediaType(), and ModelResponse.getWriter().
Referenced by ModelResponse.serve().
{
                 response.addHeader("Vary", "Accept");
                 ContentTypeNegotiator negotiator = PubbyNegotiator.getDataNegotiator();
                 MediaRangeSpec bestMatch = negotiator.getBestMatch(
                                 request.getHeader("Accept"), request.getHeader("User-Agent"));
                 if (bestMatch == null) {
                         response.setStatus(406);
                         response.setContentType("text/plain");
                         ServletOutputStream out = response.getOutputStream();
                         out.println("406 Not Acceptable: The requested data format is not supported.");
                         out.println("Supported formats are RDF/XML, JSON-LD, GeoJSON, GeoURI, TriX, WKT, GML, KML, SVG, GPX, TriG, Turtle, N3, and N-Triples.");
                         return;
                 }
                 response.setContentType(bestMatch.getMediaType());
                 getWriter(bestMatch.getMediaType()).write(model, response);
                 response.getOutputStream().flush();
     }
getWriter()
ModelWriter getWriter (String mediaType) private
Referenced by ModelResponse.doResponseModel().
{
                 if ("application/rdf+xml".equals(mediaType)) {
                         return new RDFXMLWriter();
                 }
                 if ("application/rdf+json".equals(mediaType)) {
                         return new RDFJSONWriter();
                 }
                 if ("application/json".equals(mediaType)) {
                         return new JSONWriter();
                 }
                 if ("application/geojson".equals(mediaType)) {
                         return new GeoJSONWriterr();
                 }
                 if ("application/topojson".equals(mediaType)) {
                         return new TopoJSONWriter();
                 }
                 if ("image/svg+xml".equals(mediaType)) {
                         return new SVGWriter();
                 }
                 if ("text/latlon".equals(mediaType)) {
                         return new LatLonTextWriter();
                 }
                 if("text/csv".equals(mediaType)){
                         return new CSVWriter();
                 }
                 if("text/gpx".equals(mediaType)){
                         return new GPXWriter();
                 }
                 if ("application/osm+xml".equals(mediaType)) {
                         return new OSMWriter();
                 }
                 if ("text/osmlink".equals(mediaType)) {
                         return new OSMLinkWriter();
                 }
                 if ("text/googlemapslink".equals(mediaType)) {
                         return new GoogleMapsLinkWriter();
                 }
                 if ("application/geouri".equals(mediaType)) {
                         return new GeoURIWriter();
                 }
                 if ("application/gml".equals(mediaType)) {
                         return new GMLWriter();
                 }
                 if ("application/kml".equals(mediaType)) {
                         return new KMLWriter();
                 }
                 if ("application/trig".equals(mediaType)) {
                         return new TrigWriter();
                 }
                 if ("text/wkt".equals(mediaType)) {
                         return new WKTWriter();
                 }
                 if ("application/trix".equals(mediaType)) {
                         return new TrixWriter();
                 }
                 if ("application/x-turtle".equals(mediaType)) {
                         return new TurtleWriter();
                 }
                 if ("text/rdf+n3;charset=utf-8".equals(mediaType)) {
                         return new TurtleWriter();
                 }
                 if("application/rt".equals(mediaType)) {
                         return new RDFThriftWriter();
                 }
                 if("text/nq".equals(mediaType)) {
                         return new NQuadsWriter();
                 }
                 if("application/hex+x-ndjson".equals(mediaType)) {
                         return new HexTuplesWriter();
                 }
                 return new NTriplesWriter();
         }
serve()
void serve ()
References ModelResponse.doResponseModel().
Referenced by ValuesDataURLServlet.doGet().
{
                 // Error hendling is still quite a mess here.
                 try {
                         doResponseModel();
                 } catch (IOException ioEx) {
                         throw new RuntimeException(ioEx);
                 } catch (JenaException jEx) {
                         try {
                                 response.sendError(
                                                 HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                                                 "JenaException: " + jEx.getMessage());
                                 jEx.printStackTrace();
             } catch (IOException e) {
                 throw new RuntimeException(e);
             }
                 }
         }
Member Data Documentation
model
final Model model private
Referenced by ModelResponse.ModelResponse().
request
final HttpServletRequest request private
Referenced by ModelResponse.ModelResponse().
response
final HttpServletResponse response private
Referenced by ModelResponse.ModelResponse().