GeoPubby: ModelResponse.JSONWriter Class Reference
ModelResponse.JSONWriter Class Reference
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
{
                         model.getWriter("JSON-LD").write(model, response.getOutputStream(), null);
                         return null;
                 }
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GoogleMapsLinkWriter.write(), XYZASCIIWriter.write(), GeoURIWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), TopoJSONWriter.write(), GeoJSONWriterr.write(), CSVWriter.write(), KMLWriter.write(), GPXWriter.write(), GMLWriter.write(), SVGWriter.write(), OSMWriter.write(), MapMLWriter.write(), and LatLonTextWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by KMLWriter.write(), OSMWriter.write(), GPXWriter.write(), GMLWriter.write(), and MapMLWriter.write().