GeoPubby: VelocityHelper Class Reference
VelocityHelper Class Reference
A facade class that simplifies using a custom Velocity engine from a servlet.
Public Member Functions
VelocityHelper (ServletContext servletContext, HttpServletResponse response)
Context getVelocityContext ()
void renderXHTML (String templateName)
Renders a template using the template variables put into the velocity context.
Private Member Functions
VelocityEngine getVelocityEngine ()
VelocityEngine createVelocityEngine ()
Private Attributes
final ServletContext servletContext
final HttpServletResponse response
final Context velocityContext
Static Private Attributes
static final String VELOCITY_ENGINE
Detailed Description
A facade class that simplifies using a custom Velocity engine from a servlet.
It encapsulates creation of the VelocityEngine instance, its storage in the servlet context, and the rendering of templates into the servlet response output stream.
Constructor & Destructor Documentation
VelocityHelper()
VelocityHelper (ServletContext servletContext, HttpServletResponse response)
References VelocityHelper.response, and VelocityHelper.servletContext.
{
                 this.servletContext = servletContext;
                 this.response = response;
                 this.velocityContext = new VelocityContext();
         }
Member Function Documentation
createVelocityEngine()
VelocityEngine createVelocityEngine () private
Referenced by VelocityHelper.getVelocityEngine().
{
                 try {
                         VelocityEngine result = new VelocityEngine();
                         result.setProperty("output.encoding", "utf-8");
                         result.setProperty("file.resource.loader.path",
                                         servletContext.getRealPath("/") + "/WEB-INF/templates/");
                         result.setProperty("velocimacro.context.localscope", true);
                         // Turn off Velocity logging
                         result.setProperty("runtime.log.logsystem.class",
                                         "org.apache.velocity.runtime.log.NullLogSystem");
                         // XML-escape *all* references inserted into templates
                         result.setProperty("eventhandler.referenceinsertion.class", EscapeXmlReference.class.getName());
                         // Enable caching
                         result.setProperty("file.resource.loader.cache", true);
                         result.init();
                         return result;
                 } catch (Exception ex) {
                         throw new RuntimeException(ex);
                 }
         }
getVelocityContext()
Context getVelocityContext ()
Returns
A receptacle for template variables
References VelocityHelper.velocityContext.
{
                 return velocityContext;
         }
getVelocityEngine()
VelocityEngine getVelocityEngine () private
References VelocityHelper.createVelocityEngine(), and VelocityHelper.servletContext.
Referenced by VelocityHelper.renderXHTML().
{
                 synchronized (servletContext) {
                         if (servletContext.getAttribute(VELOCITY_ENGINE) == null) {
                                 servletContext.setAttribute(VELOCITY_ENGINE, createVelocityEngine());
                         }
                         return (VelocityEngine) servletContext.getAttribute(VELOCITY_ENGINE);
                 }
         }
renderXHTML()
void renderXHTML (String templateName)
Renders a template using the template variables put into the velocity context.
References VelocityHelper.getVelocityEngine().
{
                 response.addHeader("Content-Type", "text/html; charset=utf-8");
                 response.addHeader("Cache-Control", "no-cache");
                 response.addHeader("Pragma", "no-cache");
                 try {
                         OutputStreamWriter writer = new OutputStreamWriter(response.getOutputStream(), "utf-8");
                         getVelocityEngine().mergeTemplate(templateName, velocityContext,
                                         writer);
                         writer.close();
                 } catch (Exception ex) {
                         throw new RuntimeException(ex);
                 }
         }
Member Data Documentation
response
final HttpServletResponse response private
Referenced by VelocityHelper.VelocityHelper().
servletContext
final ServletContext servletContext private
Referenced by VelocityHelper.getVelocityEngine(), and VelocityHelper.VelocityHelper().
VELOCITY_ENGINE
final String VELOCITY_ENGINE static private
Initial value:
=
                VelocityHelper.class.getName() + ".VELOCITY_ENGINE"
velocityContext
final Context velocityContext private
Referenced by VelocityHelper.getVelocityContext().