GeoPubby: VocabularyStore Class Reference
VocabularyStore Class Reference
A store for labels, descriptions and other metadata of classes and properties.
Classes
class CachedPropertyCollection
class I18nStringValueCache
class IntegerValueCache
class ValueCache
Public Member Functions
void setDataSource (DataSource dataSource)
Needs to be set before the instance is used! This is to allow creation of the store before the dataset is fully assembled.
void setDefaultLanguage (String defaultLanguage)
Literal getLabel (String iri, boolean preferPlural)
Literal getLabel (String iri, boolean preferPlural, String language)
Literal getCachedLabel (String iri, boolean preferPlural)
Returns a label, only taking into account previously cached values, without querying the data sources.
Literal getInverseLabel (String iri, boolean preferPlural)
Literal getInverseLabel (String iri, boolean preferPlural, String language)
Literal getDescription (String iri)
Literal getDescription (String iri, String language)
int getWeight (Property property, boolean forInverse)
Returns the conf:weight of the property.
CachedPropertyCollection getHighIndegreeProperties ()
CachedPropertyCollection getHighOutdegreeProperties ()
Private Attributes
DataSource dataSource
String defaultLanguage = "en"
final I18nStringValueCache labels = new I18nStringValueCache(RDFS.label, false)
final I18nStringValueCache pluralLabels = new I18nStringValueCache(CONF.pluralLabel, false)
final I18nStringValueCache inverseLabels = new I18nStringValueCache(RDFS.label, true)
final I18nStringValueCache inversePluralLabels = new I18nStringValueCache(CONF.pluralLabel, true)
final I18nStringValueCache descriptions = new I18nStringValueCache(RDFS.comment, false)
final IntegerValueCache weights = new IntegerValueCache(CONF.weight, false)
final IntegerValueCache inverseWeights = new IntegerValueCache(CONF.weight, true)
final CachedPropertyCollection highIndegreeProperties = new CachedPropertyCollection(CONF.HighIndregreeProperty)
final CachedPropertyCollection highOutdegreeProperties = new CachedPropertyCollection(CONF.HighOutdregreeProperty)
Detailed Description
A store for labels, descriptions and other metadata of classes and properties.
Values are retrieved from a DataSource and cached.
Member Function Documentation
getCachedLabel()
Literal getCachedLabel (String iri, boolean preferPlural)
Returns a label, only taking into account previously cached values, without querying the data sources.
Fast.
Parameters
iri IRI of the resource whose label to return
preferPlural Return conf:pluralLabel if available
Returns
The best label found, or null if none
References VocabularyStore.I18nStringValueCache.getCached().
Referenced by ResourceDescription.Value.getLabel().
{
                 if (preferPlural) {
                         Literal pluralLabel = pluralLabels.getCached(iri, defaultLanguage);
                         return pluralLabel == null ? getCachedLabel(iri, false) : pluralLabel;
                 }
                 return labels.getCached(iri, defaultLanguage);
         }
getDescription() [1/2]
Literal getDescription (String iri)
Referenced by ResourceDescription.ResourceProperty.getDescription(), and ResourceDescription.Value.getDescription().
{
                 return getDescription(iri, defaultLanguage);
         }
getDescription() [2/2]
Literal getDescription (String iri, String language)
References VocabularyStore.I18nStringValueCache.get().
{
                 return descriptions.get(iri, language);
         }
getHighIndegreeProperties()
CachedPropertyCollection getHighIndegreeProperties ()
References VocabularyStore.highIndegreeProperties.
Referenced by Dataset.buildDataSource(), and ResourceDescription.learnHighDegreeProperties().
{
                 return highIndegreeProperties;
         }
getHighOutdegreeProperties()
CachedPropertyCollection getHighOutdegreeProperties ()
References VocabularyStore.highOutdegreeProperties.
Referenced by Dataset.buildDataSource(), and ResourceDescription.learnHighDegreeProperties().
{
                 return highOutdegreeProperties;
         }
getInverseLabel() [1/2]
Literal getInverseLabel (String iri, boolean preferPlural)
Referenced by VocabularyStore.getInverseLabel(), and ResourceDescription.ResourceProperty.getInverseLabel().
{
                 return getInverseLabel(iri, preferPlural, defaultLanguage);
         }
getInverseLabel() [2/2]
Literal getInverseLabel (String iri, boolean preferPlural, String language)
References VocabularyStore.I18nStringValueCache.get(), and VocabularyStore.getInverseLabel().
{
                 if (preferPlural) {
                         Literal pluralLabel = inversePluralLabels.get(iri, language);
                         return pluralLabel == null ? getInverseLabel(iri, false, language) : pluralLabel;
                 }
                 return inverseLabels.get(iri, language);
         }
getLabel() [1/2]
Literal getLabel (String iri, boolean preferPlural)
Referenced by VocabularyStore.getLabel(), ResourceDescription.ResourceProperty.getLabel(), and ResourceDescription.Value.getLabel().
{
                 return getLabel(iri, preferPlural, defaultLanguage);
         }
getLabel() [2/2]
Literal getLabel (String iri, boolean preferPlural, String language)
References VocabularyStore.I18nStringValueCache.get(), and VocabularyStore.getLabel().
{
                 if (preferPlural) {
                         Literal pluralLabel = pluralLabels.get(iri, language);
                         return pluralLabel == null ? getLabel(iri, false, language) : pluralLabel;
                 }
                 return labels.get(iri, language);
         }
getWeight()
int getWeight (Property property, boolean forInverse)
Returns the conf:weight of the property.
The inverse's weight can be requested; if no inverse weight is specified then the "forward" weight is used.
Parameters
property The property whose weight to return
forInverse If true, look for the inverse's weight first
Returns
The conf:weight assigned to the property
References VocabularyStore.ValueCache< K >.get().
Referenced by ResourceDescription.ResourceProperty.compareTo().
{
                 Integer result = forInverse ? inverseWeights.get(property.getURI()) : null;
                 if (result == null) result = weights.get(property.getURI());
                 return result == null ? 0 : result.intValue();
         }
setDataSource()
void setDataSource (DataSource dataSource)
Needs to be set before the instance is used! This is to allow creation of the store before the dataset is fully assembled.
References VocabularyStore.dataSource.
Referenced by Configuration.Configuration().
{
                 this.dataSource = dataSource;
         }
setDefaultLanguage()
void setDefaultLanguage (String defaultLanguage)
References VocabularyStore.defaultLanguage.
Referenced by Configuration.Configuration().
{
                 this.defaultLanguage = defaultLanguage;
         }
Member Data Documentation
dataSource
DataSource dataSource private
Referenced by VocabularyStore.setDataSource().
defaultLanguage
String defaultLanguage = "en" private
Referenced by VocabularyStore.setDefaultLanguage().
descriptions
final I18nStringValueCache descriptions = new I18nStringValueCache(RDFS.comment, false) private
highIndegreeProperties
final CachedPropertyCollection highIndegreeProperties = new CachedPropertyCollection(CONF.HighIndregreeProperty) private
Referenced by VocabularyStore.getHighIndegreeProperties().
highOutdegreeProperties
final CachedPropertyCollection highOutdegreeProperties = new CachedPropertyCollection(CONF.HighOutdregreeProperty) private
Referenced by VocabularyStore.getHighOutdegreeProperties().
inverseLabels
final I18nStringValueCache inverseLabels = new I18nStringValueCache(RDFS.label, true) private
inversePluralLabels
final I18nStringValueCache inversePluralLabels = new I18nStringValueCache(CONF.pluralLabel, true) private
inverseWeights
final IntegerValueCache inverseWeights = new IntegerValueCache(CONF.weight, true) private
labels
final I18nStringValueCache labels = new I18nStringValueCache(RDFS.label, false) private
pluralLabels
final I18nStringValueCache pluralLabels = new I18nStringValueCache(CONF.pluralLabel, false) private
weights
final IntegerValueCache weights = new IntegerValueCache(CONF.weight, false) private