GeoPubby: HypermediaResource Class Reference
HypermediaResource Class Reference
The hypermedia interface to a specific resource managed by the server.
Public Member Functions
HypermediaResource (String relativeIRI, Configuration config)
String getRelativeIRI ()
String getAbsoluteIRI ()
String getPageURL ()
String getDataURL ()
String getPathPageURL (Property property)
String getPathDataURL (Property property)
String getInversePathPageURL (Property property)
String getInversePathDataURL (Property property)
Private Member Functions
String getPathURL (String urlPrefix, Property property)
Private Attributes
final String relativeIRI
final Configuration config
Detailed Description
The hypermedia interface to a specific resource managed by the server.
Author
Richard Cyganiak (richa.nosp@m.rd@c.nosp@m.ygani.nosp@m.ak.d.nosp@m.e)
Version
$Id$
Constructor & Destructor Documentation
HypermediaResource()
HypermediaResource (String relativeIRI, Configuration config)
References HypermediaResource.config, and HypermediaResource.relativeIRI.
{
                 this.relativeIRI = relativeIRI;
                 this.config = config;
         }
Member Function Documentation
getAbsoluteIRI()
String getAbsoluteIRI ()
Returns
the resource's IRI on the public Web server
References Configuration.getWebApplicationBaseURI(), Configuration.getWebResourcePrefix(), and HypermediaResource.relativeIRI.
{
                 return config.getWebApplicationBaseURI() +
                                 config.getWebResourcePrefix() +
                                 relativeIRI;
         }
getDataURL()
String getDataURL ()
Returns
the RDF document describing the resource on the public Web server
References Configuration.getWebApplicationBaseURI(), and HypermediaResource.relativeIRI.
{
                 return config.getWebApplicationBaseURI() + "data/" + relativeIRI;
         }
getInversePathDataURL()
String getInversePathDataURL (Property property)
References HypermediaResource.getPathURL().
{
                 return getPathURL("pathdata/-", property);
         }
getInversePathPageURL()
String getInversePathPageURL (Property property)
References HypermediaResource.getPathURL().
{
                 return getPathURL("pathpage/-", property);
         }
getPageURL()
String getPageURL ()
Returns
the HTML page describing the resource on the public Web server
References Configuration.getWebApplicationBaseURI(), and HypermediaResource.relativeIRI.
{
                 return config.getWebApplicationBaseURI() + "page/" + relativeIRI;
         }
getPathDataURL()
String getPathDataURL (Property property)
References HypermediaResource.getPathURL().
{
                 return getPathURL("pathdata/", property);
         }
getPathPageURL()
String getPathPageURL (Property property)
References HypermediaResource.getPathURL().
{
                 return getPathURL("pathpage/", property);
         }
getPathURL()
String getPathURL (String urlPrefix, Property property) private
References Configuration.getPrefixes(), and Configuration.getWebApplicationBaseURI().
Referenced by HypermediaResource.getInversePathDataURL(), HypermediaResource.getInversePathPageURL(), HypermediaResource.getPathDataURL(), and HypermediaResource.getPathPageURL().
{
                 if (config.getPrefixes().qnameFor(property.getURI()) == null) {
                         return null;
                 }
                 return config.getWebApplicationBaseURI() + urlPrefix +
                                 config.getPrefixes().qnameFor(property.getURI()) + "/" +
                                 relativeIRI;
         }
getRelativeIRI()
String getRelativeIRI ()
Returns
the resource's IRI, relative to the web server root
References HypermediaResource.relativeIRI.
{
                 return relativeIRI;
         }
Member Data Documentation
config
final Configuration config private
Referenced by HypermediaResource.HypermediaResource().
relativeIRI
final String relativeIRI private
Referenced by HypermediaResource.getAbsoluteIRI(), HypermediaResource.getDataURL(), HypermediaResource.getPageURL(), HypermediaResource.getRelativeIRI(), and HypermediaResource.HypermediaResource().