GeoPubby: IndexDataSource Class Reference
IndexDataSource Class Reference
A DataSource that wraps another data source and adds an index of the resources in that data source.
Public Member Functions
IndexDataSource (String indexIRI, DataSource wrapped)
boolean canDescribe (String absoluteIRI)
Indicates whether this data source may have some information about a given IRI.
Model describeResource (String iri)
Returns a subgraph of the data source describing one resource.
Model describeResource (String iri, String language)
Returns a subgraph of the data source describing one resource.
Map< Property, Integer > getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
Map< Property, Integer > getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Describe the index resource, and extract all the statements that have our property and the right subject/object.
List< Resource > getIndex ()
A list of IRI resources described in this data source.
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine< SearchRecord > getLabelIndex ()
Static Public Attributes
static final int MAX_INDEX_SIZE = 1000000
Private Attributes
final String indexIRI
final DataSource wrapped
Static Private Attributes
static final String SIOC_NS = "http://rdfs.org/sioc/ns#"
static final Property siocContainerOf
Detailed Description
A DataSource that wraps another data source and adds an index of the resources in that data source.
Constructor & Destructor Documentation
IndexDataSource()
IndexDataSource (String indexIRI, DataSource wrapped)
References IndexDataSource.indexIRI, and IndexDataSource.wrapped.
{
                 this.indexIRI = indexIRI;
                 this.wrapped = wrapped;
         }
Member Function Documentation
canDescribe()
boolean canDescribe (String absoluteIRI)
Indicates whether this data source may have some information about a given IRI.
If this is false, a client should not bother to call describeResource(String). This method is to allow for optimizations and should respond very fast.
It is also used by the UI to decide whether a click on a resource should go to a Pubby page (if true) or out to the Web (if false).
Parameters
absoluteIRI The IRI of a resource to be described
Returns
true if this data source might have something about it
Implements DataSource.
References DataSource.canDescribe().
{
                 return indexIRI.equals(absoluteIRI) || wrapped.canDescribe(absoluteIRI);
         }
describeResource() [1/2]
Model describeResource (String absoluteIRI)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
References DataSource.describeResource(), DataSource.getIndex(), IndexDataSource.SIOC_NS, and IndexDataSource.siocContainerOf.
Referenced by IndexDataSource.listPropertyValues().
{
                 if (!indexIRI.equals(iri)) return wrapped.describeResource(iri);
                 Model result = ModelFactory.createDefaultModel();
                 result.setNsPrefix("sioc", SIOC_NS);
                 result.setNsPrefix("rdfs", RDFS.getURI());
                 Resource index = result.createResource(indexIRI);
                 // TODO: Get label from the vocabulary store, and make it i18nable
                 index.addProperty(RDFS.label, "Index of Resources", "en");
                 for (Resource r: wrapped.getIndex()) {
                         index.addProperty(siocContainerOf, r);
                 }
                 return result;
         }
describeResource() [2/2]
Model describeResource (String absoluteIRI, String language)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
References DataSource.describeResource(), DataSource.getIndex(), IndexDataSource.SIOC_NS, and IndexDataSource.siocContainerOf.
{
                 if (!indexIRI.equals(iri)) return wrapped.describeResource(iri);
                 Model result = ModelFactory.createDefaultModel();
                 result.setNsPrefix("sioc", SIOC_NS);
                 result.setNsPrefix("rdfs", RDFS.getURI());
                 Resource index = result.createResource(indexIRI);
                 // TODO: Get label from the vocabulary store, and make it i18nable
                 index.addProperty(RDFS.label, "Index of Resources", language);
                 for (Resource r: wrapped.getIndex()) {
                         index.addProperty(siocContainerOf, r);
                 }
                 return result;
         }
getHighIndegreeProperties()
Map<Property, Integer> getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
If high-indegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-indegree properties with number of arcs for the resource
Implements DataSource.
References DataSource.getHighIndegreeProperties().
{
                 return wrapped.getHighIndegreeProperties(resourceIRI);
         }
getHighOutdegreeProperties()
Map<Property, Integer> getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
If high-outdegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-outdegree properties with number of arcs for the resource
Implements DataSource.
References DataSource.getHighOutdegreeProperties().
{
                 return wrapped.getHighOutdegreeProperties(resourceIRI);
         }
getIndex()
List<Resource> getIndex ()
A list of IRI resources described in this data source.
Ordering is implementation-defined. Usually a reasonable limit should be applied to the number of resources returned.
Implements DataSource.
References DataSource.getIndex().
{
                 // We could add the indexIRI as an additional resource here, but we
                 // don't want it to show up in the list of resources generated in
                 // describeResource(), and we don't want it turn an otherwise
                 // empty dataset into a non-empty one.
                 return wrapped.getIndex();
         }
getLabelIndex()
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine<SearchRecord> getLabelIndex ()
Implements DataSource.
References DataSource.getLabelIndex().
{
                 System.out.println("IndexDataSource: GetLabelIndex()");
                 return wrapped.getLabelIndex();
         }
listPropertyValues()
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Describe the index resource, and extract all the statements that have our property and the right subject/object.
Implements DataSource.
References IndexDataSource.describeResource(), and DataSource.listPropertyValues().
{
                 if (!indexIRI.equals(resourceIRI)) {
                         return wrapped.listPropertyValues(resourceIRI, property, isInverse);
                 }
                 Model all = describeResource(resourceIRI);
                 Resource r = all.getResource(resourceIRI);
                 StmtIterator it = isInverse
                                 ? all.listStatements(null, property, r)
                                 : all.listStatements(r, property, (RDFNode) null);
                 Model result = ModelFactory.createDefaultModel();
                 while (it.hasNext()) {
                         result.add(it.next());
                 }
                 return result;
         }
Member Data Documentation
indexIRI
final String indexIRI private
Referenced by IndexDataSource.IndexDataSource().
MAX_INDEX_SIZE
final int MAX_INDEX_SIZE = 1000000 static inherited
Referenced by ModelDataSource.getIndex(), RemoteSPARQLDataSource.getIndex(), ModelDataSource.getLabelIndex(), and RemoteSPARQLDataSource.getLabelIndex().
SIOC_NS
final String SIOC_NS = "http://rdfs.org/sioc/ns#" static private
Referenced by IndexDataSource.describeResource().
siocContainerOf
final Property siocContainerOf static private
Initial value:
=
                        ResourceFactory.createProperty(SIOC_NS + "container_of")
Referenced by IndexDataSource.describeResource().
wrapped
final DataSource wrapped private
Referenced by IndexDataSource.IndexDataSource().