GeoPubby: URIPrefixer Class Reference
URIPrefixer Class Reference
Helper class that splits URIs into prefix and local name according to a Jena PrefixMapping.
Public Member Functions
URIPrefixer (String uri, PrefixMapping prefixes)
URIPrefixer (Resource resource, PrefixMapping prefixes)
boolean hasPrefix ()
String getPrefix ()
String getLocalName ()
String toTurtle ()
Private Attributes
final Resource resource
final String prefix
final String localName
Detailed Description
Helper class that splits URIs into prefix and local name according to a Jena PrefixMapping.
Constructor & Destructor Documentation
URIPrefixer() [1/2]
URIPrefixer (String uri, PrefixMapping prefixes)
{
                 this(ResourceFactory.createResource(uri), prefixes);
         }
URIPrefixer() [2/2]
URIPrefixer (Resource resource, PrefixMapping prefixes)
References URIPrefixer.resource.
{
                 this.resource = resource;
                 String uri = resource.getURI();
                 Iterator<String> it = prefixes.getNsPrefixMap().keySet().iterator();
                 while (it.hasNext() && uri != null) {
                         String entryPrefix = it.next();
                         String entryURI = prefixes.getNsPrefixURI(entryPrefix);
                         if (uri.startsWith(entryURI)) {
                                 prefix = entryPrefix;
                                 localName = uri.substring(entryURI.length());
                                 return;
                         }
                 }
                 prefix = null;
                 localName = null;
         }
Member Function Documentation
getLocalName()
String getLocalName ()
References URIPrefixer.localName.
Referenced by ResourceDescription.Value.getDatatypeLabel(), ResourceDescription.ResourceProperty.getLocalName(), ResourceDescription.Value.getLocalName(), ResourceDescription.getTitle(), and URIPrefixer.toTurtle().
{
                 if (resource.isAnon()) return null;
                 if (localName == null) {
                         Matcher matcher = Pattern.compile("([^#/:?]+)[#/:?]*$").matcher(resource.getURI());
                         if (matcher.find()) {
                                 return matcher.group(1);
                         }
                         return "";      // Only happens if the URI contains only excluded chars
                 }
                 return localName;
         }
getPrefix()
String getPrefix ()
References URIPrefixer.prefix.
Referenced by ResourceDescription.ResourceProperty.getPrefix(), ResourceDescription.Value.getPrefix(), and URIPrefixer.toTurtle().
{
                 return prefix;
         }
hasPrefix()
boolean hasPrefix ()
Referenced by ResourceDescription.Value.getDatatypeLabel(), ResourceDescription.ResourceProperty.hasPrefix(), ResourceDescription.Value.hasPrefix(), and URIPrefixer.toTurtle().
{
                 return prefix != null;
         }
toTurtle()
String toTurtle ()
References URIPrefixer.getLocalName(), URIPrefixer.getPrefix(), and URIPrefixer.hasPrefix().
Referenced by ResourceDescription.Value.getDatatypeLabel().
{
                 if (resource.isAnon()) return "[]";
                 if (hasPrefix()) {
                         return getPrefix() + ":" + getLocalName();
                 }
                 return "<" + resource.getURI() + ">";
         }
Member Data Documentation
localName
final String localName private
Referenced by URIPrefixer.getLocalName().
prefix
final String prefix private
Referenced by URIPrefixer.getPrefix().
resource
final Resource resource private
Referenced by URIPrefixer.URIPrefixer().