GeoPubby: ResourceReader Class Reference
ResourceReader Class Reference abstract
Convenience superclass for classes that read properties of an RDF resource, intended for making the reading of configuration files easier.
Public Member Functions
ResourceReader (Resource resource)
Resource getSelf ()
Model getModel ()
boolean hasType (Resource class_)
boolean hasProperty (Property p)
Resource getResource (Property p)
Set< Resource > getResources (Property p)
Set< Property > getProperties (Property p)
String getIRI (Property p)
String getIRI (Property p, String defaultValue)
String getRequiredIRI (Property p)
Set< String > getIRIs (Property p)
String getString (Property p)
String getString (Property p, String defaultValue)
Set< String > getStrings (Property p)
boolean getBoolean (Property p, boolean defaultValue)
void requireExactlyOneOf (Property... properties)
Private Member Functions
void assertHasOneValue (Property p)
void assertResourceValue (Property p)
void assertResourceValue (Statement stmt)
void assertIRIValue (Property p)
void assertIRIValue (Statement stmt)
void assertLiteralValue (Property p)
void assertLiteralValue (Statement stmt)
void assertString (Statement stmt)
String pretty (RDFNode node)
String pretty (Statement stmt)
void raiseMissingProperty (Property p)
void raiseUnexpectedDatatype (String expectedDatatype, Statement stmt)
Private Attributes
final Resource resource
Detailed Description
Convenience superclass for classes that read properties of an RDF resource, intended for making the reading of configuration files easier.
Constructor & Destructor Documentation
ResourceReader()
ResourceReader (Resource resource)
References ResourceReader.resource.
{
                 this.resource = resource;
         }
Member Function Documentation
assertHasOneValue()
void assertHasOneValue (Property p) private
References ResourceReader.pretty().
Referenced by ResourceReader.getBoolean(), ResourceReader.getIRI(), ResourceReader.getResource(), and ResourceReader.getString().
{
                 StmtIterator it = resource.listProperties(p);
                 if (!it.hasNext()) {
                         throw new ConfigurationException("Missing property " + pretty(p) +
                                         " on resource " + pretty(resource));
                 }
                 it.next();
                 if (it.hasNext()) {
                         throw new ConfigurationException("Too many values for property " +
                                         pretty(p) + " on resource " + pretty(resource));
                 }
         }
assertIRIValue() [1/2]
void assertIRIValue (Property p) private
Referenced by ResourceReader.getIRI(), and ResourceReader.getIRIs().
{
                 assertIRIValue(resource.getProperty(p));
         }
assertIRIValue() [2/2]
void assertIRIValue (Statement stmt) private
References ResourceReader.pretty().
{
                 if (stmt.getObject().isLiteral()) {
                         throw new ConfigurationException(
                                         "Expected IRI object, found literal: " + pretty(stmt));
                 }
                 if (stmt.getObject().isAnon()) {
                         throw new ConfigurationException(
                                         "Expected IRI object, found blank node: " + pretty(stmt));
                 }
         }
assertLiteralValue() [1/2]
void assertLiteralValue (Property p) private
Referenced by ResourceReader.assertString(), and ResourceReader.getBoolean().
{
                 assertLiteralValue(resource.getProperty(p));
         }
assertLiteralValue() [2/2]
void assertLiteralValue (Statement stmt) private
References ResourceReader.pretty().
{
                 if (stmt.getObject().isURIResource()) {
                         throw new ConfigurationException(
                                         "Expected literal object, found IRI: " + pretty(stmt));
                 }
                 if (stmt.getObject().isAnon()) {
                         throw new ConfigurationException(
                                         "Expected literal object, found blank node: " + pretty(stmt));
                 }
         }
assertResourceValue() [1/2]
void assertResourceValue (Property p) private
Referenced by ResourceReader.getResource(), and ResourceReader.getResources().
{
                 assertResourceValue(resource.getProperty(p));
         }
assertResourceValue() [2/2]
void assertResourceValue (Statement stmt) private
References ResourceReader.pretty().
{
                 if (stmt.getObject().isLiteral()) {
                         throw new ConfigurationException(
                                         "Expected resource object, found literal: " + pretty(stmt));
                 }
         }
assertString()
void assertString (Statement stmt) private
References ResourceReader.assertLiteralValue(), and ResourceReader.raiseUnexpectedDatatype().
Referenced by ResourceReader.getString(), and ResourceReader.getStrings().
{
                 assertLiteralValue(stmt);
                 Literal value = stmt.getLiteral();
                 if (value.getDatatypeURI() == null ||
                                 XSD.xstring.getURI().equals(value.getDatatypeURI()) ||
                                 (RDF.getURI() + "langString").equals(value.getDatatypeURI())) {
                         return;
                 }
                 raiseUnexpectedDatatype("string", stmt);
         }
getBoolean()
boolean getBoolean (Property p, boolean defaultValue)
References ResourceReader.assertHasOneValue(), ResourceReader.assertLiteralValue(), and ResourceReader.raiseUnexpectedDatatype().
Referenced by Dataset.addSameAsStatements(), Configuration.showLabels(), Dataset.supportsIRIs(), and Dataset.supportsSPARQL11().
{
                 if (!resource.hasProperty(p)) {
                         return defaultValue;
                 }
                 assertHasOneValue(p);
                 assertLiteralValue(p);
                 Literal value = resource.getProperty(p).getLiteral();
                 if (XSD.xboolean.getURI().equals(value.getDatatypeURI())) {
                         return value.getBoolean();
                 }
                 if (value.getDatatypeURI() == null || XSD.xstring.getURI().equals(value.getDatatypeURI())) {
                         if ("true".equals(value.getString().toLowerCase())
                                         || "false".equals(value.getString().toLowerCase())) {
                                 return "true".equals(value.getString().toLowerCase());
                         }
                 }
                 raiseUnexpectedDatatype("xsd:boolean", resource.getProperty(p));
                 return false;
         }
getIRI() [1/2]
String getIRI (Property p)
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), Configuration.getProjectLink(), ResourceReader.getRequiredIRI(), and MetadataConfiguration.MetadataConfiguration().
{
                 return getIRI(p, null);
         }
getIRI() [2/2]
String getIRI (Property p, String defaultValue)
References ResourceReader.assertHasOneValue(), and ResourceReader.assertIRIValue().
{
                 if (!resource.hasProperty(p)) return defaultValue;
                 assertHasOneValue(p);
                 assertIRIValue(p);
                 return resource.getProperty(p).getResource().getURI();
         }
getIRIs()
Set<String> getIRIs (Property p)
References ResourceReader.assertIRIValue().
Referenced by Dataset.buildDataSource(), Configuration.Configuration(), Dataset.getBrowsableNamespaces(), and Configuration.getBrowsableNamespaces().
{
                 Set<String> result = new HashSet<String>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertIRIValue(stmt);
                         result.add(stmt.getResource().getURI());
                 }
                 return result;
         }
getModel()
Model getModel ()
Referenced by MetadataConfiguration.addMetadataFromTemplate(), Configuration.Configuration(), MetadataConfiguration.parsePlaceholder(), and ResourceReader.pretty().
{
                 return resource.getModel();
         }
getProperties()
Set<Property> getProperties (Property p)
References ResourceReader.getResources().
Referenced by Configuration.Configuration().
{
                 Set<Property> result = new HashSet<Property>();
                 for (Resource r: getResources(p)) {
                         result.add(r.as(Property.class));
                 }
                 return result;
         }
getRequiredIRI()
String getRequiredIRI (Property p)
References ResourceReader.getIRI(), and ResourceReader.raiseMissingProperty().
Referenced by Configuration.Configuration().
{
                 if (!resource.hasProperty(p)) {
                         raiseMissingProperty(p);
                 }
                 return getIRI(p);
         }
getResource()
Resource getResource (Property p)
References ResourceReader.assertHasOneValue(), and ResourceReader.assertResourceValue().
Referenced by MetadataConfiguration.MetadataConfiguration().
{
                 if (!resource.hasProperty(p)) return null;
                 assertHasOneValue(p);
                 assertResourceValue(p);
                 return resource.getProperty(p).getResource();
         }
getResources()
Set<Resource> getResources (Property p)
References ResourceReader.assertResourceValue().
Referenced by Configuration.Configuration(), and ResourceReader.getProperties().
{
                 Set<Resource> result = new HashSet<Resource>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertResourceValue(stmt);
                         result.add(stmt.getResource());
                 }
                 return result;
         }
getSelf()
Resource getSelf ()
References ResourceReader.resource.
Referenced by MetadataConfiguration.parsePlaceholder().
{
                 return resource;
         }
getString() [1/2]
String getString (Property p)
Referenced by Dataset.buildDataSource(), Configuration.getDefaultLanguage(), Configuration.getProjectName(), and Configuration.getWebResourcePrefix().
{
                 return getString(p, null);
         }
getString() [2/2]
String getString (Property p, String defaultValue)
References ResourceReader.assertHasOneValue(), and ResourceReader.assertString().
{
                 if (!resource.hasProperty(p)) {
                         return defaultValue;
                 }
                 assertHasOneValue(p);
                 assertString(resource.getProperty(p));
                 return resource.getProperty(p).getString();
         }
getStrings()
Set<String> getStrings (Property p)
References ResourceReader.assertString().
Referenced by Dataset.buildDataSource().
{
                 Set<String> result = new HashSet<String>();
                 StmtIterator it = resource.listProperties(p);
                 while (it.hasNext()) {
                         Statement stmt = it.next();
                         assertString(stmt);
                         result.add(stmt.getString());
                 }
                 return result;
         }
hasProperty()
boolean hasProperty (Property p)
Referenced by Dataset.buildDataSource(), Configuration.buildDataSource(), and Configuration.Configuration().
{
                 return resource.hasProperty(p);
         }
hasType()
boolean hasType (Resource class_)
Referenced by Dataset.buildDataSource().
{
                 return resource.hasProperty(RDF.type, class_);
         }
pretty() [1/2]
String pretty (RDFNode node) private
References ResourceReader.getModel().
Referenced by ResourceReader.assertHasOneValue(), ResourceReader.assertIRIValue(), ResourceReader.assertLiteralValue(), ResourceReader.assertResourceValue(), ResourceReader.pretty(), ResourceReader.raiseMissingProperty(), ResourceReader.raiseUnexpectedDatatype(), and ResourceReader.requireExactlyOneOf().
{
                 if (node.isAnon()) return "[]";
                 if (node.isURIResource()) {
                         Resource r = node.asResource();
                         if (getModel().qnameFor(r.getURI()) == null) {
                                 return "<" + r.getURI() + ">";
                         }
                         return getModel().qnameFor(r.getURI());
                 }
                 return PrintUtil.print(node);
         }
pretty() [2/2]
String pretty (Statement stmt) private
References ResourceReader.pretty().
{
                 return pretty(stmt.getSubject()) + " " + pretty(stmt.getPredicate())
                                 + " " + pretty(stmt.getObject()) + ".";
         }
raiseMissingProperty()
void raiseMissingProperty (Property p) private
References ResourceReader.pretty().
Referenced by ResourceReader.getRequiredIRI().
{
                 throw new ConfigurationException("Missing property " +
                                 pretty(p) + " on resource " + pretty(resource));
         }
raiseUnexpectedDatatype()
void raiseUnexpectedDatatype (String expectedDatatype, Statement stmt) private
References ResourceReader.pretty().
Referenced by ResourceReader.assertString(), and ResourceReader.getBoolean().
{
                 throw new ConfigurationException(
                                 "Expected " + expectedDatatype +
                                 " object, found other datatype: " +
                                 pretty(stmt));
         }
requireExactlyOneOf()
void requireExactlyOneOf (Property... properties)
References ResourceReader.pretty().
Referenced by Dataset.buildDataSource().
{
                 Property found = null;
                 boolean first = true;
                 StringBuilder s = new StringBuilder();
                 for (Property p: properties) {
                         if (resource.hasProperty(p)) {
                                 if (found == null) {
                                         found = p;
                                 } else {
                                         throw new ConfigurationException("Can't have both " +
                                                         pretty(found) + " and " + pretty(p) +
                                                         " on resource " + pretty(resource));
                                 }
                         }
                         if (!first) {
                                 s.append(", ");
                         }
                         s.append(pretty(p));
                         first = false;
                 }
                 if (found == null) {
                         throw new ConfigurationException("One of " + s.toString() +
                                         " required on resource " + pretty(resource));
                 }
         }
Member Data Documentation
resource
final Resource resource private
Referenced by ResourceReader.getSelf(), and ResourceReader.ResourceReader().