GeoPubby: ContentTypeNegotiator.Negotiation Class Reference
ContentTypeNegotiator.Negotiation Class Reference
Package Functions
Negotiation (List< MediaRangeSpec > ranges)
MediaRangeSpec negotiate ()
Private Member Functions
void evaluateVariantAlias (MediaRangeSpec variant, MediaRangeSpec isAliasFor)
void evaluateVariant (MediaRangeSpec variant)
void evaluateDefaultVariant (MediaRangeSpec variant)
Private Attributes
final List< MediaRangeSpec > ranges
MediaRangeSpec bestMatchingVariant = null
MediaRangeSpec bestDefaultVariant = null
double bestMatchingQuality = 0
double bestDefaultQuality = 0
Constructor & Destructor Documentation
Negotiation()
Negotiation (List< MediaRangeSpec > ranges) package
{
                         this.ranges = ranges;
                 }
Member Function Documentation
evaluateDefaultVariant()
void evaluateDefaultVariant (MediaRangeSpec variant) private
References MediaRangeSpec.getQuality().
{
                         if (variant.getQuality() > bestDefaultQuality) {
                                 bestDefaultVariant = variant;
                                 bestDefaultQuality = 0.00001 * variant.getQuality();
                         }
                 }
evaluateVariant()
void evaluateVariant (MediaRangeSpec variant) private
{
                         evaluateVariantAlias(variant, variant);
                 }
evaluateVariantAlias()
void evaluateVariantAlias (MediaRangeSpec variant, MediaRangeSpec isAliasFor) private
References MediaRangeSpec.getBestMatch(), and MediaRangeSpec.getQuality().
{
                         if (variant.getBestMatch(ranges) == null) return;
                         double q = variant.getBestMatch(ranges).getQuality();
                         if (q * variant.getQuality() > bestMatchingQuality) {
                                 bestMatchingVariant = isAliasFor;
                                 bestMatchingQuality = q * variant.getQuality();
                         }
                 }
negotiate()
MediaRangeSpec negotiate () package
References ContentTypeNegotiator.VariantSpec.getAliases(), ContentTypeNegotiator.VariantSpec.getMediaType(), and ContentTypeNegotiator.VariantSpec.isDefault.
Referenced by ContentTypeNegotiator.getBestMatch().
{
                         Iterator<VariantSpec> it = variantSpecs.iterator();
                         while (it.hasNext()) {
                                 VariantSpec variant = it.next();
                                 if (variant.isDefault) {
                                         evaluateDefaultVariant(variant.getMediaType());
                                 }
                                 evaluateVariant(variant.getMediaType());
                                 Iterator<MediaRangeSpec> aliasIt = variant.getAliases().iterator();
                                 while (aliasIt.hasNext()) {
                                         MediaRangeSpec alias = (MediaRangeSpec) aliasIt.next();
                                         evaluateVariantAlias(alias, variant.getMediaType());
                                 }
                         }
                         return (bestMatchingVariant == null) ? bestDefaultVariant : bestMatchingVariant;
                 }
Member Data Documentation
bestDefaultQuality
double bestDefaultQuality = 0 private
bestDefaultVariant
MediaRangeSpec bestDefaultVariant = null private
bestMatchingQuality
double bestMatchingQuality = 0 private
bestMatchingVariant
MediaRangeSpec bestMatchingVariant = null private
ranges
final List<MediaRangeSpec> ranges private