GeoPubby: ModelWriter Class Reference
ModelWriter Class Reference
A model class for exporting RDF in several downlift formats.
Public Member Functions
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Detailed Description
A model class for exporting RDF in several downlift formats.
Member Function Documentation
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException
Reimplemented in LDWriter, YAMLWriter, XLSXWriter, XLSWriter, WKTWriter, WKBWriterr, TWKBWriterr, TopoJSONWriter, SVGWriter, SHPWriter, OSMWriter, OSMLinkWriter, OpenLocationCodeWriter, MapMLWriter, LatLonTextWriter, KMLWriter, GRASSVectorASCIIWriter, GPXWriter, GoogleMapsLinkWriter, GMLWriter, GeoURIWriter, GeoJSONWriterr, GeoJSONLDWriter, GeoHashWriter, GeobufWriter, EXIJSONWriter, EWKTWriter, ESRIJSONWriter, CSVWriter, TLPWriter, TGFWriter, RDFEXIWriter, HexTuplesWriter, GXLWriter, GraphMLWriter, GMLWriter, GEXFWriter, GDFWriter, CypherWriter, JSONPWriter, XYZASCIIWriter, X3DWriter, WKBRasterWriter, and CoverageJSONWriter.
{
                 ExtendedIterator<Resource> it=model.
                                 listResourcesWithProperty(GEO.HASGEOMETRY);
                 usedProperty=GEO.HASGEOMETRY;
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P_LAT);
                         usedProperty=GEO.P_LAT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.HASGEOMETRY);
                         usedProperty=GEO.HASGEOMETRY;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.GEORSSPOINT);
                         usedProperty=GEO.GEORSSPOINT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P625);
                         usedProperty=GEO.P625;
                 }
                 return it;
         }
References GEO.GEORSSPOINT, GEO.HASGEOMETRY, GEO.P625, GEO.P_LAT, and ModelWriter.usedProperty.
Referenced by ModelResponse.doResponseModel().
Member Data Documentation
reader
WKTReader reader =new WKTReader() protected
Referenced by GeoModelWriter.handleGeometry(), X3DWriter.write(), XYZASCIIWriter.write(), CSVWriter.write(), EWKTWriter.write(), GeoURIWriter.write(), GoogleMapsLinkWriter.write(), GPXWriter.write(), OSMLinkWriter.write(), TWKBWriterr.write(), WKBWriterr.write(), WKTWriter.write(), XLSWriter.write(), XLSXWriter.write(), and LDWriter.write().
usedProperty
Property usedProperty =null protected
Referenced by ModelWriter.write(), GMLWriter.write(), GPXWriter.write(), KMLWriter.write(), MapMLWriter.write(), and OSMWriter.write().