GeoPubby: CoverageModelWriter Class Reference
CoverageModelWriter Class Reference
Public Member Functions
Tuple< Boolean, String > handleCoverage (Statement curst, Resource ind, Model model)
ExtendedIterator< Resource > write (Model model, HttpServletResponse response) throws IOException
Protected Attributes
Property usedProperty =null
WKTReader reader =new WKTReader()
Package Attributes
GridCoverage cov
Member Function Documentation
handleCoverage()
Tuple<Boolean,String> handleCoverage (Statement curst, Resource ind, Model model)
{
                 boolean handled=false;
                 String type="coverage";
                 if(COV.ASCOVERAGEJSON.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }else if(COV.ASGMLCOV.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }else if(COV.ASRASTWKB.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }else if(COV.ASHEXRASTWKB.getURI().equals(curst.getPredicate().getURI().toString())) {
                         handled=true;
                 }
                 return new Tuple<Boolean,String>(handled,type);
         }
References COV.ASCOVERAGEJSON, COV.ASGMLCOV, COV.ASHEXRASTWKB, and COV.ASRASTWKB.
write()
ExtendedIterator<Resource> write (Model model, HttpServletResponse response) throws IOException inherited
Reimplemented in LDWriter, YAMLWriter, XLSXWriter, XLSWriter, WKTWriter, WKBWriterr, TWKBWriterr, TopoJSONWriter, SVGWriter, SHPWriter, OSMWriter, OSMLinkWriter, OpenLocationCodeWriter, MapMLWriter, LatLonTextWriter, KMLWriter, GRASSVectorASCIIWriter, GPXWriter, GoogleMapsLinkWriter, GMLWriter, GeoURIWriter, GeoJSONWriterr, GeoJSONLDWriter, GeoHashWriter, GeobufWriter, EXIJSONWriter, EWKTWriter, ESRIJSONWriter, CSVWriter, TLPWriter, TGFWriter, RDFEXIWriter, HexTuplesWriter, GXLWriter, GraphMLWriter, GMLWriter, GEXFWriter, GDFWriter, CypherWriter, JSONPWriter, XYZASCIIWriter, X3DWriter, WKBRasterWriter, and CoverageJSONWriter.
{
                 ExtendedIterator<Resource> it=model.
                                 listResourcesWithProperty(GEO.HASGEOMETRY);
                 usedProperty=GEO.HASGEOMETRY;
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P_LAT);
                         usedProperty=GEO.P_LAT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.HASGEOMETRY);
                         usedProperty=GEO.HASGEOMETRY;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.GEORSSPOINT);
                         usedProperty=GEO.GEORSSPOINT;
                 }
                 if(!it.hasNext()) {
                         usedProperty=null;
                         it.close();
                         it=model.listResourcesWithProperty(GEO.P625);
                         usedProperty=GEO.P625;
                 }
                 return it;
         }
References GEO.GEORSSPOINT, GEO.HASGEOMETRY, GEO.P625, GEO.P_LAT, and ModelWriter.usedProperty.
Referenced by ModelResponse.doResponseModel().
Member Data Documentation
cov
GridCoverage cov package
reader
WKTReader reader =new WKTReader() protected inherited
Referenced by GeoModelWriter.handleGeometry(), X3DWriter.write(), XYZASCIIWriter.write(), CSVWriter.write(), EWKTWriter.write(), GeoURIWriter.write(), GoogleMapsLinkWriter.write(), GPXWriter.write(), OSMLinkWriter.write(), TWKBWriterr.write(), WKBWriterr.write(), WKTWriter.write(), XLSWriter.write(), XLSXWriter.write(), and LDWriter.write().
usedProperty
Property usedProperty =null protected inherited
Referenced by ModelWriter.write(), GMLWriter.write(), GPXWriter.write(), KMLWriter.write(), MapMLWriter.write(), and OSMWriter.write().