GeoPubby: CONF Class Reference
CONF Class Reference
Static Public Attributes
static final String NS = "http://richard.cyganiak.de/2007/pubby/config.rdf#"
static final Resource Configuration = m.createResource(NS + "Configuration")
static final Property projectName = m.createProperty(NS + "projectName")
static final Property projectHomepage = m.createProperty(NS + "projectHomepage")
static final Property webBase = m.createProperty(NS + "webBase")
static final Property usePrefixesFrom = m.createProperty(NS + "usePrefixesFrom")
static final Property labelProperty = m.createProperty(NS + "labelProperty")
static final Property commentProperty = m.createProperty(NS + "commentProperty")
static final Property imageProperty = m.createProperty(NS + "imageProperty")
static final Property defaultLanguage = m.createProperty(NS + "defaultLanguage")
static final Property indexResource = m.createProperty(NS + "indexResource")
static final Property dataset = m.createProperty(NS + "dataset")
static final Property showLabels = m.createProperty(NS + "showLabels")
static final Property loadVocabulary = m.createProperty(NS + "loadVocabulary")
static final Resource AnnotationProvider = m.createResource(NS + "AnnotationProvider")
static final Property datasetBase = m.createProperty(NS + "datasetBase")
static final Property datasetURIPattern = m.createProperty(NS + "datasetURIPattern")
static final Property webResourcePrefix = m.createProperty(NS + "webResourcePrefix")
static final Property supportsIRIs = m.createProperty(NS + "supportsIRIs")
static final Property addSameAsStatements = m.createProperty(NS + "addSameAsStatements")
static final Property sparqlEndpoint = m.createProperty(NS + "sparqlEndpoint")
static final Property sparqlDefaultGraph = m.createProperty(NS + "sparqlDefaultGraph")
static final Property supportsSPARQL11 = m.createProperty(NS + "supportsSPARQL11")
static final Property loadRDF = m.createProperty(NS + "loadRDF")
static final Property rdfDocumentMetadata = m.createProperty(NS + "rdfDocumentMetadata")
static final Property metadataTemplate = m.createProperty(NS + "metadataTemplate")
static final Property contentType = m.createProperty(NS + "contentType")
static final Property resourceDescriptionQuery = m.createProperty(NS + "resourceDescriptionQuery")
static final Property propertyListQuery = m.createProperty(NS + "propertyListQuery")
static final Property inversePropertyListQuery = m.createProperty(NS + "inversePropertyListQuery")
static final Property anonymousPropertyDescriptionQuery = m.createProperty(NS + "anonymousPropertyDescriptionQuery")
static final Property anonymousInversePropertyDescriptionQuery
static final Property browsableNamespace = m.createProperty(NS + "browsableNamespace")
static final Property queryParamSelect = m.createProperty(NS + "queryParamSelect")
static final Property queryParamGraph = m.createProperty(NS + "queryParamGraph")
static final Property wdImage =m.createProperty("http://www.wikidata.org/prop/direct/P18")
static final Property weight = m.createProperty(NS + "weight")
static final Property pluralLabel = m.createProperty(NS + "pluralLabel")
static final Resource HighOutdregreeProperty = m.createResource(NS + "HighOutdegreeProperty")
static final Resource HighIndregreeProperty = m.createResource(NS + "HighIndegreeProperty")
Static Private Attributes
static final Model m = ModelFactory.createDefaultModel()
Member Data Documentation
addSameAsStatements
final Property addSameAsStatements = m.createProperty(NS + "addSameAsStatements") static
Referenced by Dataset.addSameAsStatements().
AnnotationProvider
final Resource AnnotationProvider = m.createResource(NS + "AnnotationProvider") static
Referenced by Dataset.buildDataSource(), and Configuration.Configuration().
anonymousInversePropertyDescriptionQuery
final Property anonymousInversePropertyDescriptionQuery static
Initial value:
= m.createProperty(NS
                        + "anonymousInversePropertyDescriptionQuery")
Referenced by Dataset.buildDataSource().
anonymousPropertyDescriptionQuery
final Property anonymousPropertyDescriptionQuery = m.createProperty(NS + "anonymousPropertyDescriptionQuery") static
Referenced by Dataset.buildDataSource().
browsableNamespace
final Property browsableNamespace = m.createProperty(NS + "browsableNamespace") static
Referenced by Dataset.getBrowsableNamespaces(), and Configuration.getBrowsableNamespaces().
commentProperty
final Property commentProperty = m.createProperty(NS + "commentProperty") static
Referenced by Configuration.Configuration().
Configuration
final Resource Configuration = m.createResource(NS + "Configuration") static
Referenced by Configuration.create().
contentType
final Property contentType = m.createProperty(NS + "contentType") static
Referenced by Dataset.buildDataSource().
dataset
final Property dataset = m.createProperty(NS + "dataset") static
Referenced by Configuration.Configuration(), and MetadataConfiguration.parsePlaceholder().
datasetBase
final Property datasetBase = m.createProperty(NS + "datasetBase") static
Referenced by Dataset.buildDataSource().
datasetURIPattern
final Property datasetURIPattern = m.createProperty(NS + "datasetURIPattern") static
Referenced by Dataset.buildDataSource().
defaultLanguage
final Property defaultLanguage = m.createProperty(NS + "defaultLanguage") static
Referenced by Configuration.getDefaultLanguage().
HighIndregreeProperty
final Resource HighIndregreeProperty = m.createResource(NS + "HighIndegreeProperty") static
HighOutdregreeProperty
final Resource HighOutdregreeProperty = m.createResource(NS + "HighOutdegreeProperty") static
imageProperty
final Property imageProperty = m.createProperty(NS + "imageProperty") static
Referenced by Configuration.Configuration().
indexResource
final Property indexResource = m.createProperty(NS + "indexResource") static
Referenced by Configuration.buildDataSource(), and Configuration.Configuration().
inversePropertyListQuery
final Property inversePropertyListQuery = m.createProperty(NS + "inversePropertyListQuery") static
Referenced by Dataset.buildDataSource().
labelProperty
final Property labelProperty = m.createProperty(NS + "labelProperty") static
Referenced by Configuration.Configuration().
loadRDF
final Property loadRDF = m.createProperty(NS + "loadRDF") static
Referenced by Dataset.buildDataSource(), and Configuration.Configuration().
loadVocabulary
final Property loadVocabulary = m.createProperty(NS + "loadVocabulary") static
Referenced by Configuration.Configuration().
m
final Model m = ModelFactory.createDefaultModel() static private
metadataTemplate
final Property metadataTemplate = m.createProperty(NS + "metadataTemplate") static
Referenced by MetadataConfiguration.MetadataConfiguration().
NS
final String NS = "http://richard.cyganiak.de/2007/pubby/config.rdf#" static
Referenced by Configuration.Configuration(), and MetadataConfiguration.parsePlaceholder().
pluralLabel
final Property pluralLabel = m.createProperty(NS + "pluralLabel") static
projectHomepage
final Property projectHomepage = m.createProperty(NS + "projectHomepage") static
Referenced by Configuration.getProjectLink().
projectName
final Property projectName = m.createProperty(NS + "projectName") static
Referenced by Configuration.getProjectName().
propertyListQuery
final Property propertyListQuery = m.createProperty(NS + "propertyListQuery") static
Referenced by Dataset.buildDataSource().
queryParamGraph
final Property queryParamGraph = m.createProperty(NS + "queryParamGraph") static
Referenced by Dataset.buildDataSource().
queryParamSelect
final Property queryParamSelect = m.createProperty(NS + "queryParamSelect") static
Referenced by Dataset.buildDataSource().
rdfDocumentMetadata
final Property rdfDocumentMetadata = m.createProperty(NS + "rdfDocumentMetadata") static
Referenced by MetadataConfiguration.addCustomMetadata(), and MetadataConfiguration.MetadataConfiguration().
resourceDescriptionQuery
final Property resourceDescriptionQuery = m.createProperty(NS + "resourceDescriptionQuery") static
Referenced by Dataset.buildDataSource().
showLabels
final Property showLabels = m.createProperty(NS + "showLabels") static
Referenced by Configuration.showLabels().
sparqlDefaultGraph
final Property sparqlDefaultGraph = m.createProperty(NS + "sparqlDefaultGraph") static
Referenced by Dataset.buildDataSource().
sparqlEndpoint
final Property sparqlEndpoint = m.createProperty(NS + "sparqlEndpoint") static
Referenced by Dataset.buildDataSource().
supportsIRIs
final Property supportsIRIs = m.createProperty(NS + "supportsIRIs") static
Referenced by Dataset.supportsIRIs().
supportsSPARQL11
final Property supportsSPARQL11 = m.createProperty(NS + "supportsSPARQL11") static
Referenced by Dataset.supportsSPARQL11().
usePrefixesFrom
final Property usePrefixesFrom = m.createProperty(NS + "usePrefixesFrom") static
Referenced by Configuration.Configuration().
wdImage
final Property wdImage =m.createProperty("http://www.wikidata.org/prop/direct/P18") static
Referenced by Configuration.Configuration().
webBase
final Property webBase = m.createProperty(NS + "webBase") static
Referenced by Configuration.Configuration().
webResourcePrefix
final Property webResourcePrefix = m.createProperty(NS + "webResourcePrefix") static
Referenced by Configuration.getWebResourcePrefix().
weight
final Property weight = m.createProperty(NS + "weight") static