GeoPubby: ResourceDescription.PropertyBuilder Class Reference
ResourceDescription.PropertyBuilder Class Reference
Package Functions
PropertyBuilder (Property predicate, boolean isInverse, VocabularyStore vocabularyStore)
void addValue (RDFNode valueNode)
void addHighDegreeArcs (int count)
ResourceProperty toProperty ()
Private Attributes
final Property predicate
final boolean isInverse
final List< Value > values = new ArrayList<Value>()
final List< ResourceDescription > blankNodeDescriptions
int highDegreeArcCount = 0
VocabularyStore vocabularyStore
Constructor & Destructor Documentation
PropertyBuilder()
PropertyBuilder (Property predicate, boolean isInverse, VocabularyStore vocabularyStore) package
References ResourceDescription.ResourceProperty.isInverse(), ResourceDescription.ResourceProperty.predicate, and ResourceDescription.ResourceProperty.vocabularyStore.
{
                         this.predicate = predicate;
                         this.isInverse = isInverse;
                         this.vocabularyStore = vocabularyStore;
                 }
Member Function Documentation
addHighDegreeArcs()
void addHighDegreeArcs (int count) package
{
                         highDegreeArcCount += count;
                 }
addValue()
void addValue (RDFNode valueNode) package
References ResourceDescription.config, ResourceDescription.getModel(), and ResourceDescription.ResourceDescription().
{
                         if (valueNode.isAnon()) {
                                 blankNodeDescriptions.add(new ResourceDescription(
                                                 valueNode.asResource(), getModel(), config));
                                 return;
                         }
                         values.add(new Value(valueNode, predicate, vocabularyStore));
                 }
toProperty()
ResourceProperty toProperty () package
References ResourceDescription.ResourceProperty.ResourceProperty().
Referenced by ResourceDescription.buildProperties().
{
                         Collections.sort(values);
                         return new ResourceProperty(predicate, isInverse, values,
                                         blankNodeDescriptions, highDegreeArcCount, vocabularyStore);
                 }
Member Data Documentation
blankNodeDescriptions
final List<ResourceDescription> blankNodeDescriptions private
Initial value:
=
                                new ArrayList<ResourceDescription>()
highDegreeArcCount
int highDegreeArcCount = 0 private
isInverse
final boolean isInverse private
predicate
final Property predicate private
values
final List<Value> values = new ArrayList<Value>() private
vocabularyStore
VocabularyStore vocabularyStore private