GeoPubby: RewrittenDataSource Class Reference
RewrittenDataSource Class Reference
Wraps a DataSource by applying a IRIRewriter.
Public Member Functions
RewrittenDataSource (DataSource original, IRIRewriter rewriter)
RewrittenDataSource (DataSource original, IRIRewriter rewriter, boolean addSameAsStatements)
boolean canDescribe (String absoluteIRI)
Indicates whether this data source may have some information about a given IRI.
Model describeResource (String iri)
Returns a subgraph of the data source describing one resource.
Map< Property, Integer > getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
Map< Property, Integer > getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Returns a subgraph of the data source.
List< Resource > getIndex ()
A list of IRI resources described in this data source.
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine< SearchRecord > getLabelIndex ()
Model describeResource (String absoluteIRI, String language)
Returns a subgraph of the data source describing one resource.
Static Public Attributes
static final int MAX_INDEX_SIZE = 1000000
Private Member Functions
boolean isOriginalIRI (String absoluteIRI)
void addSameAsStatement (Model model, String rewrittenIRI)
Private Attributes
final DataSource original
final IRIRewriter rewriter
final boolean addSameAs
Detailed Description
Wraps a DataSource by applying a IRIRewriter.
The result is a data source that contains the same data as the original, but with all IRIs replaced according to the rewriter.
Optionally, may add owl:sameAs statements to indicate that the rewritten and original IRIs identify the same entity.
Constructor & Destructor Documentation
RewrittenDataSource() [1/2]
RewrittenDataSource (DataSource original, IRIRewriter rewriter)
References RewrittenDataSource.original, and RewrittenDataSource.rewriter.
{
                 this(original, rewriter, false);
         }
RewrittenDataSource() [2/2]
RewrittenDataSource (DataSource original, IRIRewriter rewriter, boolean addSameAsStatements)
References RewrittenDataSource.original, and RewrittenDataSource.rewriter.
{
                 this.original = original;
                 this.rewriter = rewriter;
                 this.addSameAs = addSameAsStatements;
         }
Member Function Documentation
addSameAsStatement()
void addSameAsStatement (Model model, String rewrittenIRI) private
References ModelUtil.addNSIfUndefined(), and IRIRewriter.unrewrite().
Referenced by RewrittenDataSource.describeResource(), and RewrittenDataSource.listPropertyValues().
{
                 String originalIRI = rewriter.unrewrite(rewrittenIRI);
                 Resource rewritten = model.getResource(rewrittenIRI);
                 Resource unrewritten = model.getResource(originalIRI);
                 if (rewritten.equals(unrewritten)) return;
                 rewritten.addProperty(OWL.sameAs, unrewritten);
                 ModelUtil.addNSIfUndefined(model, "owl", OWL.NS);
         }
canDescribe()
boolean canDescribe (String absoluteIRI)
Indicates whether this data source may have some information about a given IRI.
If this is false, a client should not bother to call describeResource(String). This method is to allow for optimizations and should respond very fast.
It is also used by the UI to decide whether a click on a resource should go to a Pubby page (if true) or out to the Web (if false).
Parameters
absoluteIRI The IRI of a resource to be described
Returns
true if this data source might have something about it
Implements DataSource.
References DataSource.canDescribe(), RewrittenDataSource.isOriginalIRI(), and IRIRewriter.unrewrite().
{
                 if (isOriginalIRI(absoluteIRI)) {
                         // According to our logic, the original namespace is empty
                         // because we transplanted it. It only contains a sameAs
                         // statements for every resource in it.
                         return addSameAs && original.canDescribe(absoluteIRI);
                 }
                 return original.canDescribe(rewriter.unrewrite(absoluteIRI));
         }
describeResource() [1/2]
Model describeResource (String absoluteIRI)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
References RewrittenDataSource.addSameAsStatement(), DataSource.describeResource(), ModelUtil.EMPTY_MODEL, RewrittenDataSource.isOriginalIRI(), IRIRewriter.rewrite(), and IRIRewriter.unrewrite().
{
                 if (isOriginalIRI(iri)) {
                         // According to our logic, the original namespace is empty
                         // because we transplanted it. It only contains a sameAs
                         // statements for every resource in it.
                         if (!addSameAs || original.describeResource(iri).isEmpty()) {
                                 return ModelUtil.EMPTY_MODEL;
                         }
                         Model result = ModelFactory.createDefaultModel();
                         addSameAsStatement(result, rewriter.rewrite(iri));
                         return result;
                 }
                 // Normal case -- a rewritten IRI
                 Model result = rewriter.rewrite(
                                 original.describeResource(
                                                 rewriter.unrewrite(iri)));
                 if (addSameAs && !result.isEmpty()) {
                         addSameAsStatement(result, iri);
                 }
                 return result;
         }
describeResource() [2/2]
Model describeResource (String absoluteIRI, String language)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
{
                 // TODO Auto-generated method stub
                 return null;
         }
getHighIndegreeProperties()
Map<Property, Integer> getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
If high-indegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-indegree properties with number of arcs for the resource
Implements DataSource.
References DataSource.getHighIndegreeProperties(), RewrittenDataSource.isOriginalIRI(), IRIRewriter.rewrite(), and IRIRewriter.unrewrite().
{
                 if (isOriginalIRI(resourceIRI)) return null;
                 return rewriter.rewrite(
                                 original.getHighIndegreeProperties(
                                                 rewriter.unrewrite(resourceIRI)));
         }
getHighOutdegreeProperties()
Map<Property, Integer> getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
If high-outdegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-outdegree properties with number of arcs for the resource
Implements DataSource.
References DataSource.getHighOutdegreeProperties(), RewrittenDataSource.isOriginalIRI(), IRIRewriter.rewrite(), and IRIRewriter.unrewrite().
{
                 if (isOriginalIRI(resourceIRI)) return null;
                 return rewriter.rewrite(
                                 original.getHighOutdegreeProperties(
                                                 rewriter.unrewrite(resourceIRI)));
         }
getIndex()
List<Resource> getIndex ()
A list of IRI resources described in this data source.
Ordering is implementation-defined. Usually a reasonable limit should be applied to the number of resources returned.
Implements DataSource.
References DataSource.getIndex(), and IRIRewriter.rewrite().
{
                 List<Resource> originalIndex = original.getIndex();
                 List<Resource> result = new ArrayList<Resource>(originalIndex.size());
                 for (Resource r: originalIndex) {
                         result.add(rewriter.rewrite(r));
                 }
                 return result;
         }
getLabelIndex()
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine<SearchRecord> getLabelIndex ()
Implements DataSource.
References DataSource.getLabelIndex().
{
                 System.out.println("RewrittenDataSource: GetLabelIndex()");
                 return original.getLabelIndex();
         }
isOriginalIRI()
boolean isOriginalIRI (String absoluteIRI) private
References IRIRewriter.unrewrite().
Referenced by RewrittenDataSource.canDescribe(), RewrittenDataSource.describeResource(), RewrittenDataSource.getHighIndegreeProperties(), RewrittenDataSource.getHighOutdegreeProperties(), and RewrittenDataSource.listPropertyValues().
{
                 try {
                         rewriter.unrewrite(absoluteIRI);
                         return false;
                 } catch (IllegalArgumentException ex) {
                         // Tried to unrewrite an IRI that is already in original form
                         return true;
                 }
         }
listPropertyValues()
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Returns a subgraph of the data source.
It lists the values of a particular property of a particular resource. Where values are blank nodes, a complete description of these anonymous resources must be included.
Parameters
resourceIRI The resource to be examined
property The property we're interested in
isInverse Are we interested in outgoing arcs (false) or incoming (true)?
Returns
A subgraph of the data source.
Implements DataSource.
References RewrittenDataSource.addSameAsStatement(), DataSource.describeResource(), ModelUtil.EMPTY_MODEL, RewrittenDataSource.isOriginalIRI(), DataSource.listPropertyValues(), IRIRewriter.rewrite(), and IRIRewriter.unrewrite().
{
                 if (isOriginalIRI(resourceIRI)) {
                         // According to our logic, the original namespace is empty
                         // because we transplanted it. It only contains a sameAs
                         // statements for every resource in it.
                         if (!addSameAs || !property.equals(OWL.sameAs) || !isInverse ||
                                         original.describeResource(resourceIRI).isEmpty()) {
                                 return ModelUtil.EMPTY_MODEL;
                         }
                         Model result = ModelFactory.createDefaultModel();
                         addSameAsStatement(result, rewriter.rewrite(resourceIRI));
                         return result;
                 }
                 // Normal case -- a rewritten IRI
                 Model result = rewriter.rewrite(
                                 original.listPropertyValues(
                                                 rewriter.unrewrite(resourceIRI),
                                                 rewriter.unrewrite(property),
                                                 isInverse));
                 if (addSameAs && !result.isEmpty() && property.equals(OWL.sameAs) && !isInverse) {
                         addSameAsStatement(result, resourceIRI);
                 }
                 return result;
         }
Member Data Documentation
addSameAs
final boolean addSameAs private
MAX_INDEX_SIZE
final int MAX_INDEX_SIZE = 1000000 static inherited
Referenced by ModelDataSource.getIndex(), RemoteSPARQLDataSource.getIndex(), ModelDataSource.getLabelIndex(), and RemoteSPARQLDataSource.getLabelIndex().
original
final DataSource original private
Referenced by RewrittenDataSource.RewrittenDataSource().
rewriter
final IRIRewriter rewriter private
Referenced by RewrittenDataSource.RewrittenDataSource().