GeoPubby: GEO Class Reference
GEO Class Reference
Static Public Attributes
static final String WGS84GEONS = "http://www.w3.org/2003/01/geo/wgs84_pos#"
static final String GEOSPARQLNS = "http://www.opengis.net/ont/geosparql#"
static final String WIKIDATANS = "http://www.wikidata.org/prop/direct/"
static final Property P_LONG = model.createProperty(WGS84GEONS + "long")
static final Property P_LAT = model.createProperty(WGS84GEONS + "lat")
static final Property P_GEOMETRY = model.createProperty(WGS84GEONS + "geometry")
static final Property LOCATION = model.createProperty(WGS84GEONS + "location")
static final Property HASGEOMETRY = model.createProperty(GEOSPARQLNS + "hasGeometry")
static final Property ASWKT = model.createProperty(GEOSPARQLNS + "asWKT")
static final Property ASGEOJSON = model.createProperty(GEOSPARQLNS + "asGeoJSON")
static final Property ASGML = model.createProperty(GEOSPARQLNS + "asGML")
static final Property EPSG = model.createProperty(GEOSPARQLNS + "epsg")
static final Property P625 = model.createProperty(WIKIDATANS + "P625")
static final Property GEORSSPOINT = model.createProperty("http://www.georss.org/georss/point")
static List< Property > geomprops =Arrays.asList(new Property[] {P_LONG,P_LAT,P_GEOMETRY,LOCATION,HASGEOMETRY,ASWKT,P625})
Static Private Attributes
static Model model = ModelFactory.createDefaultModel()
Member Data Documentation
ASGEOJSON
final Property ASGEOJSON = model.createProperty(GEOSPARQLNS + "asGeoJSON") static
Referenced by ResourceDescription.addAllGeoms(), GeoModelWriter.handleGeometry(), and LDWriter.write().
ASGML
final Property ASGML = model.createProperty(GEOSPARQLNS + "asGML") static
ASWKT
final Property ASWKT = model.createProperty(GEOSPARQLNS + "asWKT") static
Referenced by ResourceDescription.addAllGeoms(), ResourceDescription.addGeometry(), GeoModelWriter.handleGeometry(), CoverageJSONWriter.write(), and LDWriter.write().
EPSG
final Property EPSG = model.createProperty(GEOSPARQLNS + "epsg") static
Referenced by ResourceDescription.getEPSG(), GeoModelWriter.handleGeometry(), WKBWriterr.write(), GeoURIWriter.write(), GoogleMapsLinkWriter.write(), XYZASCIIWriter.write(), LDWriter.write(), WKTWriter.write(), OSMLinkWriter.write(), TopoJSONWriter.write(), GeoJSONWriterr.write(), KMLWriter.write(), SVGWriter.write(), GPXWriter.write(), OSMWriter.write(), MapMLWriter.write(), GMLWriter.write(), and LatLonTextWriter.write().
geomprops
List<Property> geomprops =Arrays.asList(new Property[] {P_LONG,P_LAT,P_GEOMETRY,LOCATION,HASGEOMETRY,ASWKT,P625}) static
GEORSSPOINT
final Property GEORSSPOINT = model.createProperty("http://www.georss.org/georss/point") static
Referenced by GeoModelWriter.handleGeometry(), CoverageJSONWriter.write(), ModelWriter.write(), and LDWriter.write().
GEOSPARQLNS
final String GEOSPARQLNS = "http://www.opengis.net/ont/geosparql#" static
HASGEOMETRY
final Property HASGEOMETRY = model.createProperty(GEOSPARQLNS + "hasGeometry") static
Referenced by ResourceDescription.addAllGeoms(), and ModelWriter.write().
LOCATION
final Property LOCATION = model.createProperty(WGS84GEONS + "location") static
Referenced by ResourceDescription.addAllGeoms().
model
Model model = ModelFactory.createDefaultModel() static private
P625
final Property P625 = model.createProperty(WIKIDATANS + "P625") static
Referenced by GeoModelWriter.handleGeometry(), CoverageJSONWriter.write(), ModelWriter.write(), and LDWriter.write().
P_GEOMETRY
final Property P_GEOMETRY = model.createProperty(WGS84GEONS + "geometry") static
Referenced by ResourceDescription.addAllGeoms(), GeoModelWriter.handleGeometry(), CoverageJSONWriter.write(), and LDWriter.write().
P_LAT
final Property P_LAT = model.createProperty(WGS84GEONS + "lat") static
Referenced by ResourceDescription.addPoint(), GeoModelWriter.handleGeometry(), CoverageJSONWriter.write(), ModelWriter.write(), and LDWriter.write().
P_LONG
final Property P_LONG = model.createProperty(WGS84GEONS + "long") static
Referenced by ResourceDescription.addPoint(), GeoModelWriter.handleGeometry(), CoverageJSONWriter.write(), and LDWriter.write().
WGS84GEONS
final String WGS84GEONS = "http://www.w3.org/2003/01/geo/wgs84_pos#" static
WIKIDATANS
final String WIKIDATANS = "http://www.wikidata.org/prop/direct/" static