GeoPubby: PubbyNegotiator Class Reference
PubbyNegotiator Class Reference
Static Public Member Functions
static ContentTypeNegotiator getPubbyNegotiator ()
static ContentTypeNegotiator getDataNegotiator ()
Static Package Functions
[static initializer]
Static Private Attributes
static final ContentTypeNegotiator pubbyNegotiator
static final ContentTypeNegotiator dataNegotiator
Member Function Documentation
[static initializer]()
[static initializer] () static package
getDataNegotiator()
static ContentTypeNegotiator getDataNegotiator () static
References PubbyNegotiator.dataNegotiator.
Referenced by ModelResponse.doResponseModel(), PubbyNegotiatorTest.testDataURIDefaultsToN3ForFirefox(), and PubbyNegotiatorTest.testDataURIDefaultsToN3ForSafari().
{
                 return dataNegotiator;
         }
getPubbyNegotiator()
static ContentTypeNegotiator getPubbyNegotiator () static
References PubbyNegotiator.pubbyNegotiator.
Referenced by WebURIServlet.doGet(), and PubbyNegotiatorTest.setUp().
{
                 return pubbyNegotiator;
         }
Member Data Documentation
dataNegotiator
final ContentTypeNegotiator dataNegotiator static private
Referenced by PubbyNegotiator.getDataNegotiator().
pubbyNegotiator
final ContentTypeNegotiator pubbyNegotiator static private
Referenced by PubbyNegotiator.getPubbyNegotiator().