GeoPubby: ModelResponse Class Reference
ModelResponse Class Reference
Calls into Joseki to send a Jena model over HTTP.
Public Member Functions
ModelResponse (Model model, HttpServletRequest request, HttpServletResponse response)
void serve ()
Private Member Functions
void doResponseModel () throws IOException
ModelWriter getWriter (String mediaType, String crs)
Private Attributes
final Model model
final HttpServletRequest request
final HttpServletResponse response
Detailed Description
Calls into Joseki to send a Jena model over HTTP.
This gives us content negotiation and all the other tricks supported by Joseki for free. This has to be in the Joseki package because some required methods are not visible.
Constructor & Destructor Documentation
ModelResponse()
ModelResponse (Model model, HttpServletRequest request, HttpServletResponse response)
References RequestParamHandler.getModifiedRequest(), RequestParamHandler.isMatchingRequest(), ModelResponse.model, ModelResponse.request, and ModelResponse.response.
{
                 // Handle ?output=format request parameter
                 RequestParamHandler handler = new RequestParamHandler(request);
                 if (handler.isMatchingRequest()) {
                         request = handler.getModifiedRequest();
                 }
                 this.model = model;
                 this.request = request;
                 this.response = response;
         }
Member Function Documentation
doResponseModel()
void doResponseModel () throws IOException private
References ContentTypeNegotiator.getBestMatch(), PubbyNegotiator.getDataNegotiator(), MediaRangeSpec.getMediaType(), MediaRangeSpec.getParameter(), and ModelResponse.getWriter().
Referenced by ModelResponse.serve().
{
                 response.addHeader("Vary", "Accept");
                 ContentTypeNegotiator negotiator = PubbyNegotiator.getDataNegotiator();
                 MediaRangeSpec bestMatch = negotiator.getBestMatch(
                                 request.getHeader("Accept"), request.getHeader("User-Agent"));
                 if (bestMatch == null) {
                         response.setStatus(406);
                         response.setContentType("text/plain");
                         ServletOutputStream out = response.getOutputStream();
                         out.println("406 Not Acceptable: The requested data format is not supported.");
                         out.println("Supported formats are RDF/XML, JSON-LD, GeoJSON, GeoURI, TriX, WKT, GML, KML, SVG, GPX, TriG, Turtle, N3, and N-Triples.");
                         return;
                 }
                 String crs=null;
                 if(request.getParameter("crs")!=null) {
                         crs=request.getParameter("crs").toString();
                 }
                 response.setContentType(bestMatch.getMediaType());
                 getWriter(bestMatch.getMediaType(),crs).write(model, response);
                 response.getOutputStream().flush();
     }
getWriter()
ModelWriter getWriter (String mediaType, String crs) private
Referenced by ModelResponse.doResponseModel().
{
                 if ("application/rdf+xml".equals(mediaType)) {
                         return new LDWriter(crs,"RDF/XML");
                 }
                 if ("application/rdf+json".equals(mediaType)) {
                         return new LDWriter(crs,"RDF/JSON");
                 }
                 if ("application/json".equals(mediaType)) {
                         return new LDWriter(crs,"JSON-LD");
                 }
                 if ("application/geojson".equals(mediaType)) {
                         return new GeoJSONWriterr(crs);
                 }
                 if ("text/esrijson".equals(mediaType)) {
                         return new ESRIJSONWriter(crs);
                 }
                 if ("application/geojson-ld".equals(mediaType)) {
                         return new GeoJSONLDWriter(crs);
                 }
                 if ("application/topojson".equals(mediaType)) {
                         return new TopoJSONWriter(crs);
                 }
                 if ("image/svg+xml".equals(mediaType)) {
                         return new SVGWriter(crs);
                 }
                 if ("text/latlon".equals(mediaType)) {
                         return new LatLonTextWriter(crs);
                 }
                 if ("text/grass".equals(mediaType)) {
                         return new GRASSVectorASCIIWriter(crs);
                 }
                 if ("application/json+exi".equals(mediaType)) {
                         return new EXIJSONWriter(crs);
                 }
                 if("text/csv".equals(mediaType)){
                         return new CSVWriter(crs);
                 }
                 if("text/gpx".equals(mediaType)){
                         return new GPXWriter(crs);
                 }
                 if ("application/osm+xml".equals(mediaType)) {
                         return new OSMWriter(crs);
                 }
                 if ("text/osmlink".equals(mediaType)) {
                         return new OSMLinkWriter(crs);
                 }
                 if ("text/googlemapslink".equals(mediaType)) {
                         return new GoogleMapsLinkWriter(crs);
                 }
                 if ("application/geouri".equals(mediaType)) {
                         return new GeoURIWriter(crs);
                 }
                 if ("application/gml".equals(mediaType)) {
                         return new GMLWriter(crs);
                 }
                 if ("application/prs.coverage+json".equals(mediaType)) {
                         return new CoverageJSONWriter(crs);
                 }
                 if ("application/kml".equals(mediaType)) {
                         return new KMLWriter(crs);
                 }
                 if ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet".equals(mediaType)) {
                         return new XLSXWriter(crs);
                 }
                 if ("application/msexcel".equals(mediaType)) {
                         return new XLSWriter(crs);
                 }
                 if ("application/trig".equals(mediaType)) {
                         return new LDWriter(crs,"TriG");
                 }
                 if ("application/rdf+xml+exi".equals(mediaType)) {
                         return new RDFEXIWriter();
                 }
                 if ("text/vnd.yaml".equals(mediaType)) {
                         return new YAMLWriter(crs);
                 }
                 if ("application/javascript".equals(mediaType)) {
                         return new JSONPWriter(crs);
                 }
                 if("model/x3d+xml".equals(mediaType)) {
                         return new X3DWriter(crs);
                 }
                 if ("text/ewkt".equals(mediaType)) {
                         return new EWKTWriter(crs);
                 }
                 if ("text/wkt".equals(mediaType)) {
                         return new WKTWriter(crs);
                 }
                 if ("text/twkb".equals(mediaType)) {
                         return new TWKBWriterr(crs);
                 }
                 if ("text/wkb".equals(mediaType)) {
                         return new WKBWriterr(crs);
                 }
                 if ("text/mapml".equals(mediaType)) {
                         return new MapMLWriter(crs);
                 }
                 if ("text/xyz".equals(mediaType)) {
                         return new XYZASCIIWriter(crs);
                 }
                 if ("text/cipher".equals(mediaType)) {
                         return new CypherWriter(crs);
                 }
                 if ("text/olc".equals(mediaType)) {
                         return new OpenLocationCodeWriter(crs);
                 }
                 if ("text/geohash".equals(mediaType)) {
                         return new GeoHashWriter(crs);
                 }
                 if ("text/graphml".equals(mediaType)) {
                         return new GraphMLWriter(crs);
                 }
                 if ("text/tgf".equals(mediaType)) {
                         return new TGFWriter(crs);
                 }
                 if ("text/gdf".equals(mediaType)) {
                         return new GDFWriter(crs);
                 }
                 if ("application/trix".equals(mediaType)) {
                         return new LDWriter(crs,"TriX");
                 }
                 if ("application/x-turtle".equals(mediaType)) {
                         return new LDWriter(crs,"TURTLE");
                 }
                 if ("text/rdf+n3;charset=utf-8".equals(mediaType)) {
                         return new LDWriter(crs,"N3");
                 }
                 if("application/rt".equals(mediaType)) {
                         return new LDWriter(crs,"RDFTHRIFT");
                 }
                 if("text/nq".equals(mediaType)) {
                         return new LDWriter(crs,"NQUADS");
                 }
                 if("application/hex+x-ndjson".equals(mediaType)) {
                         return new HexTuplesWriter(crs);
                 }
                 return new LDWriter(crs,"N-TRIPLES");
         }
serve()
void serve ()
References ModelResponse.doResponseModel().
Referenced by ValuesDataURLServlet.doGet().
{
                 // Error hendling is still quite a mess here.
                 try {
                         doResponseModel();
                 } catch (IOException ioEx) {
                         throw new RuntimeException(ioEx);
                 } catch (JenaException jEx) {
                         try {
                                 response.sendError(
                                                 HttpServletResponse.SC_INTERNAL_SERVER_ERROR,
                                                 "JenaException: " + jEx.getMessage());
                                 jEx.printStackTrace();
             } catch (IOException e) {
                 throw new RuntimeException(e);
             }
                 }
         }
Member Data Documentation
model
final Model model private
Referenced by ModelResponse.ModelResponse().
request
final HttpServletRequest request private
Referenced by ModelResponse.ModelResponse().
response
final HttpServletResponse response private
Referenced by ModelResponse.ModelResponse().