GeoPubby: HypermediaControls Class Reference
HypermediaControls Class Reference
The hypermedia interface to a specific resource.
Public Member Functions
boolean isHosted ()
Is the resource itself hosted by Pubby, that is, is it in Pubby's web base namespace? (If not, then Pubby merely provides a hypermedia browsing interface for the resource, but cannot be said to host the resource itself.)
String getAbsoluteIRI ()
String getBrowsableURL ()
ResourceDescription getResourceDescription ()
String getPageURL ()
String getDataURL ()
String getValuesPageURL (Property property)
String getInverseValuesPageURL (Property property)
String getValuesDataURL (Property property)
String getInverseValuesDataURL (Property property)
Static Public Member Functions
static HypermediaControls createFromPubbyPath (String path, Configuration config)
Creates a new hypermedia resource from a Pubby path representing a resource.
static HypermediaControls createFromIRI (String absoluteIRI, Configuration config)
Creates a new hypermedia resource from an absolute IRI.
Private Member Functions
HypermediaControls (String absoluteIRI, Configuration config)
String getPubbyPath ()
A version of the resource's IRI suitable for use in constructing Pubby path URLs.
String getPathURL (String urlPrefix, Property property)
Private Attributes
final String absoluteIRI
final boolean isHosted
final Configuration config
Detailed Description
The hypermedia interface to a specific resource.
The resource may be hosted by the server or merely made browsable by the server.
Constructor & Destructor Documentation
HypermediaControls()
HypermediaControls (String absoluteIRI, Configuration config) private
References HypermediaControls.absoluteIRI, HypermediaControls.config, and Configuration.getWebApplicationBaseURI().
Referenced by HypermediaControls.createFromIRI().
{
                 this.absoluteIRI = absoluteIRI;
                 this.config = config;
                 this.isHosted = absoluteIRI.startsWith(config.getWebApplicationBaseURI());
         }
Member Function Documentation
createFromIRI()
static HypermediaControls createFromIRI (String absoluteIRI, Configuration config) static
Creates a new hypermedia resource from an absolute IRI.
Parameters
absoluteIRI An IRI identifying the resource
config The server's configuration
Returns
An object providing hypermedia controls for the resource, or null if this is not a Pubby-browsable resource.
References HypermediaControls.HypermediaControls(), and Configuration.isBrowsable().
Referenced by HypermediaControls.createFromPubbyPath(), RootServlet.doGet(), ResourceDescription.ResourceProperty.getBrowsableURL(), and ResourceDescription.Value.getBrowsableURL().
{
                 if (absoluteIRI == null) return null;
                 if (!config.isBrowsable(absoluteIRI)) return null;
                 return new HypermediaControls(absoluteIRI, config);
         }
createFromPubbyPath()
static HypermediaControls createFromPubbyPath (String path, Configuration config) static
Creates a new hypermedia resource from a Pubby path representing a resource.
Parameters
path A Pubby path, either absolute or relative
config The server's configuration
Returns
An object providing hypermedia controls for the resource, or null if this is not a Pubby-browsable resource.
References HypermediaControls.config, HypermediaControls.createFromIRI(), Configuration.getWebApplicationBaseURI(), Configuration.getWebResourcePrefix(), and PubbyIRIEscaper.unescapeSpecialCharacters().
Referenced by Configuration.getControls().
{
                 try {
                         if (new URI(path).isAbsolute()) {
                                 return createFromIRI(
                                                 PubbyIRIEscaper.unescapeSpecialCharacters(path), config);
                         } else {
                                 return createFromIRI(config.getWebApplicationBaseURI() +
                                                 config.getWebResourcePrefix() + path, config);
                         }
                 } catch (URISyntaxException ex) {
                         return null;
                 }
         }
getAbsoluteIRI()
String getAbsoluteIRI ()
Returns
the resource's absolute IRI
References HypermediaControls.absoluteIRI.
Referenced by BaseServlet.addDocumentMetadata(), DataURLServlet.addHighDegreePropertyLinks(), DataURLServlet.doGet(), MetadataConfiguration.parsePlaceholder(), and ResourceDescription.ResourceDescription().
{
                 return absoluteIRI;
         }
getBrowsableURL()
String getBrowsableURL ()
Returns
Best hyperlink for this resource (Pubby page if available).
References HypermediaControls.absoluteIRI, and HypermediaControls.getPageURL().
Referenced by ResourceDescription.ResourceProperty.getBrowsableURL().
{
                 if (isHosted) {
                         return absoluteIRI;
                 } else {
                         return getPageURL();
                 }
         }
getDataURL()
String getDataURL ()
Returns
the RDF document describing the resource on the public Web server
References HypermediaControls.getPubbyPath(), and Configuration.getWebApplicationBaseURI().
Referenced by PageURLServlet.doGet(), WebURIServlet.doGet(), DataURLServlet.doGet(), and MetadataConfiguration.parsePlaceholder().
{
                 return config.getWebApplicationBaseURI() + "data/" + getPubbyPath();
         }
getInverseValuesDataURL()
String getInverseValuesDataURL (Property property)
References HypermediaControls.getPathURL().
Referenced by DataURLServlet.addHighDegreePropertyLinks().
{
                 return getPathURL("values.data/-", property);
         }
getInverseValuesPageURL()
String getInverseValuesPageURL (Property property)
References HypermediaControls.getPathURL().
Referenced by ResourceDescription.ResourceProperty.getValuesPageURL().
{
                 return getPathURL("values/-", property);
         }
getPageURL()
String getPageURL ()
Returns
the HTML page describing the resource on the public Web server
References HypermediaControls.getPubbyPath(), and Configuration.getWebApplicationBaseURI().
Referenced by WebURIServlet.doGet(), HypermediaControls.getBrowsableURL(), and ResourceDescription.Value.getBrowsableURL().
{
                 return config.getWebApplicationBaseURI() + "page/" + getPubbyPath();
         }
getPathURL()
String getPathURL (String urlPrefix, Property property) private
References PubbyIRIEscaper.escapeSpecialCharacters(), Configuration.getPrefixes(), HypermediaControls.getPubbyPath(), and Configuration.getWebApplicationBaseURI().
Referenced by HypermediaControls.getInverseValuesDataURL(), HypermediaControls.getInverseValuesPageURL(), HypermediaControls.getValuesDataURL(), and HypermediaControls.getValuesPageURL().
{
                 if (config.getPrefixes().qnameFor(property.getURI()) == null) {
                         String encoded = PubbyIRIEscaper.escapeSpecialCharacters(property.getURI());
                         return config.getWebApplicationBaseURI() + urlPrefix +
                                         "!" + encoded + "///" +
                                         getPubbyPath();
                 }
                 return config.getWebApplicationBaseURI() + urlPrefix +
                                 config.getPrefixes().qnameFor(property.getURI()) + "/" +
                                 getPubbyPath();
         }
getPubbyPath()
String getPubbyPath () private
A version of the resource's IRI suitable for use in constructing Pubby path URLs.
If the resource is Pubby-hosted, this will be its IRI relative to the resource base (conf:webBase + conf:webResourcePrefix). Otherwise, it will be its full absolute IRI with special characters escaped to make it safe in constructing paths.
Returns
References PubbyIRIEscaper.escapeSpecialCharacters(), Configuration.getWebApplicationBaseURI(), and Configuration.getWebResourcePrefix().
Referenced by HypermediaControls.getDataURL(), HypermediaControls.getPageURL(), and HypermediaControls.getPathURL().
{
                 if (isHosted) {
                         int resourceBaseLength = config.getWebApplicationBaseURI().length() +
                                         config.getWebResourcePrefix().length();
                         return absoluteIRI.substring(resourceBaseLength);
                 } else {
                         return PubbyIRIEscaper.escapeSpecialCharacters(absoluteIRI);
                 }
         }
getResourceDescription()
ResourceDescription getResourceDescription ()
Returns
A description of the resource that allows interrogation of the data
References HypermediaControls.config, DataSource.describeResource(), Configuration.getDataSource(), DataSource.getHighIndegreeProperties(), and DataSource.getHighOutdegreeProperties().
Referenced by PageURLServlet.doGet(), and DataURLServlet.doGet().
{
                 DataSource source = config.getDataSource();
                 Model model = source.describeResource(absoluteIRI);
                 if (model.isEmpty()) return null;
                 return new ResourceDescription(this, model,
                                 source.getHighIndegreeProperties(absoluteIRI),
                                 source.getHighOutdegreeProperties(absoluteIRI),
                                 config);
         }
getValuesDataURL()
String getValuesDataURL (Property property)
References HypermediaControls.getPathURL().
Referenced by DataURLServlet.addHighDegreePropertyLinks().
{
                 return getPathURL("values.data/", property);
         }
getValuesPageURL()
String getValuesPageURL (Property property)
References HypermediaControls.getPathURL().
Referenced by ResourceDescription.ResourceProperty.getValuesPageURL().
{
                 return getPathURL("values/", property);
         }
isHosted()
boolean isHosted ()
Is the resource itself hosted by Pubby, that is, is it in Pubby's web base namespace? (If not, then Pubby merely provides a hypermedia browsing interface for the resource, but cannot be said to host the resource itself.)
{
                 return isHosted;
         }
Member Data Documentation
absoluteIRI
final String absoluteIRI private
Referenced by HypermediaControls.getAbsoluteIRI(), HypermediaControls.getBrowsableURL(), and HypermediaControls.HypermediaControls().
config
final Configuration config private
Referenced by HypermediaControls.createFromPubbyPath(), HypermediaControls.getResourceDescription(), and HypermediaControls.HypermediaControls().
isHosted
final boolean isHosted private
Referenced by WebURIServlet.doGet().