GeoPubby: ContentTypeNegotiatorTest Class Reference
ContentTypeNegotiatorTest Class Reference
Public Member Functions
void setUp ()
void testNoVariantOnServer ()
void testMatchSimple ()
void testNoMatch ()
void testUseDefaultIfNoMatch ()
void testUseDefaultIfTwoEqualOptions ()
void testPickFirstIfTwoEqualOptions ()
void testDefaultToHigherQuality ()
void testPickCorrectMatchSimple ()
void testPickCorrectMatchWithClientQuality ()
void testPickCorrectMatchWithServerQuality1 ()
void testPickCorrectMatchWithServerQuality2 ()
void testNoMatchIfBestEqualsZero ()
void testQualityMultiplication ()
void testEmptyHeader ()
void testEmptyHeaderPickBestQuality ()
void testAcceptAlias ()
void testUseAliasQuality ()
void testSpecifyDefaultAccept ()
void testUserAgentOverrideSimple ()
Private Attributes
ContentTypeNegotiator negotiator
Member Function Documentation
setUp()
void setUp ()
{
                 negotiator = new ContentTypeNegotiator();
         }
testAcceptAlias()
void testAcceptAlias ()
References ContentTypeNegotiator.VariantSpec.addAliasMediaType(), ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b").addAliasMediaType("c/d");
                 assertEquals("a/b", negotiator.getBestMatch("c/d").getMediaType());
         }
testDefaultToHigherQuality()
void testDefaultToHigherQuality ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b;q=0.6");
                 negotiator.addVariant("c/d;q=0.8");
                 assertEquals("c/d", negotiator.getBestMatch("*/*").getMediaType());
         }
testEmptyHeader()
void testEmptyHeader ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b");
                 assertEquals("a/b", negotiator.getBestMatch("").getMediaType());
                 assertEquals("a/b", negotiator.getBestMatch(null).getMediaType());
                 assertEquals("a/b", negotiator.getBestMatch("junk").getMediaType());
         }
testEmptyHeaderPickBestQuality()
void testEmptyHeaderPickBestQuality ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b;q=0.2");
                 negotiator.addVariant("c/d");
                 assertEquals("c/d", negotiator.getBestMatch(null).getMediaType());
         }
testMatchSimple()
void testMatchSimple ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b");
                 assertEquals("a/b", negotiator.getBestMatch("a/b").getMediaType());
         }
testNoMatch()
void testNoMatch ()
References ContentTypeNegotiator.addVariant(), and ContentTypeNegotiator.getBestMatch().
{
                 negotiator.addVariant("a/b");
                 assertNull(negotiator.getBestMatch("z/z"));
         }
testNoMatchIfBestEqualsZero()
void testNoMatchIfBestEqualsZero ()
References ContentTypeNegotiator.addVariant(), and ContentTypeNegotiator.getBestMatch().
{
                 negotiator.addVariant("a/b");
                 assertNull(negotiator.getBestMatch("a/*;q=0"));
         }
testNoVariantOnServer()
void testNoVariantOnServer ()
References ContentTypeNegotiator.getBestMatch().
{
                 assertNull(negotiator.getBestMatch("a/b"));
         }
testPickCorrectMatchSimple()
void testPickCorrectMatchSimple ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b");
                 negotiator.addVariant("c/d");
                 assertEquals("c/d", negotiator.getBestMatch("c/d").getMediaType());
         }
testPickCorrectMatchWithClientQuality()
void testPickCorrectMatchWithClientQuality ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b");
                 negotiator.addVariant("c/d");
                 assertEquals("a/b", negotiator.getBestMatch("a/b;q=0.8,c/d;q=0.6").getMediaType());
                 assertEquals("c/d", negotiator.getBestMatch("a/b;q=0.6,c/d;q=0.8").getMediaType());
         }
testPickCorrectMatchWithServerQuality1()
void testPickCorrectMatchWithServerQuality1 ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b;q=0.8");
                 negotiator.addVariant("c/d;q=0.6");
                 assertEquals("a/b", negotiator.getBestMatch("a/b,c/d").getMediaType());
         }
testPickCorrectMatchWithServerQuality2()
void testPickCorrectMatchWithServerQuality2 ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b;q=0.6");
                 negotiator.addVariant("c/d;q=0.8");
                 assertEquals("c/d", negotiator.getBestMatch("a/b,c/d").getMediaType());
         }
testPickFirstIfTwoEqualOptions()
void testPickFirstIfTwoEqualOptions ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b");
                 negotiator.addVariant("c/d");
                 assertEquals("a/b", negotiator.getBestMatch("*/*").getMediaType());
         }
testQualityMultiplication()
void testQualityMultiplication ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b;q=0.1");
                 negotiator.addVariant("c/d;q=0.9");
                 negotiator.addVariant("e/f;q=0.8");
                 assertEquals("e/f", negotiator.getBestMatch("a/b;q=0.9;c/d;q=0.1;e/f;q=0.8").getMediaType());
         }
testSpecifyDefaultAccept()
void testSpecifyDefaultAccept ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and ContentTypeNegotiator.setDefaultAccept().
{
                 negotiator.addVariant("a/b");
                 negotiator.addVariant("c/d;q=0.5");
                 negotiator.setDefaultAccept("c/d");
                 assertEquals("c/d", negotiator.getBestMatch(null).getMediaType());
         }
testUseAliasQuality()
void testUseAliasQuality ()
References ContentTypeNegotiator.VariantSpec.addAliasMediaType(), ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b;q=0.5");
                 negotiator.addVariant("c/d").addAliasMediaType("e/f;q=0.1");
                 assertEquals("a/b", negotiator.getBestMatch("a/b,e/f").getMediaType());
         }
testUseDefaultIfNoMatch()
void testUseDefaultIfNoMatch ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and ContentTypeNegotiator.VariantSpec.makeDefault().
{
                 negotiator.addVariant("a/b").makeDefault();
                 assertEquals("a/b", negotiator.getBestMatch("z/z").getMediaType());
         }
testUseDefaultIfTwoEqualOptions()
void testUseDefaultIfTwoEqualOptions ()
References ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and ContentTypeNegotiator.VariantSpec.makeDefault().
{
                 negotiator.addVariant("a/b");
                 negotiator.addVariant("c/d").makeDefault();
                 assertEquals("c/d", negotiator.getBestMatch("z/z").getMediaType());
         }
testUserAgentOverrideSimple()
void testUserAgentOverrideSimple ()
References ContentTypeNegotiator.addUserAgentOverride(), ContentTypeNegotiator.addVariant(), ContentTypeNegotiator.getBestMatch(), and MediaRangeSpec.getMediaType().
{
                 negotiator.addVariant("a/b");
                 negotiator.addVariant("c/d;q=0.5");
                 negotiator.addUserAgentOverride(Pattern.compile(""), null, "c/d");
                 assertEquals("c/d", negotiator.getBestMatch("a/b", null).getMediaType());
         }
Member Data Documentation
negotiator
ContentTypeNegotiator negotiator private