GeoPubby: ResourceDescription.ResourceProperty Class Reference
ResourceDescription.ResourceProperty Class Reference
Public Member Functions
ResourceProperty (Property predicate, boolean isInverse, List< Value > simpleValues, List< ResourceDescription > complexVaues, int omittedValues, VocabularyStore vocabularyStore)
boolean isInverse ()
String getURI ()
String getBrowsableURL ()
boolean hasPrefix ()
String getPrefix ()
String getLocalName ()
String getLabel ()
String getLabel (boolean preferPlural)
String getInverseLabel ()
String getInverseLabel (boolean preferPlural)
String getCompleteLabel ()
Note: This bypasses conf:showLabels, always assuming true
String getDescription ()
List< Value > getSimpleValues ()
List< ResourceDescription > getComplexValues ()
boolean hasOnlySimpleValues ()
int getValueCount ()
boolean isMultiValued ()
String getValuesPageURL ()
int compareTo (ResourceProperty other)
Private Attributes
final Property predicate
final URIPrefixer predicatePrefixer
final boolean isInverse
final List< Value > simpleValues
final List< ResourceDescription > complexValues
final int omittedValues
final VocabularyStore vocabularyStore
Constructor & Destructor Documentation
ResourceProperty()
ResourceProperty (Property predicate, boolean isInverse, List< Value > simpleValues, List< ResourceDescription > complexVaues, int omittedValues, VocabularyStore vocabularyStore)
{
                         this.predicate = predicate;
                         this.predicatePrefixer = new URIPrefixer(predicate, getPrefixes());
                         this.isInverse = isInverse;
                         this.simpleValues = simpleValues;
                         this.complexValues = complexVaues;
                         this.omittedValues = omittedValues;
                         this.vocabularyStore = vocabularyStore;
                 }
References ResourceDescription.getPrefixes(), ResourceDescription.ResourceProperty.isInverse, ResourceDescription.ResourceProperty.omittedValues, ResourceDescription.ResourceProperty.predicate, ResourceDescription.ResourceProperty.simpleValues, and ResourceDescription.ResourceProperty.vocabularyStore.
Referenced by ResourceDescription.ResourceProperty.compareTo().
Member Function Documentation
compareTo()
int compareTo (ResourceProperty other)
{
                         if (!(other instanceof ResourceProperty)) {
                                 return 0;
                         }
                         ResourceProperty otherProperty = (ResourceProperty) other;
                         int myWeight = config.getVocabularyStore().getWeight(
                                         predicate, isInverse);
                         int otherWeight = config.getVocabularyStore().getWeight(
                                         otherProperty.predicate, other.isInverse);
                         if (myWeight < otherWeight) return -1;
                         if (myWeight > otherWeight) return 1;
                         String propertyLocalName = getLocalName();
                         String otherLocalName = otherProperty.getLocalName();
                         if (propertyLocalName.compareTo(otherLocalName) != 0) {
                                 return propertyLocalName.compareTo(otherLocalName);
                         }
                         if (this.isInverse() != otherProperty.isInverse()) {
                                 return (this.isInverse()) ? 1 : -1;
                         }
                         return 0;
                 }
References ResourceDescription.config, ResourceDescription.ResourceProperty.getLocalName(), Configuration.getVocabularyStore(), VocabularyStore.getWeight(), ResourceDescription.ResourceProperty.isInverse, ResourceDescription.ResourceProperty.predicate, and ResourceDescription.ResourceProperty.ResourceProperty().
getBrowsableURL()
String getBrowsableURL ()
{
                         HypermediaControls controls = HypermediaControls.createFromIRI(
                                         predicate.getURI(), config);
                         if (controls == null) return predicate.getURI();
                         return controls.getBrowsableURL();
                 }
References ResourceDescription.config, HypermediaControls.createFromIRI(), HypermediaControls.getBrowsableURL(), and ResourceDescription.ResourceProperty.predicate.
getCompleteLabel()
String getCompleteLabel ()
Note: This bypasses conf:showLabels, always assuming true
Returns
"Is Widget Of", "Widgets", "ex:widget", whatever is most appropriate
{
                         if (isInverse && getInverseLabel() != null) {
                                 return getInverseLabel();
                         }
                         String result;
                         if (getLabel() != null) {
                                 result = getLabel();
                         } else if (hasPrefix()) {
                                 result = getPrefix() + ":" + getLocalName();
                         } else {
                                 result = "?:" + getLocalName();
                         }
                         return isInverse ? "Is " + result + " of" : result;
                 }
References ResourceDescription.ResourceProperty.getInverseLabel(), ResourceDescription.ResourceProperty.getLabel(), ResourceDescription.ResourceProperty.getLocalName(), ResourceDescription.ResourceProperty.getPrefix(), ResourceDescription.ResourceProperty.hasPrefix(), and ResourceDescription.ResourceProperty.isInverse.
getComplexValues()
List<ResourceDescription> getComplexValues ()
{
                         return complexValues;
                 }
References ResourceDescription.ResourceProperty.complexValues.
getDescription()
String getDescription ()
{
                         return vocabularyStore.getDescription(predicate.getURI()).getLexicalForm();
                 }
References VocabularyStore.getDescription(), ResourceDescription.ResourceProperty.predicate, and ResourceDescription.ResourceProperty.vocabularyStore.
getInverseLabel() [1/2]
String getInverseLabel ()
{
                         return getInverseLabel(isMultiValued());
                 }
References ResourceDescription.ResourceProperty.isMultiValued().
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
getInverseLabel() [2/2]
String getInverseLabel (boolean preferPlural)
{
                         Literal label = vocabularyStore.getInverseLabel(predicate.getURI(), preferPlural);
                         if (label == null) return null;
                         return toTitleCase(label.getLexicalForm(), label.getLanguage());
                 }
References VocabularyStore.getInverseLabel(), ResourceDescription.ResourceProperty.predicate, ResourceDescription.toTitleCase(), and ResourceDescription.ResourceProperty.vocabularyStore.
getLabel() [1/2]
String getLabel ()
{
                         return getLabel(isMultiValued());
                 }
References ResourceDescription.ResourceProperty.isMultiValued().
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
getLabel() [2/2]
String getLabel (boolean preferPlural)
{
                         System.out.println("Getting label (plural)? "+predicate.getURI());
                         Literal label = vocabularyStore.getLabel(predicate.getURI(), preferPlural);
                         System.out.println("Found label: "+label);
                         if (label == null) {
                                 StmtIterator iter=predicate.listProperties(RDFS.label);
                                 if(iter.hasNext()) {
                                         String labelprop=iter.next().getObject().asLiteral().getString();
                                         System.out.println("Got Label for Prop: "+labelprop);
                                         return labelprop;
                                 }else {
                                         return null;
                                 }
                         }
                         return toTitleCase(label.getLexicalForm(), label.getLanguage());
                 }
References VocabularyStore.getLabel(), ResourceDescription.ResourceProperty.predicate, ResourceDescription.toTitleCase(), and ResourceDescription.ResourceProperty.vocabularyStore.
getLocalName()
String getLocalName ()
{
                         return predicatePrefixer.getLocalName();
                 }
References URIPrefixer.getLocalName(), and ResourceDescription.ResourceProperty.predicatePrefixer.
Referenced by ResourceDescription.ResourceProperty.compareTo(), and ResourceDescription.ResourceProperty.getCompleteLabel().
getPrefix()
String getPrefix ()
{
                         return predicatePrefixer.getPrefix();
                 }
References URIPrefixer.getPrefix(), and ResourceDescription.ResourceProperty.predicatePrefixer.
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
getSimpleValues()
List<Value> getSimpleValues ()
{
                         return simpleValues;
                 }
References ResourceDescription.ResourceProperty.simpleValues.
getURI()
String getURI ()
{
                         return predicate.getURI();
                 }
References ResourceDescription.ResourceProperty.predicate.
getValueCount()
int getValueCount ()
{
                         return omittedValues + complexValues.size() + simpleValues.size();
                 }
References ResourceDescription.ResourceProperty.complexValues, ResourceDescription.ResourceProperty.omittedValues, and ResourceDescription.ResourceProperty.simpleValues.
getValuesPageURL()
String getValuesPageURL ()
{
                         if (hypermediaResource == null) {
                                 return null;
                         }
                         return isInverse
                                         ? hypermediaResource.getInverseValuesPageURL(predicate)
                                         : hypermediaResource.getValuesPageURL(predicate);
                 }
References HypermediaControls.getInverseValuesPageURL(), HypermediaControls.getValuesPageURL(), ResourceDescription.hypermediaResource, ResourceDescription.ResourceProperty.isInverse, and ResourceDescription.ResourceProperty.predicate.
hasOnlySimpleValues()
boolean hasOnlySimpleValues ()
{
                         return omittedValues == 0 && complexValues.isEmpty();
                 }
References ResourceDescription.ResourceProperty.complexValues, and ResourceDescription.ResourceProperty.omittedValues.
hasPrefix()
boolean hasPrefix ()
{
                         return predicatePrefixer.hasPrefix();
                 }
References URIPrefixer.hasPrefix(), and ResourceDescription.ResourceProperty.predicatePrefixer.
Referenced by ResourceDescription.ResourceProperty.getCompleteLabel().
isInverse()
boolean isInverse ()
{
                         return isInverse;
                 }
References ResourceDescription.ResourceProperty.isInverse.
isMultiValued()
boolean isMultiValued ()
{
                         return simpleValues.size() + omittedValues + complexValues.size() > 1;
                 }
References ResourceDescription.ResourceProperty.complexValues, ResourceDescription.ResourceProperty.omittedValues, and ResourceDescription.ResourceProperty.simpleValues.
Referenced by ResourceDescription.ResourceProperty.getInverseLabel(), and ResourceDescription.ResourceProperty.getLabel().
Member Data Documentation
complexValues
final List<ResourceDescription> complexValues private
Referenced by ResourceDescription.ResourceProperty.getComplexValues(), ResourceDescription.ResourceProperty.getValueCount(), ResourceDescription.ResourceProperty.hasOnlySimpleValues(), and ResourceDescription.ResourceProperty.isMultiValued().
isInverse
final boolean isInverse private
Referenced by ResourceDescription.ResourceProperty.compareTo(), ResourceDescription.ResourceProperty.getCompleteLabel(), ResourceDescription.ResourceProperty.getValuesPageURL(), ResourceDescription.ResourceProperty.isInverse(), and ResourceDescription.ResourceProperty.ResourceProperty().
omittedValues
final int omittedValues private
Referenced by ResourceDescription.ResourceProperty.getValueCount(), ResourceDescription.ResourceProperty.hasOnlySimpleValues(), ResourceDescription.ResourceProperty.isMultiValued(), and ResourceDescription.ResourceProperty.ResourceProperty().
predicate
final Property predicate private
Referenced by ResourceDescription.ResourceProperty.compareTo(), ResourceDescription.ResourceProperty.getBrowsableURL(), ResourceDescription.ResourceProperty.getDescription(), ResourceDescription.ResourceProperty.getInverseLabel(), ResourceDescription.ResourceProperty.getLabel(), ResourceDescription.ResourceProperty.getURI(), ResourceDescription.ResourceProperty.getValuesPageURL(), and ResourceDescription.ResourceProperty.ResourceProperty().
predicatePrefixer
final URIPrefixer predicatePrefixer private
Referenced by ResourceDescription.ResourceProperty.getLocalName(), ResourceDescription.ResourceProperty.getPrefix(), and ResourceDescription.ResourceProperty.hasPrefix().
simpleValues
final List<Value> simpleValues private
Referenced by ResourceDescription.ResourceProperty.getSimpleValues(), ResourceDescription.ResourceProperty.getValueCount(), ResourceDescription.ResourceProperty.isMultiValued(), and ResourceDescription.ResourceProperty.ResourceProperty().
vocabularyStore
final VocabularyStore vocabularyStore private
Referenced by ResourceDescription.ResourceProperty.getDescription(), ResourceDescription.ResourceProperty.getInverseLabel(), ResourceDescription.ResourceProperty.getLabel(), and ResourceDescription.ResourceProperty.ResourceProperty().