GeoPubby: MergeDataSource Class Reference
MergeDataSource Class Reference
A DataSource that presents an RDF merge of multiple other data sources.
Public Member Functions
MergeDataSource (DataSource... sources)
MergeDataSource (Collection< DataSource > sources)
MergeDataSource (Collection< DataSource > sources, PrefixMapping mustHavePrefixes)
boolean canDescribe (String absoluteIRI)
Indicates whether this data source may have some information about a given IRI.
Model describeResource (String iri, String language)
Returns a subgraph of the data source describing one resource.
Model describeResource (String iri)
Returns a subgraph of the data source describing one resource.
Map< Property, Integer > getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
Map< Property, Integer > getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Returns a subgraph of the data source.
List< Resource > getIndex ()
A list of IRI resources described in this data source.
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine< SearchRecord > getLabelIndex ()
Public Attributes
final Collection< DataSource > sources
Static Public Attributes
static final int MAX_INDEX_SIZE = 1000000
Package Functions
private< K > Map< K, Integer > addIntegerMaps (Map< K, Integer > map1, Map< K, Integer > map2)
Private Attributes
final PrefixMapping mustHavePrefixes
Detailed Description
A DataSource that presents an RDF merge of multiple other data sources.
Can also be initialized with a prefix mapping that will be guaranteed to be defined on all result models.
Constructor & Destructor Documentation
MergeDataSource() [1/3]
MergeDataSource (DataSource... sources)
{
                 this(Arrays.asList(sources));
         }
MergeDataSource() [2/3]
MergeDataSource (Collection< DataSource > sources)
References MergeDataSource.sources.
{
                 this(sources, new PrefixMappingImpl());
         }
MergeDataSource() [3/3]
MergeDataSource (Collection< DataSource > sources, PrefixMapping mustHavePrefixes)
References MergeDataSource.mustHavePrefixes, and MergeDataSource.sources.
{
                 this.sources = sources;
                 this.mustHavePrefixes = mustHavePrefixes;
         }
Member Function Documentation
addIntegerMaps()
private<K> Map<K, Integer> addIntegerMaps (Map< K, Integer > map1, Map< K, Integer > map2) package
Referenced by MergeDataSource.getHighIndegreeProperties(), and MergeDataSource.getHighOutdegreeProperties().
{
                 if (map1 == null) return map2;
                 if (map2 == null) return map1;
                 for (K key: map2.keySet()) {
                         int value = map2.get(key);
                         if (value == 0) continue;
                         map1.put(key, map1.containsKey(key) ? map1.get(key) + value : value);
                 }
                 return map1;
         }
canDescribe()
boolean canDescribe (String absoluteIRI)
Indicates whether this data source may have some information about a given IRI.
If this is false, a client should not bother to call describeResource(String). This method is to allow for optimizations and should respond very fast.
It is also used by the UI to decide whether a click on a resource should go to a Pubby page (if true) or out to the Web (if false).
Parameters
absoluteIRI The IRI of a resource to be described
Returns
true if this data source might have something about it
Implements DataSource.
{
                 for (DataSource source: sources) {
                         if (source.canDescribe(absoluteIRI)) return true;
                 }
                 return false;
         }
describeResource() [1/2]
Model describeResource (String absoluteIRI, String language)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
References ModelUtil.mergeModels(), and ModelUtil.mergePrefixes().
{
                 Model result = ModelFactory.createDefaultModel();
                 for (DataSource source: sources) {
                         if (!source.canDescribe(iri)) continue;
                         ModelUtil.mergeModels(result, source.describeResource(iri,language));
                 }
                 // Remove any other prefixes that may already be defined for the must-have namespaces
                 for (String prefix: mustHavePrefixes.getNsPrefixMap().keySet()) {
                         String ns = mustHavePrefixes.getNsPrefixURI(prefix);
                         while (result.getNsURIPrefix(ns) != null) {
                                 result.removeNsPrefix(result.getNsURIPrefix(ns));
                         }
                 }
                 // Set all the must-have prefix/namespace pairs
                 ModelUtil.mergePrefixes(result, mustHavePrefixes);
                 return result;
         }
describeResource() [2/2]
Model describeResource (String absoluteIRI)
Returns a subgraph of the data source describing one resource.
This should include both incoming and outgoing triples. However, it should exclude outgoing arcs where the property is a high-outdegree property, and it should exclude incoming arcs where the property is a high-indegree property. If labels for other resources are included in the result, then they will be used.
Parameters
absoluteIRI The IRI of the resource to be described
Returns
A subgraph of the data source describing the resource.
Implements DataSource.
References ModelUtil.mergeModels(), and ModelUtil.mergePrefixes().
{
                 Model result = ModelFactory.createDefaultModel();
                 for (DataSource source: sources) {
                         if (!source.canDescribe(iri)) continue;
                         ModelUtil.mergeModels(result, source.describeResource(iri));
                 }
                 // Remove any other prefixes that may already be defined for the must-have namespaces
                 for (String prefix: mustHavePrefixes.getNsPrefixMap().keySet()) {
                         String ns = mustHavePrefixes.getNsPrefixURI(prefix);
                         while (result.getNsURIPrefix(ns) != null) {
                                 result.removeNsPrefix(result.getNsURIPrefix(ns));
                         }
                 }
                 // Set all the must-have prefix/namespace pairs
                 ModelUtil.mergePrefixes(result, mustHavePrefixes);
                 return result;
         }
getHighIndegreeProperties()
Map<Property, Integer> getHighIndegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high indegree, then those properties must be returned here with the count of arcs.
If high-indegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-indegree properties with number of arcs for the resource
Implements DataSource.
References MergeDataSource.addIntegerMaps().
{
                 Map<Property, Integer> result = new HashMap<Property, Integer>();
                 for (DataSource source: sources) {
                         result = addIntegerMaps(result,
                                         source.getHighIndegreeProperties(resourceIRI));
                 }
                 return result;
         }
getHighOutdegreeProperties()
Map<Property, Integer> getHighOutdegreeProperties (String resourceIRI)
If describeResource(String) omits properties of high outdegree, then those properties must be returned here with the count of arcs.
If high-outdegree properties are not omitted, or the resource doesn't have any, then an empty map or null may be returned. Entries with value 0 will be ignored.
Parameters
resourceIRI The IRI of the resource to be described
Returns
A map containing high-outdegree properties with number of arcs for the resource
Implements DataSource.
References MergeDataSource.addIntegerMaps().
{
                 Map<Property, Integer> result = new HashMap<Property, Integer>();
                 for (DataSource source: sources) {
                         result = addIntegerMaps(result,
                                         source.getHighOutdegreeProperties(resourceIRI));
                 }
                 return result;
         }
getIndex()
List<Resource> getIndex ()
A list of IRI resources described in this data source.
Ordering is implementation-defined. Usually a reasonable limit should be applied to the number of resources returned.
Implements DataSource.
{
                 List<Resource> result = new ArrayList<Resource>();
                 for (DataSource source: sources) {
                         System.out.println(source);
                         result.addAll(source.getIndex());
                 }
                 return result;
         }
getLabelIndex()
de.fuberlin.wiwiss.pubby.util.AutocompleteEngine<SearchRecord> getLabelIndex ()
Implements DataSource.
References SearchIndexInstance.getInstance().
{
                 System.out.println("MergeDataSource: GetLabelIndex()");
                 for(DataSource ds:sources) {
                         ds.getLabelIndex();
                 }
                 return SearchIndexInstance.getInstance();
         }
listPropertyValues()
Model listPropertyValues (String resourceIRI, Property property, boolean isInverse)
Returns a subgraph of the data source.
It lists the values of a particular property of a particular resource. Where values are blank nodes, a complete description of these anonymous resources must be included.
Parameters
resourceIRI The resource to be examined
property The property we're interested in
isInverse Are we interested in outgoing arcs (false) or incoming (true)?
Returns
A subgraph of the data source.
Implements DataSource.
References ModelUtil.mergeModels(), and ModelUtil.mergePrefixes().
{
                 Model result = ModelFactory.createDefaultModel();
                 for (DataSource source: sources) {
                         ModelUtil.mergeModels(result,
                                         source.listPropertyValues(resourceIRI, property, isInverse));
                 }
                 ModelUtil.mergePrefixes(result, mustHavePrefixes);
                 return result;
         }
Member Data Documentation
MAX_INDEX_SIZE
final int MAX_INDEX_SIZE = 1000000 static inherited
Referenced by ModelDataSource.getIndex(), RemoteSPARQLDataSource.getIndex(), ModelDataSource.getLabelIndex(), and RemoteSPARQLDataSource.getLabelIndex().
mustHavePrefixes
final PrefixMapping mustHavePrefixes private
Referenced by MergeDataSource.MergeDataSource().
sources
final Collection<DataSource> sources
Referenced by MergeDataSource.MergeDataSource().