GeoPubby: ContentTypeNegotiator Class Reference
ContentTypeNegotiator Class Reference
Classes
class AcceptHeaderOverride
class Negotiation
class VariantSpec
Public Member Functions
VariantSpec addVariant (String mediaType)
void setDefaultAccept (String accept)
Sets an Accept header to be used as the default if a client does not send an Accept header, or if the Accept header cannot be parsed.
void addUserAgentOverride (Pattern userAgentString, String originalAcceptHeader, String newAcceptHeader)
Overrides the Accept header for certain user agents.
MediaRangeSpec getBestMatch (String accept)
MediaRangeSpec getBestMatch (String accept, String userAgent)
Private Member Functions
List< MediaRangeSpec > toAcceptRanges (String accept)
Private Attributes
List< VariantSpec > variantSpecs = new ArrayList<VariantSpec>()
List< MediaRangeSpec > defaultAcceptRanges
List< AcceptHeaderOverride > userAgentOverrides
Member Function Documentation
addUserAgentOverride()
void addUserAgentOverride (Pattern userAgentString, String originalAcceptHeader, String newAcceptHeader)
Overrides the Accept header for certain user agents.
This can be used to implement special-case handling for user agents that send faulty Accept headers.
Parameters
userAgentString A pattern to be matched against the User-Agent header; null means regardless of User-Agent
originalAcceptHeader Only override the Accept header if the user agent sends this header; null means always override
newAcceptHeader The Accept header to be used instead
{
                 this.userAgentOverrides.add(new AcceptHeaderOverride(
                                 userAgentString, originalAcceptHeader, newAcceptHeader));
         }
Referenced by PubbyNegotiator.[static initializer](), and ContentTypeNegotiatorTest.testUserAgentOverrideSimple().
addVariant()
VariantSpec addVariant (String mediaType)
{
                 VariantSpec result = new VariantSpec(mediaType);
                 variantSpecs.add(result);
                 return result;
         }
References ContentTypeNegotiator.variantSpecs.
Referenced by PubbyNegotiator.[static initializer](), ContentTypeNegotiatorTest.testAcceptAlias(), ContentTypeNegotiatorTest.testDefaultToHigherQuality(), ContentTypeNegotiatorTest.testEmptyHeader(), ContentTypeNegotiatorTest.testEmptyHeaderPickBestQuality(), ContentTypeNegotiatorTest.testMatchSimple(), ContentTypeNegotiatorTest.testNoMatch(), ContentTypeNegotiatorTest.testNoMatchIfBestEqualsZero(), ContentTypeNegotiatorTest.testPickCorrectMatchSimple(), ContentTypeNegotiatorTest.testPickCorrectMatchWithClientQuality(), ContentTypeNegotiatorTest.testPickCorrectMatchWithServerQuality1(), ContentTypeNegotiatorTest.testPickCorrectMatchWithServerQuality2(), ContentTypeNegotiatorTest.testPickFirstIfTwoEqualOptions(), ContentTypeNegotiatorTest.testQualityMultiplication(), ContentTypeNegotiatorTest.testSpecifyDefaultAccept(), ContentTypeNegotiatorTest.testUseAliasQuality(), ContentTypeNegotiatorTest.testUseDefaultIfNoMatch(), ContentTypeNegotiatorTest.testUseDefaultIfTwoEqualOptions(), and ContentTypeNegotiatorTest.testUserAgentOverrideSimple().
getBestMatch() [1/2]
MediaRangeSpec getBestMatch (String accept)
{
                 return getBestMatch(accept, null);
         }
Referenced by WebURIServlet.doGet(), ModelResponse.doResponseModel(), ContentTypeNegotiatorTest.testAcceptAlias(), PubbyNegotiatorTest.testAcceptEverythingGetsHTML(), PubbyNegotiatorTest.testAcceptHTML(), PubbyNegotiatorTest.testAcceptJSON(), PubbyNegotiatorTest.testAcceptRDFXML(), PubbyNegotiatorTest.testAcceptXHTMLGetsHTML(), PubbyNegotiatorTest.testAcceptXMLGetsRDFXML(), PubbyNegotiatorTest.testBrowsersGetHTML(), PubbyNegotiatorTest.testDataURIDefaultsToN3ForFirefox(), PubbyNegotiatorTest.testDataURIDefaultsToN3ForSafari(), ContentTypeNegotiatorTest.testDefaultToHigherQuality(), ContentTypeNegotiatorTest.testEmptyHeader(), ContentTypeNegotiatorTest.testEmptyHeaderPickBestQuality(), PubbyNegotiatorTest.testFirefox3GetsHTML(), PubbyNegotiatorTest.testGetN3(), PubbyNegotiatorTest.testGetNTriples(), PubbyNegotiatorTest.testGetTurtle(), ContentTypeNegotiatorTest.testMatchSimple(), PubbyNegotiatorTest.testNoAcceptGetsHTML(), ContentTypeNegotiatorTest.testNoMatch(), ContentTypeNegotiatorTest.testNoMatchIfBestEqualsZero(), ContentTypeNegotiatorTest.testNoVariantOnServer(), ContentTypeNegotiatorTest.testPickCorrectMatchSimple(), ContentTypeNegotiatorTest.testPickCorrectMatchWithClientQuality(), ContentTypeNegotiatorTest.testPickCorrectMatchWithServerQuality1(), ContentTypeNegotiatorTest.testPickCorrectMatchWithServerQuality2(), ContentTypeNegotiatorTest.testPickFirstIfTwoEqualOptions(), ContentTypeNegotiatorTest.testQualityMultiplication(), PubbyNegotiatorTest.testSafariGetsHTML(), ContentTypeNegotiatorTest.testSpecifyDefaultAccept(), PubbyNegotiatorTest.testTabulatorGetsRDF(), ContentTypeNegotiatorTest.testUseAliasQuality(), ContentTypeNegotiatorTest.testUseDefaultIfNoMatch(), ContentTypeNegotiatorTest.testUseDefaultIfTwoEqualOptions(), and ContentTypeNegotiatorTest.testUserAgentOverrideSimple().
getBestMatch() [2/2]
MediaRangeSpec getBestMatch (String accept, String userAgent)
{
                 if (userAgent == null) {
                         userAgent = "";
                 }
                 Iterator<AcceptHeaderOverride> it = userAgentOverrides.iterator();
                 String overriddenAccept = accept;
                 while (it.hasNext()) {
                         AcceptHeaderOverride override = (AcceptHeaderOverride) it.next();
                         if (override.matches(accept, userAgent)) {
                                 overriddenAccept = override.getReplacement();
                         }
                 }
                 return new Negotiation(toAcceptRanges(overriddenAccept)).negotiate();
         }
References ContentTypeNegotiator.AcceptHeaderOverride.getReplacement(), ContentTypeNegotiator.Negotiation.negotiate(), ContentTypeNegotiator.toAcceptRanges(), and ContentTypeNegotiator.userAgentOverrides.
setDefaultAccept()
void setDefaultAccept (String accept)
Sets an Accept header to be used as the default if a client does not send an Accept header, or if the Accept header cannot be parsed.
Defaults to "* / *".
{
                 this.defaultAcceptRanges = MediaRangeSpec.parseAccept(accept);
         }
References MediaRangeSpec.parseAccept().
Referenced by PubbyNegotiator.[static initializer](), and ContentTypeNegotiatorTest.testSpecifyDefaultAccept().
toAcceptRanges()
List<MediaRangeSpec> toAcceptRanges (String accept) private
{
                 if (accept == null) {
                         return defaultAcceptRanges;
                 }
                 List<MediaRangeSpec> result = MediaRangeSpec.parseAccept(accept);
                 if (result.isEmpty()) {
                         return defaultAcceptRanges;
                 }
                 return result;
         }
References ContentTypeNegotiator.defaultAcceptRanges, and MediaRangeSpec.parseAccept().
Referenced by ContentTypeNegotiator.getBestMatch().
Member Data Documentation
defaultAcceptRanges
List<MediaRangeSpec> defaultAcceptRanges private
Initial value:
=
                Collections.singletonList(MediaRangeSpec.parseRange("*/*"))
Referenced by ContentTypeNegotiator.toAcceptRanges().
userAgentOverrides
List<AcceptHeaderOverride> userAgentOverrides private
Initial value:
=
                        new ArrayList<AcceptHeaderOverride>()
Referenced by ContentTypeNegotiator.getBestMatch().
variantSpecs
List<VariantSpec> variantSpecs = new ArrayList<VariantSpec>() private
Referenced by ContentTypeNegotiator.addVariant(), and ContentTypeNegotiator.Negotiation.negotiate().