GeoPubby: ResourceDescription Class Reference
ResourceDescription Class Reference
A convenient interface to an RDF description of a resource.
Classes
class PropertyBuilder
class ResourceProperty
class Value
Public Member Functions
ResourceDescription (HypermediaControls controller, Model model, Configuration config)
Constructor for this class.
List< Geometry > getGeoms ()
Gets the list of geometries existing at the current resource.
String getEPSG ()
Gets the EPSG code from a statement if it is annotated using an EPSG statement.
StyleObject getStyle ()
Gets the EPSG code from a statement if it is annotated using an EPSG statement.
ResourceDescription (HypermediaControls controller, Model model, Map< Property, Integer > highIndegreeProperties, Map< Property, Integer > highOutdegreeProperties, Configuration config)
String getURI ()
Model getModel ()
String getTitle ()
If getLabel() is non null, return the label.
Literal getLabel ()
String getComment ()
String getImageURL ()
ResourceProperty getProperty (Property property, boolean isInverse)
List< ResourceProperty > getProperties ()
String toSentenceCase (String s, String lang)
Converts a string to Sentence Case.
String toTitleCase (String s, String lang)
Converts a string to Title Case.
Private Member Functions
void addPoint (final Resource r)
Adds a point described by a longitude and latitude coordinate to the list of geometries.
void addGeometry2 (final Literal literall)
Adds a geometry given as a WKT literal and extracts an EPSG code if annotated.
void addGeometryGeoJSON (final Literal literall)
Adds a geometry described using a GeoJSON literal.
void addGeometry (final Resource r)
Adds a geometry described using a WKT literal.
void addAllGeoms ()
Adds geometries to GeoPubby considering a list of geo properties with different literal types.
ResourceDescription (HypermediaControls controller, Model model, Map< Property, Integer > highIndegreeProperties, Map< Property, Integer > highOutdegreeProperties, Configuration config, boolean learnHighDegreeProps)
ResourceDescription (Resource resource, Model model, Configuration config)
List< ResourceProperty > buildProperties ()
boolean isEmptyLiteral (RDFNode node)
Checks whether a node is an empty literal that should better be skipped.
PrefixMapping getPrefixes ()
Returns a prefix mapping containing all prefixes from the input model and from the configuration, with the configuration taking precedence.
Collection< RDFNode > getValuesFromMultipleProperties (Collection< Property > properties)
Literal getBestLanguageMatch (Collection< RDFNode > nodes, String lang)
String normalizeWhitespace (String s, boolean squash)
void learnHighDegreeProperties (boolean isInverse, int limit)
Private Attributes
final HypermediaControls hypermediaResource
final Model model
final Resource resource
final Configuration config
final Map< Property, Integer > highIndegreeProperties
final Map< Property, Integer > highOutdegreeProperties
PrefixMapping prefixes = null
List< ResourceProperty > properties = null
List< Geometry > geoms
List of extracted geometries per resource.
WKTReader reader =new WKTReader()
WKTReader to read WKT literals.
GeometryFactory fac =new GeometryFactory()
Static Private Attributes
static final int HIGH_DEGREE_CUTOFF = 10
static Pattern wordPattern = Pattern.compile("[^ \t\r\n-]+|")
static Pattern camelCaseBoundaryPattern
static Pattern english = Pattern.compile("^en(-.*)?$", Pattern.CASE_INSENSITIVE)
static Set< String > englishUncapitalizedWords
Detailed Description
A convenient interface to an RDF description of a resource.
Provides access to its label, a textual comment, detailed representations of its properties, and so on.
TODO: Sort out who constructs these. Perhaps only the data source and this class itself should?
Constructor & Destructor Documentation
ResourceDescription() [1/4]
ResourceDescription (HypermediaControls controller, Model model, Configuration config)
Constructor for this class.
Parameters
controller
model
config
{
                 this(controller, model, null, null, config, false);
         }
References ResourceDescription.config, and ResourceDescription.model.
Referenced by ResourceDescription.PropertyBuilder.addValue(), and ResourceDescription.Value.getLabel().
ResourceDescription() [2/4]
ResourceDescription (HypermediaControls controller, Model model, Map< Property, Integer > highIndegreeProperties, Map< Property, Integer > highOutdegreeProperties, Configuration config)
{
                 this(controller, model, highIndegreeProperties, highOutdegreeProperties, config, true);
         }
References ResourceDescription.config, ResourceDescription.highIndegreeProperties, ResourceDescription.highOutdegreeProperties, and ResourceDescription.model.
ResourceDescription() [3/4]
ResourceDescription (HypermediaControls controller, Model model, Map< Property, Integer > highIndegreeProperties, Map< Property, Integer > highOutdegreeProperties, Configuration config, boolean learnHighDegreeProps) private
{
                 this.hypermediaResource = controller;
                 this.model = model;
                 this.resource = model.getResource(controller.getAbsoluteIRI());
                 this.config = config;
                 this.highIndegreeProperties = highIndegreeProperties == null ?
                                 Collections.<Property, Integer>emptyMap() : highIndegreeProperties;
                 this.highOutdegreeProperties = highOutdegreeProperties == null ?
                                 Collections.<Property, Integer>emptyMap() : highOutdegreeProperties;
                 if (learnHighDegreeProps) {
                         learnHighDegreeProperties(true, HIGH_DEGREE_CUTOFF);
                         learnHighDegreeProperties(false, HIGH_DEGREE_CUTOFF);
                 }
         }
References ResourceDescription.config, HypermediaControls.getAbsoluteIRI(), ResourceDescription.HIGH_DEGREE_CUTOFF, ResourceDescription.highIndegreeProperties, ResourceDescription.highOutdegreeProperties, ResourceDescription.learnHighDegreeProperties(), and ResourceDescription.model.
ResourceDescription() [4/4]
ResourceDescription (Resource resource, Model model, Configuration config) private
{
                 this.hypermediaResource = null;
                 this.model = model;
                 this.resource = resource;
                 this.config = config;
                 this.highIndegreeProperties = Collections.<Property, Integer>emptyMap();
                 this.highOutdegreeProperties = Collections.<Property, Integer>emptyMap();
         }
References ResourceDescription.config, ResourceDescription.model, and ResourceDescription.resource.
Member Function Documentation
addAllGeoms()
void addAllGeoms () private
Adds geometries to GeoPubby considering a list of geo properties with different literal types.
{
                 StmtIterator it= resource.listProperties(GEO.ASWKT);
                 while(it.hasNext()) {
                     Statement s = it.nextStatement();
                     if ( !s.getObject().isAnon() ) {
                         addGeometry2(s.getObject().asLiteral());
                     }
                 }
                 it.close();
                 it= resource.listProperties(GEO.ASGEOJSON);
                 while(it.hasNext()) {
                     Statement s = it.nextStatement();
                     if ( !s.getObject().isAnon() ) {
                         addGeometryGeoJSON(s.getObject().asLiteral());
                     }
                 }
                 it.close();
                         it= resource.listProperties(GEO.LOCATION);
                 while(it.hasNext()) {
                     Statement s = it.nextStatement();
                     if ( !s.getObject().isAnon() ) {
                         addPoint(s.getObject().asResource());
                     }
                 }
                 it.close();
                 it= resource.listProperties(GEO.HASGEOMETRY);
                 while(it.hasNext()) {
                     Statement s = it.nextStatement();
                     if(s.getObject().isURIResource()) {
                         addGeometry(s.getObject().asResource());
                     }
                 }
                 it.close();
                 it= resource.listProperties(GEO.P_GEOMETRY);
                 while(it.hasNext()) {
                     Statement s = it.nextStatement();
                     if(s.getObject().isURIResource()) {
                         addGeometry(s.getObject().asResource());
                     }
                 }
                 it.close();
                 addPoint(resource);
             }
References ResourceDescription.addGeometry(), ResourceDescription.addGeometry2(), ResourceDescription.addGeometryGeoJSON(), ResourceDescription.addPoint(), GEO.ASGEOJSON, GEO.ASWKT, GEO.HASGEOMETRY, GEO.LOCATION, GEO.P_GEOMETRY, and ResourceDescription.resource.
Referenced by ResourceDescription.getGeoms().
addGeometry()
void addGeometry (final Resource r) private
Adds a geometry described using a WKT literal.
Parameters
r the literal to analyze
{
                 StmtIterator it= resource.listProperties(GEO.ASWKT);
                 while(it.hasNext()) {
                     addGeometry2(it.next().getObject().asLiteral());
                 }
                 it.close();
          }
References ResourceDescription.addGeometry2(), GEO.ASWKT, and ResourceDescription.resource.
Referenced by ResourceDescription.addAllGeoms().
addGeometry2()
void addGeometry2 (final Literal literall) private
Adds a geometry given as a WKT literal and extracts an EPSG code if annotated.
Parameters
literall the literal to analyze
{
                                 String literal=literall.getString();
                                 System.out.println("Geometry2: "+literal);
                         Geometry geom;
                                 try {
                                         String epsgcode="";
                                         if(literal.startsWith("<")) {
                                                 epsgcode=literal.substring(literal.indexOf('<'),literal.lastIndexOf('>')).trim();
                                                 epsgcode=epsgcode.substring(epsgcode.lastIndexOf('/')+1);
                                                 literal=literal.substring(literal.lastIndexOf('>')+1).trim();
                                         }
                                         geom = this.reader.read(literal);
                                         if(!epsgcode.isEmpty())
                                                 geom.setSRID(Integer.valueOf(epsgcode));
                                 geoms.add(geom);
                                 } catch (ParseException e) {
                                         e.printStackTrace();
                                 }
             }
References ResourceDescription.geoms.
Referenced by ResourceDescription.addAllGeoms(), and ResourceDescription.addGeometry().
addGeometryGeoJSON()
void addGeometryGeoJSON (final Literal literall) private
Adds a geometry described using a GeoJSON literal.
Parameters
literall the literal to analyze
{
                         String literal=literall.getString();
                         System.out.println("GeometryGeoJSON: "+literal);
                         GeoJSONReader reader=new GeoJSONReader();
                         if(literal!=null) {
                                 try {
                                 Geometry geom=reader.read(literal);
                                 geoms.add(geom);
                                 }catch(RuntimeException e) {
                                         e.printStackTrace();
                                 }
                         }
          }
References ResourceDescription.geoms, and ResourceDescription.reader.
Referenced by ResourceDescription.addAllGeoms().
addPoint()
void addPoint (final Resource r) private
Adds a point described by a longitude and latitude coordinate to the list of geometries.
Parameters
r the resource to analyze
{
                 final Statement lngS = r.getProperty(GEO.P_LONG);
                 final Statement latS = r.getProperty(GEO.P_LAT);
                 if ( lngS != null || latS != null ) {
                         geoms.add(fac.createPoint(new Coordinate(lngS.getObject().asLiteral().getDouble(),
                                         latS.getObject().asLiteral().getDouble())));
                 }
             }
References ResourceDescription.fac, ResourceDescription.geoms, GEO.P_LAT, and GEO.P_LONG.
Referenced by ResourceDescription.addAllGeoms().
buildProperties()
List<ResourceProperty> buildProperties () private
{
                 Map<String,PropertyBuilder> propertyBuilders =
                                 new HashMap<String,PropertyBuilder>();
                 StmtIterator it = resource.listProperties();
                 while (it.hasNext()) {
                         Statement stmt = it.nextStatement();
                         if (isEmptyLiteral(stmt.getObject())) continue;
                         Property predicate = stmt.getPredicate();
                         String key = "=>" + predicate;
                         if (!propertyBuilders.containsKey(key)) {
                                 propertyBuilders.put(key, new PropertyBuilder(
                                                 predicate, false, config.getVocabularyStore()));
                         }
                         // TODO: Should distinguish clearly here between adding a
                         //       simple value, adding a complex (inlined) value, and
                         //       omitting a value. But how to decide whether blank nodes
                         //       are omitted or included as complex value? The decision has
                         //       already been made earlier when the model was built.
                         propertyBuilders.get(key).addValue(stmt.getObject());
                 }
                 it = model.listStatements(null, null, resource);
                 while (it.hasNext()) {
                         Statement stmt = it.nextStatement();
                         Property predicate = stmt.getPredicate();
                         String key = "<=" + predicate;
                         if (!propertyBuilders.containsKey(key)) {
                                 propertyBuilders.put(key, new PropertyBuilder(
                                                 predicate, true, config.getVocabularyStore()));
                         }
                         // TODO: See TODO above
                         propertyBuilders.get(key).addValue(stmt.getSubject());
                 }
                 for (Property p: highIndegreeProperties.keySet()) {
                         String key = "<=" + p;
                         if (!propertyBuilders.containsKey(key)) {
                                 propertyBuilders.put(key, new PropertyBuilder(
                                                 p, true, config.getVocabularyStore()));
                         }
                         propertyBuilders.get(key).addHighDegreeArcs(highIndegreeProperties.get(p));
                 }
                 for (Property p: highOutdegreeProperties.keySet()) {
                         String key = "=>" + p;
                         if (!propertyBuilders.containsKey(key)) {
                                 propertyBuilders.put(key, new PropertyBuilder(
                                                 p, false, config.getVocabularyStore()));
                         }
                         propertyBuilders.get(key).addHighDegreeArcs(highOutdegreeProperties.get(p));
                 }
                 List<ResourceProperty> results = new ArrayList<ResourceProperty>();
                 Iterator<PropertyBuilder> it2 = propertyBuilders.values().iterator();
                 while (it2.hasNext()) {
                         PropertyBuilder propertyBuilder = (PropertyBuilder) it2.next();
                         results.add(propertyBuilder.toProperty());
                 }
                 System.out.println("Build properties finished!");
                 Collections.sort(results);
                 return results;
         }
References ResourceDescription.config, Configuration.getVocabularyStore(), ResourceDescription.highIndegreeProperties, ResourceDescription.highOutdegreeProperties, ResourceDescription.isEmptyLiteral(), ResourceDescription.model, ResourceDescription.resource, and ResourceDescription.PropertyBuilder.toProperty().
Referenced by ResourceDescription.getProperties().
getBestLanguageMatch()
Literal getBestLanguageMatch (Collection< RDFNode > nodes, String lang) private
{
                 Iterator<RDFNode> it = nodes.iterator();
                 Literal aLiteral = null;
                 while (it.hasNext()) {
                         RDFNode candidate = it.next();
                         if (!candidate.isLiteral()) continue;
                         Literal literal = candidate.asLiteral();
                         if (lang == null
                                         || lang.equals(literal.getLanguage())) {
                                 return literal;
                         }
                         aLiteral = literal;
                 }
                 return aLiteral;
         }
Referenced by ResourceDescription.getComment(), and ResourceDescription.getLabel().
getComment()
String getComment ()
{
                 Collection<RDFNode> candidates = getValuesFromMultipleProperties(config.getCommentProperties());
                 Literal l = getBestLanguageMatch(candidates, config.getDefaultLanguage());
                 if (l == null) return null;
                 return toSentenceCase(l.getLexicalForm(), l.getLanguage());
         }
References ResourceDescription.config, ResourceDescription.getBestLanguageMatch(), Configuration.getCommentProperties(), Configuration.getDefaultLanguage(), ResourceDescription.getValuesFromMultipleProperties(), and ResourceDescription.toSentenceCase().
Referenced by PageURLServlet.doGet().
getEPSG()
String getEPSG ()
Gets the EPSG code from a statement if it is annotated using an EPSG statement.
Returns
The EPSG code as String
{
             StmtIterator it= resource.listProperties(GEO.EPSG);
             if(it.hasNext()){
                 Statement s = it.nextStatement();
                 return s.getObject().asLiteral().getString();
             }
             return "";
         }
References GEO.EPSG, and ResourceDescription.resource.
Referenced by PageURLServlet.doGet().
getGeoms()
List<Geometry> getGeoms ()
Gets the list of geometries existing at the current resource.
Returns
The list of geometries
{
                 if (geoms == null) {
                     geoms = new ArrayList<Geometry>();
                     addAllGeoms();
                 }
                 return geoms;
             }
References ResourceDescription.addAllGeoms(), and ResourceDescription.geoms.
Referenced by PageURLServlet.doGet().
getImageURL()
String getImageURL ()
{
                 Collection<RDFNode> candidates = getValuesFromMultipleProperties(config.getImageProperties());
                 Iterator<RDFNode> it = candidates.iterator();
                 while (it.hasNext()) {
                         RDFNode candidate = (RDFNode) it.next();
                         if (candidate.isURIResource()) {
                                 return ((Resource) candidate.as(Resource.class)).getURI();
                         }
                 }
                 return null;
         }
References ResourceDescription.config, Configuration.getImageProperties(), ResourceDescription.getURI(), and ResourceDescription.getValuesFromMultipleProperties().
Referenced by PageURLServlet.doGet().
getLabel()
Literal getLabel ()
{
                 Collection<RDFNode> candidates = getValuesFromMultipleProperties(config.getLabelProperties());
                 return getBestLanguageMatch(candidates, config.getDefaultLanguage());
         }
References ResourceDescription.config, ResourceDescription.getBestLanguageMatch(), Configuration.getDefaultLanguage(), Configuration.getLabelProperties(), and ResourceDescription.getValuesFromMultipleProperties().
Referenced by ResourceDescription.getTitle().
getModel()
Model getModel ()
{
                 return model;
         }
References ResourceDescription.model.
Referenced by ResourceDescription.PropertyBuilder.addValue(), PageURLServlet.doGet(), DataURLServlet.doGet(), and ValuesURLServlet.doGet().
getPrefixes()
PrefixMapping getPrefixes () private
Returns a prefix mapping containing all prefixes from the input model and from the configuration, with the configuration taking precedence.
{
                 if (prefixes == null) {
                         prefixes = new PrefixMappingImpl();
                         prefixes.setNsPrefixes(model);
                         for (String prefix: config.getPrefixes().getNsPrefixMap().keySet()) {
                                 prefixes.setNsPrefix(prefix, config.getPrefixes().getNsPrefixURI(prefix));
                         }
                 }
                 return prefixes;
         }
References ResourceDescription.config, Configuration.getPrefixes(), ResourceDescription.model, and ResourceDescription.prefixes.
Referenced by ResourceDescription.Value.getDatatypeLabel(), ResourceDescription.getTitle(), ResourceDescription.ResourceProperty.ResourceProperty(), and ResourceDescription.Value.Value().
getProperties()
List<ResourceProperty> getProperties ()
{
                 if (properties == null) {
                         properties = buildProperties();
                 }
                 return properties;
         }
References ResourceDescription.buildProperties(), and ResourceDescription.properties.
Referenced by PageURLServlet.doGet(), and ResourceDescription.getProperty().
getProperty()
ResourceProperty getProperty (Property property, boolean isInverse)
{
                 for (ResourceProperty p: getProperties()) {
                         if (p.getURI().equals(property.getURI()) && p.isInverse() == isInverse) {
                                 return p;
                         }
                 }
                 return null;
         }
References ResourceDescription.getProperties().
Referenced by ValuesDataURLServlet.doGet(), and ValuesURLServlet.doGet().
getStyle()
StyleObject getStyle ()
Gets the EPSG code from a statement if it is annotated using an EPSG statement.
Returns
The EPSG code as String
{
             StmtIterator it= resource.listProperties(GEO.STYLE);
             if(it.hasNext()){
                 Statement s = it.nextStatement();
                 //if(s.getObject().isResource()) {
                         StyleObject obj=GeoModelWriter.handleStyle(s.getSubject());
                         return obj;
                 //}
             }
             return null;
         }
References GeoModelWriter.handleStyle(), ResourceDescription.resource, and GEO.STYLE.
Referenced by PageURLServlet.doGet().
getTitle()
String getTitle ()
If getLabel() is non null, return the label.
If it is null, generate an attempt at a human-readable title from the URI. If the resource is blank, return null.
{
                 if (!resource.isResource()) return null;
                 Literal l = getLabel();
                 String label = l == null ? null : l.getLexicalForm();
                 String lang = l == null ? null : l.getLanguage();
                 if (label == null) {
                         label = new URIPrefixer(resource, getPrefixes()).getLocalName();
                 }
                 if ("".equals(label)) { // Prefix mapping assigns an empty local name
                         label = resource.getURI();
                         lang = null;
                 }
                 return toTitleCase(label, lang);
         }
References ResourceDescription.getLabel(), URIPrefixer.getLocalName(), ResourceDescription.getPrefixes(), ResourceDescription.resource, and ResourceDescription.toTitleCase().
Referenced by ValuesDataURLServlet.doGet(), PageURLServlet.doGet(), DataURLServlet.doGet(), and ValuesURLServlet.doGet().
getURI()
String getURI ()
{
                 return resource.getURI();
         }
References ResourceDescription.resource.
Referenced by PageURLServlet.doGet(), ValuesURLServlet.doGet(), and ResourceDescription.getImageURL().
getValuesFromMultipleProperties()
Collection<RDFNode> getValuesFromMultipleProperties (Collection< Property > properties) private
{
                 Collection<RDFNode> results = new ArrayList<RDFNode>();
                 Iterator<Property> it = properties.iterator();
                 while (it.hasNext()) {
                         org.apache.jena.rdf.model.Property property = (org.apache.jena.rdf.model.Property) it.next();
                         StmtIterator labelIt = resource.listProperties(property);
                         while (labelIt.hasNext()) {
                                 RDFNode label = labelIt.nextStatement().getObject();
                                 results.add(label);
                         }
                 }
                 return results;
         }
References ResourceDescription.properties, and ResourceDescription.resource.
Referenced by ResourceDescription.getComment(), ResourceDescription.getImageURL(), and ResourceDescription.getLabel().
isEmptyLiteral()
boolean isEmptyLiteral (RDFNode node) private
Checks whether a node is an empty literal that should better be skipped.
The logic is that those literals are probably an error on the data producer side and are best not shown to the user in HTML views.
{
                 if (!node.isLiteral()) return false;
                 Literal l = node.asLiteral();
                 if (l.getDatatypeURI() == null ||
                                 l.getDatatypeURI().startsWith(RDF.getURI()) ||
                                 l.getDatatypeURI().startsWith(XSD.getURI())) {
                         if ("".equals(l.getLexicalForm())) return true;
                 }
                 return false;
         }
Referenced by ResourceDescription.buildProperties().
learnHighDegreeProperties()
void learnHighDegreeProperties (boolean isInverse, int limit) private
{
                 CachedPropertyCollection knownHighProps = isInverse
                                 ? config.getVocabularyStore().getHighIndegreeProperties()
                                 : config.getVocabularyStore().getHighOutdegreeProperties();
                 Map<Property, Integer> highCounts = isInverse
                                 ? highIndegreeProperties
                                 : highOutdegreeProperties;
                 StmtIterator it = isInverse
                                 ? model.listStatements(null, null, resource)
                                 : resource.listProperties();
                 Map<Property, Integer> valueCounts = new HashMap<Property, Integer>();
                 while (it.hasNext()) {
                         Property p = it.next().getPredicate();
                         if (!valueCounts.containsKey(p)) {
                                 valueCounts.put(p, 0);
                         }
                         valueCounts.put(p, valueCounts.get(p) + 1);
                 }
                 for (Property p: valueCounts.keySet()) {
                         if (valueCounts.get(p) <= limit) continue;
                         knownHighProps.reportAdditional(p);
                         if (isInverse) {
                                 model.removeAll(null, p, resource);
                         } else {
                                 resource.removeAll(p);
                         }
                         highCounts.put(p, valueCounts.get(p));
                 }
         }
References ResourceDescription.config, VocabularyStore.getHighIndegreeProperties(), VocabularyStore.getHighOutdegreeProperties(), Configuration.getVocabularyStore(), ResourceDescription.highIndegreeProperties, ResourceDescription.highOutdegreeProperties, ResourceDescription.model, VocabularyStore.CachedPropertyCollection.reportAdditional(), and ResourceDescription.resource.
Referenced by ResourceDescription.ResourceDescription().
normalizeWhitespace()
String normalizeWhitespace (String s, boolean squash) private
{
                 s = s.replaceAll("[ \t\r\n]+", " ");
                 if (squash && " ".equals(s)) return "";
                 return s;
         }
Referenced by ResourceDescription.toTitleCase().
toSentenceCase()
String toSentenceCase (String s, String lang)
Converts a string to Sentence Case.
In our implementation, this simply means the first letter is uppercased if it isn't already. Also trims surrounding whitespace.
{
                 if (s == null) return null;
                 s = s.trim();
                 if ("".equals(s)) return null;
                 return s.substring(0, 1).toUpperCase() + s.substring(1);
         }
Referenced by ResourceDescription.getComment().
toTitleCase()
String toTitleCase (String s, String lang)
Converts a string to Title Case.
Also trims surrounding whitespace and collapses consecutive whitespace characters within into a single space. If the language is English or null, English rules are used. Also splits CamelCase into separate words to better deal with poor labels.
{
                 if (s == null) return null;
                 if (lang == null) {
                         lang = config.getDefaultLanguage();
                 }
                 s = camelCaseBoundaryPattern.matcher(s).replaceAll(" ");
                 s = s.replace(" - ", " \u2013 ");
                 Set<String> uncapitalizedWords = Collections.emptySet();
                 if (lang == null || "".equals(lang) || english.matcher(lang).matches()) {
                         uncapitalizedWords = englishUncapitalizedWords;
                 }
                 StringBuffer result = new StringBuffer();
                 Matcher matcher = wordPattern.matcher(s);
                 boolean first = true;
                 int offset = 0;
                 while (matcher.find()) {
                         result.append(normalizeWhitespace(
                                         s.substring(offset, matcher.start()), first));
                         offset = matcher.end();
                         String word = matcher.group();
                         if ("".equals(word)) continue;
                         /*if (first || !uncapitalizedWords.contains(word.toLowerCase())) {
                                 word = word.substring(0, 1).toUpperCase() + word.substring(1);
                         } else {
                                 word = word.substring(0, 1).toLowerCase() + word.substring(1);
                         }*/
                         result.append(word);
                         first = false;
                 }
                 result.append(normalizeWhitespace(
                                 s.substring(offset), true));
                 return result.toString();
         }
References ResourceDescription.camelCaseBoundaryPattern, ResourceDescription.config, ResourceDescription.english, ResourceDescription.englishUncapitalizedWords, Configuration.getDefaultLanguage(), ResourceDescription.normalizeWhitespace(), and ResourceDescription.wordPattern.
Referenced by ResourceDescription.ResourceProperty.getInverseLabel(), ResourceDescription.ResourceProperty.getLabel(), ResourceDescription.Value.getLabel(), and ResourceDescription.getTitle().
Member Data Documentation
camelCaseBoundaryPattern
Pattern camelCaseBoundaryPattern static private
Initial value:
= Pattern.compile(
                        "(?<=(\\p{javaLowerCase}|\\p{javaUpperCase})\\p{javaLowerCase})" +
                        "(?=\\p{javaUpperCase})")
Referenced by ResourceDescription.toTitleCase().
config
final Configuration config private
Referenced by ResourceDescription.PropertyBuilder.addValue(), ResourceDescription.buildProperties(), ResourceDescription.ResourceProperty.compareTo(), ResourceDescription.ResourceProperty.getBrowsableURL(), ResourceDescription.Value.getBrowsableURL(), ResourceDescription.getComment(), ResourceDescription.getImageURL(), ResourceDescription.getLabel(), ResourceDescription.Value.getLabel(), ResourceDescription.getPrefixes(), ResourceDescription.learnHighDegreeProperties(), ResourceDescription.ResourceDescription(), and ResourceDescription.toTitleCase().
english
Pattern english = Pattern.compile("^en(-.*)?$", Pattern.CASE_INSENSITIVE) static private
Referenced by ResourceDescription.toTitleCase().
englishUncapitalizedWords
Set<String> englishUncapitalizedWords static private
Initial value:
=
                        new HashSet<String>(Arrays.asList(
                                        "above", "about", "across", "against", "along", "among",
                                        "around", "at", "before", "behind", "below", "beneath",
                                        "beside", "between", "beyond", "by", "down", "during",
                                        "except", "for", "from", "in", "inside", "into", "like",
                                        "near", "of", "off", "on", "since", "to", "toward",
                                        "through", "under", "until", "up", "upon", "with", "within",
                                        "a", "an", "the",
                                        "and", "but", "for", "nor", "or", "so", "yet"
                        ))
Referenced by ResourceDescription.toTitleCase().
fac
GeometryFactory fac =new GeometryFactory() private
Referenced by ResourceDescription.addPoint().
geoms
List<Geometry> geoms private
List of extracted geometries per resource.
Referenced by ResourceDescription.addGeometry2(), ResourceDescription.addGeometryGeoJSON(), ResourceDescription.addPoint(), and ResourceDescription.getGeoms().
HIGH_DEGREE_CUTOFF
final int HIGH_DEGREE_CUTOFF = 10 static private
Referenced by ResourceDescription.ResourceDescription().
highIndegreeProperties
final Map<Property, Integer> highIndegreeProperties private
Referenced by ResourceDescription.buildProperties(), ResourceDescription.learnHighDegreeProperties(), and ResourceDescription.ResourceDescription().
highOutdegreeProperties
final Map<Property, Integer> highOutdegreeProperties private
Referenced by ResourceDescription.buildProperties(), ResourceDescription.learnHighDegreeProperties(), and ResourceDescription.ResourceDescription().
hypermediaResource
final HypermediaControls hypermediaResource private
Referenced by ResourceDescription.ResourceProperty.getValuesPageURL().
model
final Model model private
Referenced by ResourceDescription.buildProperties(), ResourceDescription.Value.getLabel(), ResourceDescription.getModel(), ResourceDescription.getPrefixes(), ResourceDescription.learnHighDegreeProperties(), and ResourceDescription.ResourceDescription().
prefixes
PrefixMapping prefixes = null private
Referenced by ResourceDescription.getPrefixes().
properties
List<ResourceProperty> properties = null private
Referenced by ResourceDescription.getProperties(), and ResourceDescription.getValuesFromMultipleProperties().
reader
WKTReader reader =new WKTReader() private
WKTReader to read WKT literals.
Referenced by ResourceDescription.addGeometryGeoJSON().
resource
final Resource resource private
Referenced by ResourceDescription.addAllGeoms(), ResourceDescription.addGeometry(), ResourceDescription.buildProperties(), ResourceDescription.getEPSG(), ResourceDescription.getStyle(), ResourceDescription.getTitle(), ResourceDescription.getURI(), ResourceDescription.getValuesFromMultipleProperties(), ResourceDescription.learnHighDegreeProperties(), and ResourceDescription.ResourceDescription().
wordPattern
Pattern wordPattern = Pattern.compile("[^ \t\r\n-]+|") static private
Referenced by ResourceDescription.toTitleCase().