GeoPubby: ResourceDescription.Value Class Reference
ResourceDescription.Value Class Reference
Public Member Functions
Value (RDFNode valueNode, Property predicate, VocabularyStore vocabularyStore)
Node getNode ()
String getBrowsableURL ()
boolean hasPrefix ()
String getPrefix ()
String getLocalName ()
String getLabel ()
String getDescription ()
String getDatatypeLabel ()
String getDatatypeURI ()
boolean isType ()
int compareTo (Value other)
Private Attributes
final RDFNode node
URIPrefixer prefixer
Property predicate
VocabularyStore vocabularyStore
Constructor & Destructor Documentation
Value()
Value (RDFNode valueNode, Property predicate, VocabularyStore vocabularyStore)
{
                         this.node = valueNode;
                         this.predicate = predicate;
                         this.vocabularyStore = vocabularyStore;
                         if (valueNode.isURIResource()) {
                                 prefixer = new URIPrefixer((Resource) valueNode.as(Resource.class), getPrefixes());
                         }
                 }
References ResourceDescription.getPrefixes(), ResourceDescription.Value.predicate, ResourceDescription.Value.prefixer, and ResourceDescription.Value.vocabularyStore.
Referenced by ResourceDescription.Value.compareTo().
Member Function Documentation
compareTo()
int compareTo (Value other)
{
                         if (!(other instanceof Value)) {
                                 return 0;
                         }
                         Value otherValue = (Value) other;
                         if (getNode().isURI() && otherValue.getNode().isURI()) {
                                 return getNode().getURI().compareTo(otherValue.getNode().getURI());
                         }
                         if (getNode().isURI()) {
                                 return 1;
                         }
                         if (otherValue.getNode().isURI()) {
                                 return -1;
                         }
                         if (getNode().isBlank() && otherValue.getNode().isBlank()) {
                                 return getNode().getBlankNodeLabel().compareTo(otherValue.getNode().getBlankNodeLabel());
                         }
                         if (getNode().isBlank()) {
                                 return 1;
                         }
                         if (otherValue.getNode().isBlank()) {
                                 return -1;
                         }
                         // TODO Typed literals, language literals
                         return getNode().getLiteralLexicalForm().compareTo(otherValue.getNode().getLiteralLexicalForm());
                 }
References ResourceDescription.Value.getNode(), and ResourceDescription.Value.Value().
getBrowsableURL()
String getBrowsableURL ()
{
                         if (!node.isURIResource()) return null;
                         HypermediaControls controls = HypermediaControls.createFromIRI(
                                         node.asResource().getURI(), config);
                         if (controls == null) return node.asResource().getURI();
                         return controls.getPageURL();
                 }
References ResourceDescription.config, HypermediaControls.createFromIRI(), HypermediaControls.getPageURL(), and ResourceDescription.Value.node.
getDatatypeLabel()
String getDatatypeLabel ()
{
                         if (!node.isLiteral()) return null;
                         String uri = ((Literal) node.as(Literal.class)).getDatatypeURI();
                         if (uri == null) return null;
                         URIPrefixer datatypePrefixer = new URIPrefixer(uri, getPrefixes());
                         if (datatypePrefixer.hasPrefix()) {
                                 return datatypePrefixer.toTurtle();
                         } else {
                                 return "?:" + datatypePrefixer.getLocalName();
                         }
                 }
References ResourceDescription.Value.getDatatypeURI(), URIPrefixer.getLocalName(), ResourceDescription.getPrefixes(), URIPrefixer.hasPrefix(), ResourceDescription.Value.node, and URIPrefixer.toTurtle().
getDatatypeURI()
String getDatatypeURI ()
{
                         if (!node.isLiteral()) return null;
                         String uri = ((Literal) node.as(Literal.class)).getDatatypeURI();
                         if (uri == null) return null;
                         return uri;
                 }
References ResourceDescription.Value.node.
Referenced by ResourceDescription.Value.getDatatypeLabel().
getDescription()
String getDescription ()
{
                         return vocabularyStore.getDescription(node.asNode().getURI()).getLexicalForm();
                 }
References VocabularyStore.getDescription(), ResourceDescription.Value.node, and ResourceDescription.Value.vocabularyStore.
getLabel()
String getLabel ()
{
                         System.out.println("Getting label for "+node.toString());
                         if (!node.isResource()) return null;
                         System.out.println(node.toString()+" is a resource!");
                         Literal result = null;
                         if (node.isURIResource()) {
                                 if (predicate.equals(RDF.type)) {
                                         // Look up class labels in vocabulary store
                                         result = vocabularyStore.getLabel(node.asNode().getURI(), false);
                                 } else if (node.isURIResource()) {
                                         // If it's not a class, see if we happen to have a label cached
                                         result = vocabularyStore.getCachedLabel(node.asResource().getURI(), false);
                                         //System.out.println("HasCachedLabel? "+result.toString());
                                 }
                         }
                         if (result == null) {
                                 // Use any label that may be included in the description model
                                 result = new ResourceDescription(node.asResource(), model, config).getLabel();
                                 //System.out.println("Resource has label? "+result.toString());
                         }
                         if (result == null) return null;
                         return toTitleCase(result.getLexicalForm(), result.getLanguage());
                 }
References ResourceDescription.config, VocabularyStore.getCachedLabel(), VocabularyStore.getLabel(), ResourceDescription.model, ResourceDescription.Value.node, ResourceDescription.Value.predicate, ResourceDescription.ResourceDescription(), ResourceDescription.toTitleCase(), and ResourceDescription.Value.vocabularyStore.
getLocalName()
String getLocalName ()
{
                         if (prefixer == null) {
                                 return null;
                         }
                         return prefixer.getLocalName();
                 }
References URIPrefixer.getLocalName(), and ResourceDescription.Value.prefixer.
getNode()
Node getNode ()
{
                         return node.asNode();
                 }
References ResourceDescription.Value.node.
Referenced by ResourceDescription.Value.compareTo().
getPrefix()
String getPrefix ()
{
                         if (prefixer == null) {
                                 return null;
                         }
                         return prefixer.getPrefix();
                 }
References URIPrefixer.getPrefix(), and ResourceDescription.Value.prefixer.
hasPrefix()
boolean hasPrefix ()
{
                         return prefixer != null && prefixer.hasPrefix();
                 }
References URIPrefixer.hasPrefix(), and ResourceDescription.Value.prefixer.
isType()
boolean isType ()
{
                         return predicate.equals(RDF.type);
                 }
References ResourceDescription.Value.predicate.
Member Data Documentation
node
final RDFNode node private
Referenced by ResourceDescription.Value.getBrowsableURL(), ResourceDescription.Value.getDatatypeLabel(), ResourceDescription.Value.getDatatypeURI(), ResourceDescription.Value.getDescription(), ResourceDescription.Value.getLabel(), and ResourceDescription.Value.getNode().
predicate
Property predicate private
Referenced by ResourceDescription.Value.getLabel(), ResourceDescription.Value.isType(), and ResourceDescription.Value.Value().
prefixer
URIPrefixer prefixer private
Referenced by ResourceDescription.Value.getLocalName(), ResourceDescription.Value.getPrefix(), ResourceDescription.Value.hasPrefix(), and ResourceDescription.Value.Value().
vocabularyStore
VocabularyStore vocabularyStore private
Referenced by ResourceDescription.Value.getDescription(), ResourceDescription.Value.getLabel(), and ResourceDescription.Value.Value().