GeoPubby: COV Class Reference
COV Class Reference
Static Public Attributes
static final String GEOSPARQLNS = "http://www.opengis.net/ont/geosparql#"
static final Property HASCOVERAGE = model.createProperty(GEOSPARQLNS + "hasCoverage")
static final Property ASHEXRASTWKB = model.createProperty(GEOSPARQLNS + "asHexRastWKB")
static final Property ASRASTWKB = model.createProperty(GEOSPARQLNS + "asRastWKB")
static final Property ASCOVERAGEJSON = model.createProperty(GEOSPARQLNS + "asCoverageJSON")
static final Property ASGMLCOV = model.createProperty(GEOSPARQLNS + "asGMLCOV")
static final Property EPSG = model.createProperty(GEOSPARQLNS + "epsg")
static List< Property > covprops =Arrays.asList(new Property[] {HASCOVERAGE,ASCOVERAGEJSON,ASGMLCOV,ASRASTWKB,ASHEXRASTWKB})
Static Private Attributes
static Model model = ModelFactory.createDefaultModel()
Member Data Documentation
ASCOVERAGEJSON
final Property ASCOVERAGEJSON = model.createProperty(GEOSPARQLNS + "asCoverageJSON") static
Referenced by CoverageModelWriter.handleCoverage().
ASGMLCOV
final Property ASGMLCOV = model.createProperty(GEOSPARQLNS + "asGMLCOV") static
Referenced by CoverageModelWriter.handleCoverage().
ASHEXRASTWKB
final Property ASHEXRASTWKB = model.createProperty(GEOSPARQLNS + "asHexRastWKB") static
Referenced by CoverageModelWriter.handleCoverage().
ASRASTWKB
final Property ASRASTWKB = model.createProperty(GEOSPARQLNS + "asRastWKB") static
Referenced by CoverageModelWriter.handleCoverage().
covprops
List<Property> covprops =Arrays.asList(new Property[] {HASCOVERAGE,ASCOVERAGEJSON,ASGMLCOV,ASRASTWKB,ASHEXRASTWKB}) static
EPSG
final Property EPSG = model.createProperty(GEOSPARQLNS + "epsg") static
GEOSPARQLNS
final String GEOSPARQLNS = "http://www.opengis.net/ont/geosparql#" static
HASCOVERAGE
final Property HASCOVERAGE = model.createProperty(GEOSPARQLNS + "hasCoverage") static
model
Model model = ModelFactory.createDefaultModel() static private