GeoPubby: AutocompleteEngine< T extends Indexable > Class Template Reference
AutocompleteEngine< T extends Indexable > Class Template Reference
Facade for indexing and searching Indexable elements.
Classes
class Builder
Builder for constructing AutocompleteEngine instances.
Public Member Functions
boolean add (T element)
Indexes a single element.
boolean addAll (Collection< T > elements)
Indexes a collection of elements.
boolean remove (T element)
Removes a single element.
boolean removeAll (Collection< T > elements)
Removes a collection of elements.
Collection< T > getAll ()
Gets all elements.
List< T > search (String query)
Returns a List of all elements that match a query, sorted according to the default comparator.
List< T > search (String query, int limit)
Returns a List of the top elements that match a query, sorted according to the default comparator.
Private Member Functions
AutocompleteEngine (Builder< T > builder)
Private Attributes
final Analyzer analyzer
final Comparator< ScoredObject< T > > comparator
final IndexAdapter< T > index
final Lock read
final Lock write
Detailed Description
Facade for indexing and searching Indexable elements.
Constructor & Destructor Documentation
AutocompleteEngine()
AutocompleteEngine (Builder< T > builder) private
     {
         assert builder != null;
         this.analyzer = builder.analyzer;
         this.comparator = builder.comparator;
         this.index = builder.index;
         ReadWriteLock lock = new ReentrantReadWriteLock();
         this.read = lock.readLock();
         this.write = lock.writeLock();
     }
Member Function Documentation
add()
boolean add (T element)
Indexes a single element.
Exceptions
NullPointerException if
element
is null;
Referenced by ModelDataSource.getLabelIndex(), and RemoteSPARQLDataSource.getLabelIndex().
     {
         return addAll(Arrays.asList(element));
     }
addAll()
boolean addAll (Collection< T > elements)
Indexes a collection of elements.
Exceptions
NullPointerException if
elements
is null or contains a null element;
Referenced by AutocompleteEngine< de.fuberlin.wiwiss.pubby.util.SearchRecord >.add().
     {
         checkPointer(elements != null);
         boolean result = false;
         for (T element : elements)
         {
             checkPointer(element != null);
             write.lock();
             try
             {
                 for (String field : element.getFields())
                 {
                     for (String token : analyzer.apply(field))
                     {
                         result |= index.put(token, element);
                     }
                 }
             }
             finally
             {
                 write.unlock();
             }
         }
         return result;
     }
getAll()
Collection<T> getAll ()
Gets all elements.
Exceptions
NullPointerException if
elements
is null or contains a null element;
     {
         return new LinkedList<T>();
     }
remove()
boolean remove (T element)
Removes a single element.
Exceptions
NullPointerException if
element
is null;
     {
         return removeAll(Arrays.asList(element));
     }
removeAll()
boolean removeAll (Collection< T > elements)
Removes a collection of elements.
Exceptions
NullPointerException if
elements
is null or contains a null element;
Referenced by AutocompleteEngine< de.fuberlin.wiwiss.pubby.util.SearchRecord >.remove().
     {
         checkPointer(elements != null);
         boolean result = false;
         for (T element : elements)
         {
             checkPointer(element != null);
             write.lock();
             try
             {
                 result |= index.remove(element);
             }
             finally
             {
                 write.unlock();
             }
         }
         return result;
     }
search() [1/2]
List<T> search (String query)
Returns a List of all elements that match a query, sorted according to the default comparator.
Exceptions
NullPointerException if
query
is null;
Referenced by AutocompleteEngine< de.fuberlin.wiwiss.pubby.util.SearchRecord >.search().
     {
         checkPointer(query != null);
         read.lock();
         try
         {
             Aggregator<T> aggregator = new Aggregator<>(comparator);
             Iterator<String> tokens = analyzer.apply(query).iterator();
             if (tokens.hasNext())
             {
                 aggregator.addAll(index.get(tokens.next()));
             }
             while (tokens.hasNext())
             {
                 if (aggregator.isEmpty())
                 {
                     break;
                 }
                 aggregator.retainAll(index.get(tokens.next()));
             }
             return aggregator.values();
         }
         finally
         {
             read.unlock();
         }
     }
search() [2/2]
List<T> search (String query, int limit)
Returns a List of the top elements that match a query, sorted according to the default comparator.
Exceptions
NullPointerException if
query
is null;
IllegalArgumentException if
limit
is negative;
     {
         checkArgument(limit >= 0);
         List<T> result = search(query);
         if (result.size() > limit)
         {
             return result.subList(0, limit);
         }
         return result;
     }
Member Data Documentation
analyzer
final Analyzer analyzer private
comparator
final Comparator<ScoredObject<T> > comparator private
Referenced by AutocompleteEngine< de.fuberlin.wiwiss.pubby.util.SearchRecord >.search().
index
final IndexAdapter<T> index private
read
final Lock read private
write
final Lock write private