GeoPubby: VocabularyStore.CachedPropertyCollection Class Reference
VocabularyStore.CachedPropertyCollection Class Reference
Public Member Functions
Collection< Property > get ()
void reportAdditional (Property p)
Package Functions
CachedPropertyCollection (Resource type)
Private Attributes
final Resource type
Collection< Property > cache = null
Constructor & Destructor Documentation
CachedPropertyCollection()
CachedPropertyCollection (Resource type) package
References VocabularyStore.CachedPropertyCollection.type.
{
                         this.type = type;
                 }
Member Function Documentation
get()
Collection<Property> get ()
References VocabularyStore.CachedPropertyCollection.cache, and DataSource.listPropertyValues().
Referenced by RemoteSPARQLDataSource.preProcessQuery().
{
                         if (dataSource == null) return Collections.emptyList();
                         if (cache != null) return cache;
                         cache = new ArrayList<Property>();
                         Model result = dataSource.listPropertyValues(type.getURI(), RDF.type, true);
                         StmtIterator it = result.listStatements(null, RDF.type, type);
                         while (it.hasNext()) {
                                 Resource r = it.next().getSubject();
                                 if (!r.isURIResource()) continue;
                                 cache.add(r.as(Property.class));
                         }
                         return cache;
                 }
reportAdditional()
void reportAdditional (Property p)
Referenced by ResourceDescription.learnHighDegreeProperties().
{
                         if (cache == null) get();
                         if (cache.contains(p)) return;
                         cache.add(p);
                 }
Member Data Documentation
cache
Collection<Property> cache = null private
Referenced by VocabularyStore.CachedPropertyCollection.get().
type
final Resource type private
Referenced by VocabularyStore.CachedPropertyCollection.CachedPropertyCollection().