GeoPubby: SearchIndexInstance Class Reference
SearchIndexInstance Class Reference
Static Public Member Functions
static AutocompleteEngine< SearchRecord > getInstance ()
Private Member Functions
SearchIndexInstance ()
Static Private Attributes
static AutocompleteEngine< SearchRecord > globalIndex =null
Constructor & Destructor Documentation
SearchIndexInstance()
SearchIndexInstance () private
{
                 globalIndex= new AutocompleteEngine.Builder<SearchRecord>()
                     .setIndex(new SearchAdapter())
                     .setAnalyzers(new LowerCaseTransformer(), new WordTokenizer())
                     .build();
         }
Member Function Documentation
getInstance()
static AutocompleteEngine<SearchRecord> getInstance () static
References SearchIndexInstance.globalIndex.
Referenced by ModelDataSource.getLabelIndex(), MergeDataSource.getLabelIndex(), and RemoteSPARQLDataSource.getLabelIndex().
{
                 if(globalIndex!=null) {
                         return globalIndex;
                 }
                 globalIndex= new AutocompleteEngine.Builder<SearchRecord>()
                     .setIndex(new SearchAdapter())
                     .setAnalyzers(new LowerCaseTransformer(), new WordTokenizer())
                     .build();
                 return globalIndex;
         }
Member Data Documentation
globalIndex
AutocompleteEngine<SearchRecord> globalIndex =null static private
Referenced by SearchIndexInstance.getInstance().