GeoPubby: ValuesDataURLServlet Class Reference
ValuesDataURLServlet Class Reference
A servlet for serving an RDF document describing resources related to a given resource via a given property.
Public Member Functions
boolean doGet (HypermediaControls controller, Property predicate, boolean isInverse, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException
String getDocumentTitle (String resourceLabel, String propertyLabel, boolean isInverse)
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException, ServletException
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
void init () throws ServletException
Protected Member Functions
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title)
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes)
void send404 (HttpServletResponse response, String resourceURI) throws IOException
void sendInitialization500 (HttpServletResponse response, String message) throws IOException
String addQueryString (String dataURL, HttpServletRequest request)
Private Attributes
Configuration config
String initError
Static Private Attributes
static final long serialVersionUID = -7927775670218866340L
static Pattern prefixedNamePattern = Pattern.compile("(-?)([^!:/]*):([^:/]*)/(.*)")
static Pattern fullIRIPattern = Pattern.compile("(-?)!(.*?)///(.*)")
Detailed Description
A servlet for serving an RDF document describing resources related to a given resource via a given property.
The property can be a forward or backward arc.
Member Function Documentation
addDocumentMetadata()
void addDocumentMetadata (Model model, HypermediaControls controller, String documentURL, String title) protected inherited
{
                 ModelUtil.addNSIfUndefined(model, "foaf", FOAF.getURI());
                 ModelUtil.addNSIfUndefined(model, "rdfs", RDFS.getURI());
                 // Add document metadata
                 Resource topic = model.getResource(controller.getAbsoluteIRI());
                 Resource document = model.getResource(documentURL);
                 document.addProperty(FOAF.primaryTopic, topic);
                 document.addProperty(RDFS.label, title);
                 // Add custom metadata
                 for (Dataset dataset: config.getDatasets()) {
                         MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                         metadata.addCustomMetadata(model, document);
                         metadata.addMetadataFromTemplate(model, controller);
                 }
         }
References MetadataConfiguration.addCustomMetadata(), MetadataConfiguration.addMetadataFromTemplate(), ModelUtil.addNSIfUndefined(), BaseServlet.config, HypermediaControls.getAbsoluteIRI(), and Configuration.getDatasets().
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
addPageMetadata()
void addPageMetadata (Context context, HypermediaControls controller, PrefixMapping prefixes) protected inherited
{
                 try {
                         Model metadataModel = ModelFactory.createDefaultModel();
                         for (Dataset dataset: config.getDatasets()) {
                                 MetadataConfiguration metadata = dataset.getMetadataConfiguration();
                                 Resource document = metadata.addMetadataFromTemplate(metadataModel, controller);
                                 // Replaced the commented line by the following one because the
                                 // RDF graph we want to talk about is a specific representation
                                 // of the data identified by the getDataURL() URI.
                                 //                                       Olaf, May 28, 2010
                                 // context.put("metadata", metadata.getResource(resource.getDataURL()));
                                 context.put("metadata", document);
                         }
                         Map<String,String> nsSet = metadataModel.getNsPrefixMap();
                         nsSet.putAll(prefixes.getNsPrefixMap());
                         context.put("prefixes", nsSet.entrySet());
                         context.put("blankNodesMap", new HashMap<Resource,String>());
                 }
                 catch (Exception e) {
                         context.put("metadata", Boolean.FALSE);
                 }
         }
References MetadataConfiguration.addMetadataFromTemplate(), BaseServlet.config, and Configuration.getDatasets().
Referenced by PageURLServlet.doGet(), and ValuesURLServlet.doGet().
addQueryString()
String addQueryString (String dataURL, HttpServletRequest request) protected inherited
{
                 if (request.getParameter("output") == null) {
                         return dataURL;
                 }
                 return dataURL + "?output=" + request.getParameter("output");
         }
Referenced by ValuesDataURLServlet.doGet(), and DataURLServlet.doGet().
doGet() [1/3]
void doGet (HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException inherited
{
                 if (initError != null) {
                         if(config==null) {
                                 System.out.println("Calling initConfiguration from BaseServlet!");
                                 Boolean res=ServletContextInitializer.initConfiguration(getServletContext());
                                 if(res)
                                         initError=null;
                                 else {
                                         initError=getServletContext().getAttribute(ServletContextInitializer.ERROR_MESSAGE).toString();
                                 }
                                 System.out.println("Successful result? "+res.toString());
                         }
                         config = (Configuration) getServletContext().getAttribute(
                                         ServletContextInitializer.SERVER_CONFIGURATION);
                 }
                 if(initError!=null) {
                         sendInitialization500(response, initError);
                         return;
                 }
                 String relativeURI = request.getRequestURI().substring(
                                 request.getContextPath().length() + request.getServletPath().length());
                 // Some servlet containers keep the leading slash, some don't
                 if (!"".equals(relativeURI) && "/".equals(relativeURI.substring(0, 1))) {
                         relativeURI = relativeURI.substring(1);
                 }
                 if (!doGet(relativeURI, request, response, config)) {
                         send404(response, null);
                 }
         }
References BaseServlet.config, BaseServlet.doGet(), ServletContextInitializer.ERROR_MESSAGE, ServletContextInitializer.initConfiguration(), BaseServlet.initError, BaseServlet.send404(), BaseServlet.sendInitialization500(), and ServletContextInitializer.SERVER_CONFIGURATION.
doGet() [2/3]
boolean doGet (HypermediaControls controller, Property predicate, boolean isInverse, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException
Reimplemented from ValuesBaseServlet.
{
                 // TODO: If no data ("return false"), respond with plain text like the PageURLServlet, not with HTML
                 // TODO: Good bit of duplication with ValuesURLServlet here
                 ResourceDescription resource = controller.getResourceDescription();
                 if (resource == null) return false;
                 Model descriptions = config.getDataSource().listPropertyValues(
                                 controller.getAbsoluteIRI(), predicate, isInverse);
                 if (descriptions.isEmpty()) return false;
                 ResourceProperty property = new ResourceDescription(
                                 controller, descriptions, config).getProperty(predicate, isInverse);
                 if (property == null) return false;     // Can happen if prefix is declared in URI space of a data source rather than in web space
                 addDocumentMetadata(descriptions, controller,
                                 addQueryString(
                                                 isInverse
                                                                 ? controller.getInverseValuesDataURL(predicate)
                                                                 : controller.getValuesDataURL(predicate),
                                                 request),
                                 getDocumentTitle(
                                                 resource.getTitle(), property.getCompleteLabel(), isInverse));
                 new ModelResponse(descriptions, request, response).serve();
                 return true;
         }
References BaseServlet.addDocumentMetadata(), BaseServlet.addQueryString(), BaseServlet.config, Configuration.getDataSource(), ValuesDataURLServlet.getDocumentTitle(), ResourceDescription.getProperty(), ResourceDescription.getTitle(), DataSource.listPropertyValues(), and ModelResponse.serve().
doGet() [3/3]
boolean doGet (String relativeURI, HttpServletRequest request, HttpServletResponse response, Configuration config) throws IOException, ServletException inherited
Reimplemented from BaseServlet.
{
                 boolean isInverse;
                 Property property;
                 Matcher matcher = prefixedNamePattern.matcher(relativeURI);
                 if (matcher.matches()) {
                         String prefix = matcher.group(2);
                         if (config.getPrefixes().getNsPrefixURI(prefix) == null) {
                                 return false;
                         }
                         String localName = matcher.group(3);
                         relativeURI = matcher.group(4); // Keep just last part
                         property = ResourceFactory.createProperty(
                                         config.getPrefixes().getNsPrefixURI(prefix), localName);
                 } else {
                         matcher = fullIRIPattern.matcher(relativeURI);
                         if (!matcher.matches()) {
                                 return false;
                         }
                         String propertyIRI = IRIEncoder.toIRI(
                                         PubbyIRIEscaper.unescapeSpecialCharacters(matcher.group(2)));
                         relativeURI = matcher.group(3); // Keep just last part
                         property = ResourceFactory.createProperty(propertyIRI);
                 }
                 isInverse = "-".equals(matcher.group(1));
                 HypermediaControls controller = config.getControls(relativeURI, false);
                 if (controller == null) {
                         return false;
                 }
                 return doGet(controller, property, isInverse, request, response, config);
         }
References BaseServlet.config, ValuesBaseServlet.doGet(), ValuesBaseServlet.fullIRIPattern, Configuration.getControls(), Configuration.getPrefixes(), ValuesBaseServlet.prefixedNamePattern, IRIEncoder.toIRI(), and PubbyIRIEscaper.unescapeSpecialCharacters().
getDocumentTitle()
String getDocumentTitle (String resourceLabel, String propertyLabel, boolean isInverse)
{
                 if (isInverse) {
                         return "RDF description of all resources whose " + propertyLabel + " is " + resourceLabel;
                 } else {
                         return "RDF description of all values that are " + propertyLabel + " of " + resourceLabel;
                 }
         }
Referenced by ValuesDataURLServlet.doGet().
init()
void init () throws ServletException inherited
{
                 config = (Configuration) getServletContext().getAttribute(
                                 ServletContextInitializer.SERVER_CONFIGURATION);
                         if(config==null){
                                         initError = (String) getServletContext().getAttribute(
                                         ServletContextInitializer.ERROR_MESSAGE);
                         }
         }
References BaseServlet.config, ServletContextInitializer.ERROR_MESSAGE, BaseServlet.initError, and ServletContextInitializer.SERVER_CONFIGURATION.
send404()
void send404 (HttpServletResponse response, String resourceURI) throws IOException protected inherited
{
                 response.setStatus(404);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("project_name", config.getProjectName());
                 context.put("project_link", config.getProjectLink());
                 context.put("server_base", config.getWebApplicationBaseURI());
                 context.put("title", "404 Not Found");
                 if (resourceURI != null) {
                         context.put("uri", resourceURI);
                 }
                 template.renderXHTML("404.vm");
         }
References BaseServlet.config, Configuration.getProjectLink(), Configuration.getProjectName(), and Configuration.getWebApplicationBaseURI().
Referenced by BaseServlet.doGet().
sendInitialization500()
void sendInitialization500 (HttpServletResponse response, String message) throws IOException protected inherited
{
                 response.setStatus(500);
                 VelocityHelper template = new VelocityHelper(getServletContext(), response);
                 Context context = template.getVelocityContext();
                 context.put("message", message);
                 context.put("title", "Configuration error");
                 template.renderXHTML("500init.vm");
         }
Referenced by BaseServlet.doGet().
Member Data Documentation
config
Configuration config private inherited
Referenced by BaseServlet.addDocumentMetadata(), BaseServlet.addPageMetadata(), GeoBrowserServlet.doGet(), RootServlet.doGet(), ValuesDataURLServlet.doGet(), WebURIServlet.doGet(), DataURLServlet.doGet(), PageURLServlet.doGet(), ValuesURLServlet.doGet(), SearchServlet.doGet(), ValuesBaseServlet.doGet(), BaseServlet.doGet(), BaseServlet.init(), and BaseServlet.send404().
fullIRIPattern
Pattern fullIRIPattern = Pattern.compile("(-?)!(.*?)///(.*)") static private inherited
Referenced by ValuesBaseServlet.doGet().
initError
String initError private inherited
Referenced by BaseServlet.doGet(), and BaseServlet.init().
prefixedNamePattern
Pattern prefixedNamePattern = Pattern.compile("(-?)([^!:/]*):([^:/]*)/(.*)") static private inherited
Referenced by ValuesBaseServlet.doGet().
serialVersionUID
final long serialVersionUID = -7927775670218866340L static private