GeoPubby: PubbyNegotiatorTest Class Reference
PubbyNegotiatorTest Class Reference
Public Member Functions
void setUp ()
void testAcceptRDFXML ()
void testAcceptHTML ()
void testAcceptXHTMLGetsHTML ()
void testAcceptJSON ()
void testGetTurtle ()
void testGetN3 ()
void testGetNTriples ()
void testBrowsersGetHTML ()
void testAcceptXMLGetsRDFXML ()
void testNoAcceptGetsHTML ()
void testSafariGetsHTML ()
void testAcceptEverythingGetsHTML ()
void testFirefox3GetsHTML ()
void testTabulatorGetsRDF ()
void testDataURIDefaultsToN3ForFirefox ()
void testDataURIDefaultsToN3ForSafari ()
Private Attributes
ContentTypeNegotiator negotiator
Member Function Documentation
setUp()
void setUp ()
{
                 negotiator = PubbyNegotiator.getPubbyNegotiator();
         }
References PubbyNegotiator.getPubbyNegotiator(), and PubbyNegotiatorTest.negotiator.
testAcceptEverythingGetsHTML()
void testAcceptEverythingGetsHTML ()
{
                 assertEquals("text/html", negotiator.getBestMatch("*/*").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testAcceptHTML()
void testAcceptHTML ()
{
                 assertEquals("text/html",
                                 negotiator.getBestMatch("text/html").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testAcceptJSON()
void testAcceptJSON ()
{
                 assertEquals("application/json",
                                 negotiator.getBestMatch("application/json").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testAcceptRDFXML()
void testAcceptRDFXML ()
{
                 assertEquals("application/rdf+xml",
                                 negotiator.getBestMatch("application/rdf+xml").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testAcceptXHTMLGetsHTML()
void testAcceptXHTMLGetsHTML ()
{
                 assertEquals("text/html",
                                 negotiator.getBestMatch("application/xhtml+xml").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testAcceptXMLGetsRDFXML()
void testAcceptXMLGetsRDFXML ()
{
                 assertEquals("application/rdf+xml",
                                 negotiator.getBestMatch("application/xml").getMediaType());
                 assertEquals("application/rdf+xml",
                                 negotiator.getBestMatch("text/xml").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testBrowsersGetHTML()
void testBrowsersGetHTML ()
{
                 // Safari and Mozilla have text/html;q=0.9,text/plain;q=0.8,*/*;q=0.5
                 // We want them to see HTML
                 assertEquals("text/html",
                                 negotiator.getBestMatch("text/html;q=0.9,text/plain;q=0.8,*/*;q=0.5").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testDataURIDefaultsToN3ForFirefox()
void testDataURIDefaultsToN3ForFirefox ()
{
                 assertEquals("text/rdf+n3;charset=utf-8",
                                 PubbyNegotiator.getDataNegotiator().getBestMatch(
                                                 "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                                 ).getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), PubbyNegotiator.getDataNegotiator(), and MediaRangeSpec.getMediaType().
testDataURIDefaultsToN3ForSafari()
void testDataURIDefaultsToN3ForSafari ()
{
                 assertEquals("text/rdf+n3;charset=utf-8",
                                 PubbyNegotiator.getDataNegotiator().getBestMatch(
                                                 "text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,"+
                                                 "text/plain;q=0.8,image/png,*/*;q=0.5",
                                                 "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; en-us) " +
                                                 "AppleWebKit/525.18 (KHTML, like Gecko) " +
                                                 "Version/3.1.2 Safari/525.20.1"
                                 ).getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), PubbyNegotiator.getDataNegotiator(), and MediaRangeSpec.getMediaType().
testFirefox3GetsHTML()
void testFirefox3GetsHTML ()
{
                 // Firefox 3.0.1, OS X
                 assertEquals("text/html",
                                 negotiator.getBestMatch(
                                                 "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                                                 "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.0.1) " +
                                                 "Gecko/2008070206 Firefox/3.0.1").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testGetN3()
void testGetN3 ()
{
                 assertEquals("text/rdf+n3;charset=utf-8",
                                 negotiator.getBestMatch("text/rdf+n3").getMediaType());
                 assertEquals("text/rdf+n3;charset=utf-8",
                                 negotiator.getBestMatch("text/n3").getMediaType());
                 assertEquals("text/rdf+n3;charset=utf-8",
                                 negotiator.getBestMatch("application/n3").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testGetNTriples()
void testGetNTriples ()
{
                 assertEquals("text/plain",
                                 negotiator.getBestMatch("text/plain").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testGetTurtle()
void testGetTurtle ()
{
                 assertEquals("application/x-turtle",
                                 negotiator.getBestMatch("application/x-turtle").getMediaType());
                 assertEquals("application/x-turtle",
                                 negotiator.getBestMatch("application/turtle").getMediaType());
                 assertEquals("application/x-turtle",
                                 negotiator.getBestMatch("text/turtle").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testNoAcceptGetsHTML()
void testNoAcceptGetsHTML ()
{
                 assertEquals("text/html",
                                 negotiator.getBestMatch(null).getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testSafariGetsHTML()
void testSafariGetsHTML ()
{
                 // Some versions of Safari send a broken "*/*" Accept header.
                 // We must override this to send HTML.
                 assertEquals("text/html",
                                 negotiator.getBestMatch("*/*",
                                                 "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en) " +
                                                 "AppleWebKit/522.11.1 (KHTML, like Gecko) " +
                                                 "Version/3.0.3 Safari/522.12.1").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
testTabulatorGetsRDF()
void testTabulatorGetsRDF ()
{
                 // Tabulator 0.8.5 on Firefox 3.0.1, OS X
                 assertEquals("application/rdf+xml",
                                 negotiator.getBestMatch(
                                                 "application/rdf+xml, application/xhtml+xml;q=0.3, text/xml;q=0.2, " +
                                                 "application/xml;q=0.2, text/html;q=0.3, text/plain;q=0.1, text/n3, " +
                                                 "text/rdf+n3;q=0.5, application/x-turtle;q=0.2, text/turtle;q=1",
                                                 "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.0.1) " +
                                                 "Gecko/2008070206 Firefox/3.0.1").getMediaType());
         }
References ContentTypeNegotiator.getBestMatch(), MediaRangeSpec.getMediaType(), and PubbyNegotiatorTest.negotiator.
Member Data Documentation
negotiator
ContentTypeNegotiator negotiator private
Referenced by PubbyNegotiatorTest.setUp(), PubbyNegotiatorTest.testAcceptEverythingGetsHTML(), PubbyNegotiatorTest.testAcceptHTML(), PubbyNegotiatorTest.testAcceptJSON(), PubbyNegotiatorTest.testAcceptRDFXML(), PubbyNegotiatorTest.testAcceptXHTMLGetsHTML(), PubbyNegotiatorTest.testAcceptXMLGetsRDFXML(), PubbyNegotiatorTest.testBrowsersGetHTML(), PubbyNegotiatorTest.testFirefox3GetsHTML(), PubbyNegotiatorTest.testGetN3(), PubbyNegotiatorTest.testGetNTriples(), PubbyNegotiatorTest.testGetTurtle(), PubbyNegotiatorTest.testNoAcceptGetsHTML(), PubbyNegotiatorTest.testSafariGetsHTML(), and PubbyNegotiatorTest.testTabulatorGetsRDF().