GeoPubby: MediaRangeSpecTest Class Reference
MediaRangeSpecTest Class Reference
Public Member Functions
void testSimpleSyntax ()
void testGetType ()
void testGetSubtype ()
void testGetMediaType ()
void testSimpleParameters ()
void testWithParameters ()
void testCaseInsensitive ()
void testQuotedParameter ()
void testParameterValueEscaping ()
void testParameterValueEscapingRoundTrip ()
void testSimpleQuality ()
void testQualityAfterParameter ()
void testParametersAfterQualityAreIgnored ()
void testQualityValue ()
void testIllegalQualityValue ()
void testIllegalSyntax ()
void testNoWildcard ()
void testWildcard ()
void testIllegalWildcard ()
void testNoWildcardsInMediaType ()
void testAcceptOneRange ()
void testAcceptTwoRanges ()
void testAcceptIgnoreWSAndJunk ()
void testAcceptWithQuality ()
void testGetPrecedence ()
void testCaseInsensitiveMatch ()
void testGetBestMatchSameQuality ()
Private Member Functions
void assertIllegalMediaTypeSyntax (String mediaType)
void assertMediaRangeInList (List< MediaRangeSpec > list, int index, String mediaType)
Member Function Documentation
assertIllegalMediaTypeSyntax()
void assertIllegalMediaTypeSyntax (String mediaType) private
References MediaRangeSpec.parseRange().
Referenced by MediaRangeSpecTest.testIllegalSyntax().
{
                 assertNull(MediaRangeSpec.parseRange(mediaType));
         }
assertMediaRangeInList()
void assertMediaRangeInList (List< MediaRangeSpec > list, int index, String mediaType) private
References MediaRangeSpec.getMediaType().
Referenced by MediaRangeSpecTest.testAcceptIgnoreWSAndJunk(), MediaRangeSpecTest.testAcceptOneRange(), MediaRangeSpecTest.testAcceptTwoRanges(), and MediaRangeSpecTest.testAcceptWithQuality().
{
                 MediaRangeSpec range = (MediaRangeSpec) list.get(index);
                 assertEquals(mediaType, range.getMediaType());
         }
testAcceptIgnoreWSAndJunk()
void testAcceptIgnoreWSAndJunk ()
References MediaRangeSpecTest.assertMediaRangeInList(), and MediaRangeSpec.parseAccept().
{
                 List<MediaRangeSpec> accept = MediaRangeSpec.parseAccept("a/b , asdf , c/d");
                 assertEquals(2, accept.size());
                 assertMediaRangeInList(accept, 0, "a/b");
                 assertMediaRangeInList(accept, 1, "c/d");
         }
testAcceptOneRange()
void testAcceptOneRange ()
References MediaRangeSpecTest.assertMediaRangeInList(), and MediaRangeSpec.parseAccept().
{
                 List<MediaRangeSpec> accept = MediaRangeSpec.parseAccept("a/b");
                 assertNotNull(accept);
                 assertEquals(1, accept.size());
                 assertMediaRangeInList(accept, 0, "a/b");
         }
testAcceptTwoRanges()
void testAcceptTwoRanges ()
References MediaRangeSpecTest.assertMediaRangeInList(), and MediaRangeSpec.parseAccept().
{
                 List<MediaRangeSpec> accept = MediaRangeSpec.parseAccept("a/b,c/d");
                 assertEquals(2, accept.size());
                 assertMediaRangeInList(accept, 0, "a/b");
                 assertMediaRangeInList(accept, 1, "c/d");
         }
testAcceptWithQuality()
void testAcceptWithQuality ()
References MediaRangeSpecTest.assertMediaRangeInList(), and MediaRangeSpec.parseAccept().
{
                 List<MediaRangeSpec> accept = MediaRangeSpec.parseAccept("a/b;q=0.6,c/d;q=0.8");
                 assertEquals(2, accept.size());
                 assertMediaRangeInList(accept, 0, "a/b");
                 assertMediaRangeInList(accept, 1, "c/d");
                 assertEquals(0.6, ((MediaRangeSpec) accept.get(0)).getQuality(), 0.00001);
                 assertEquals(0.8, ((MediaRangeSpec) accept.get(1)).getQuality(), 0.00001);
         }
testCaseInsensitive()
void testCaseInsensitive ()
References MediaRangeSpec.getMediaType(), and MediaRangeSpec.parseRange().
{
                 assertEquals("a/b;c=D", MediaRangeSpec.parseRange("A/B;C=D").getMediaType());
         }
testCaseInsensitiveMatch()
void testCaseInsensitiveMatch ()
References MediaRangeSpec.getPrecedence(), and MediaRangeSpec.parseType().
{
                 assertEquals(4, MediaRangeSpec.parseType("a/b;c=d").getPrecedence(
                                 MediaRangeSpec.parseType("A/B;C=d")));
         }
testGetBestMatchSameQuality()
void testGetBestMatchSameQuality ()
References MediaRangeSpec.getBestMatch(), MediaRangeSpec.getMediaType(), MediaRangeSpec.parseAccept(), and MediaRangeSpec.parseType().
{
                 List<MediaRangeSpec> accept = MediaRangeSpec.parseAccept("*/*,a/*,a/b,a/b;c=d");
                 assertEquals("*/*", MediaRangeSpec.parseType("z/b").getBestMatch(accept).getMediaType());
                 assertEquals("a/*", MediaRangeSpec.parseType("a/z").getBestMatch(accept).getMediaType());
                 assertEquals("a/b", MediaRangeSpec.parseType("a/b").getBestMatch(accept).getMediaType());
                 assertEquals("a/b", MediaRangeSpec.parseType("a/b;c=z").getBestMatch(accept).getMediaType());
                 assertEquals("a/b", MediaRangeSpec.parseType("a/b;z=d").getBestMatch(accept).getMediaType());
                 assertEquals("a/b;c=d", MediaRangeSpec.parseType("a/b;c=d").getBestMatch(accept).getMediaType());
                 assertEquals("a/b;c=d", MediaRangeSpec.parseType("a/b;c=d;z=z").getBestMatch(accept).getMediaType());
         }
testGetMediaType()
void testGetMediaType ()
References MediaRangeSpec.getMediaType(), and MediaRangeSpec.parseRange().
{
                 assertEquals("foo-123_x/foo-123_y",
                                 MediaRangeSpec.parseRange("foo-123_x/foo-123_y").getMediaType());
         }
testGetPrecedence()
void testGetPrecedence ()
References MediaRangeSpec.getPrecedence(), MediaRangeSpec.parseRange(), and MediaRangeSpec.parseType().
{
                 MediaRangeSpec m = MediaRangeSpec.parseType("a/b;c=d;e=f");
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("z/b;c=d;e=f")));
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("a/z;c=d;e=f")));
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("a/b;x=y")));
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("a/b;c=z;e=f")));
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("a/b;c=z;e=z")));
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("a/b;x=y;c=d")));
                 assertEquals(0, m.getPrecedence(MediaRangeSpec.parseRange("a/b;c=d;e=z")));
                 assertEquals(1, m.getPrecedence(MediaRangeSpec.parseRange("*/*;c=d;e=f")));
                 assertEquals(2, m.getPrecedence(MediaRangeSpec.parseRange("a/*;c=d;e=f")));
                 assertEquals(3, m.getPrecedence(MediaRangeSpec.parseRange("a/b")));
                 assertEquals(4, m.getPrecedence(MediaRangeSpec.parseRange("a/b;c=d")));
                 assertEquals(4, m.getPrecedence(MediaRangeSpec.parseRange("a/b;e=f")));
                 assertEquals(5, m.getPrecedence(MediaRangeSpec.parseRange("a/b;e=f;c=d")));
         }
testGetSubtype()
void testGetSubtype ()
References MediaRangeSpec.getSubtype(), and MediaRangeSpec.parseRange().
{
                 assertEquals("foo-123_x", MediaRangeSpec.parseRange("bar/foo-123_x").getSubtype());
         }
testGetType()
void testGetType ()
References MediaRangeSpec.getType(), and MediaRangeSpec.parseRange().
{
                 assertEquals("foo-123_x", MediaRangeSpec.parseRange("foo-123_x/bar").getType());
         }
testIllegalQualityValue()
void testIllegalQualityValue ()
References MediaRangeSpec.getQuality(), and MediaRangeSpec.parseRange().
{
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=\"\"").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=a").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=2").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=0.1000").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=-0.1").getQuality(), 0.00001);
         }
testIllegalSyntax()
void testIllegalSyntax ()
References MediaRangeSpecTest.assertIllegalMediaTypeSyntax().
{
                 assertIllegalMediaTypeSyntax("a");
                 assertIllegalMediaTypeSyntax(" a/b ");
                 assertIllegalMediaTypeSyntax("a / b");
                 assertIllegalMediaTypeSyntax("\u00E4/b");
                 assertIllegalMediaTypeSyntax("a\na/b");
                 assertIllegalMediaTypeSyntax("a/b;c");
                 assertIllegalMediaTypeSyntax("a/b;c=");
                 assertIllegalMediaTypeSyntax("a/b;c = d");
                 assertIllegalMediaTypeSyntax("a/b;c=d e");
                 assertIllegalMediaTypeSyntax("a/b;c=\"d\"e");
                 assertIllegalMediaTypeSyntax("a/b;c=\"d\"\"");
         }
testIllegalWildcard()
void testIllegalWildcard ()
References MediaRangeSpec.parseRange().
{
                 assertNull(MediaRangeSpec.parseRange("*/b"));
         }
testNoWildcard()
void testNoWildcard ()
References MediaRangeSpec.isWildcardSubtype(), MediaRangeSpec.isWildcardType(), and MediaRangeSpec.parseRange().
{
                 assertFalse(MediaRangeSpec.parseRange("a/b").isWildcardType());
                 assertFalse(MediaRangeSpec.parseRange("a/b").isWildcardSubtype());
         }
testNoWildcardsInMediaType()
void testNoWildcardsInMediaType ()
References MediaRangeSpec.parseType().
{
                 assertNull(MediaRangeSpec.parseType("*/*"));
                 assertNull(MediaRangeSpec.parseType("a/*"));
         }
testParametersAfterQualityAreIgnored()
void testParametersAfterQualityAreIgnored ()
References MediaRangeSpec.getParameter(), MediaRangeSpec.getQuality(), and MediaRangeSpec.parseRange().
{
                 MediaRangeSpec m = MediaRangeSpec.parseRange("a/b;q=0.5;c=d");
                 assertNotNull(m);
                 assertNull(m.getParameter("c"));
                 assertEquals(0.5, m.getQuality(), 0.00001);
         }
testParameterValueEscaping()
void testParameterValueEscaping ()
References MediaRangeSpec.getParameter(), and MediaRangeSpec.parseRange().
{
                 assertEquals("", MediaRangeSpec.parseRange("a/b;c=\"\"").getParameter("c"));
                 assertEquals("a", MediaRangeSpec.parseRange("a/b;c=\"\\a\"").getParameter("c"));
                 assertEquals("\\", MediaRangeSpec.parseRange("a/b;c=\"\\\\\"").getParameter("c"));
                 assertEquals("\"", MediaRangeSpec.parseRange("a/b;c=\"\\\"\"").getParameter("c"));
                 assertEquals(" \\ \" a ",
                                 MediaRangeSpec.parseRange("a/b;c=\" \\\\ \\\" \\a \"").getParameter("c"));
         }
testParameterValueEscapingRoundTrip()
void testParameterValueEscapingRoundTrip ()
References MediaRangeSpec.getMediaType(), and MediaRangeSpec.parseRange().
{
                 assertEquals("a/b;c=\" \\\\ \\\" a \"",
                                 MediaRangeSpec.parseRange("a/b;c=\" \\\\ \\\" \\a \"").getMediaType());
         }
testQualityAfterParameter()
void testQualityAfterParameter ()
References MediaRangeSpec.getParameter(), MediaRangeSpec.getQuality(), and MediaRangeSpec.parseRange().
{
                 MediaRangeSpec m = MediaRangeSpec.parseRange("a/b;c=d;q=0.5");
                 assertNotNull(m);
                 assertEquals("d", m.getParameter("c"));
                 assertEquals(0.5, m.getQuality(), 0.00001);
         }
testQualityValue()
void testQualityValue ()
References MediaRangeSpec.getQuality(), and MediaRangeSpec.parseRange().
{
                 assertEquals(1, MediaRangeSpec.parseRange("a/b").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=1").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=1.").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=1.0").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=1.00").getQuality(), 0.00001);
                 assertEquals(1, MediaRangeSpec.parseRange("a/b;q=1.000").getQuality(), 0.00001);
                 assertEquals(0, MediaRangeSpec.parseRange("a/b;q=0").getQuality(), 0.00001);
                 assertEquals(0, MediaRangeSpec.parseRange("a/b;q=0.").getQuality(), 0.00001);
                 assertEquals(0, MediaRangeSpec.parseRange("a/b;q=0.0").getQuality(), 0.00001);
                 assertEquals(0, MediaRangeSpec.parseRange("a/b;q=0.00").getQuality(), 0.00001);
                 assertEquals(0, MediaRangeSpec.parseRange("a/b;q=0.000").getQuality(), 0.00001);
                 assertEquals(0.5, MediaRangeSpec.parseRange("a/b;q=0.5").getQuality(), 0.00001);
                 assertEquals(0.55, MediaRangeSpec.parseRange("a/b;q=0.55").getQuality(), 0.00001);
                 assertEquals(0.555, MediaRangeSpec.parseRange("a/b;q=0.555").getQuality(), 0.00001);
         }
testQuotedParameter()
void testQuotedParameter ()
References MediaRangeSpec.getMediaType(), and MediaRangeSpec.parseRange().
{
                 assertEquals("a/b;c=d", MediaRangeSpec.parseRange("a/b;c=\"d\"").getMediaType());
                 assertEquals("a/b;c=\"d e\"", MediaRangeSpec.parseRange("a/b;c=\"d e\"").getMediaType());
         }
testSimpleParameters()
void testSimpleParameters ()
References MediaRangeSpec.getMediaType(), MediaRangeSpec.getParameter(), MediaRangeSpec.getParameterNames(), MediaRangeSpec.getSubtype(), MediaRangeSpec.getType(), and MediaRangeSpec.parseRange().
{
                 MediaRangeSpec spec = MediaRangeSpec.parseRange("a/b;c=d;e=f");
                 assertEquals("a", spec.getType());
                 assertEquals("b", spec.getSubtype());
                 assertEquals("a/b;c=d;e=f", spec.getMediaType());
                 assertEquals("d", spec.getParameter("c"));
                 assertEquals("f", spec.getParameter("e"));
                 assertEquals(Arrays.asList(new String[]{"c", "e"}), spec.getParameterNames());
         }
testSimpleQuality()
void testSimpleQuality ()
References MediaRangeSpec.getParameter(), MediaRangeSpec.getQuality(), and MediaRangeSpec.parseRange().
{
                 MediaRangeSpec m = MediaRangeSpec.parseRange("a/b;q=0.5");
                 assertNotNull(m);
                 assertNull(m.getParameter("q"));
                 assertEquals(0.5, m.getQuality(), 0.00001);
         }
testSimpleSyntax()
void testSimpleSyntax ()
References MediaRangeSpec.getMediaType(), MediaRangeSpec.getParameter(), MediaRangeSpec.getParameterNames(), MediaRangeSpec.getSubtype(), MediaRangeSpec.getType(), and MediaRangeSpec.parseRange().
{
                 MediaRangeSpec spec = MediaRangeSpec.parseRange("a/b");
                 assertEquals("a", spec.getType());
                 assertEquals("b", spec.getSubtype());
                 assertEquals("a/b", spec.getMediaType());
                 assertNull(spec.getParameter("c"));
                 assertTrue(spec.getParameterNames().isEmpty());
         }
testWildcard()
void testWildcard ()
References MediaRangeSpec.isWildcardSubtype(), MediaRangeSpec.isWildcardType(), and MediaRangeSpec.parseRange().
{
                 assertTrue(MediaRangeSpec.parseRange("*/*").isWildcardType());
                 assertFalse(MediaRangeSpec.parseRange("a/*").isWildcardType());
                 assertTrue(MediaRangeSpec.parseRange("a/*").isWildcardSubtype());
         }
testWithParameters()
void testWithParameters ()
References MediaRangeSpec.getMediaType(), and MediaRangeSpec.parseRange().
{
                 assertEquals("a/b;c=d", MediaRangeSpec.parseRange("a/b ; c=d").getMediaType());
                 assertEquals("a/b;c=d;e=f", MediaRangeSpec.parseRange("a/b ; c=d ; e=f").getMediaType());
         }